import {test,expect,type Page} from './test-fixture';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft} from '../../src/objects';
import {saveVector,vectorGraphic} from '../../src/physics';
import {saveCoordinates} from '../../src/coordinates';
import {readFile} from 'node:fs/promises';
import {canvasPoint} from './view-helpers';
async function saved(page:Page){const p=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await(await p).path())!,'utf8'));}
function fixture(angle=-35,coordinates=true){const s=new DocumentStore(),book=saveObject(s,{...presetDraft('ordinary'),name:'Book'}),v=saveVector(s,{kind:'velocity',targetId:book,magnitude:{state:'unknown',unit:'m/s'},angle,length:100});const c=coordinates?saveCoordinates(s,{dimensions:2,angle:0,origin:[-120,100]}):undefined;return {s,v,c,book,symbol:s.document.semantics.variables[0].symbol};}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'angles.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');}
async function vectorAction(page:Page,symbol:string,action='Edit'){await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`${action} ${symbol}`,exact:true}).click();}
async function overlay(page:Page){return page.evaluate(()=>{const s=(window as any).Konva.stages[0];return {components:s.find('.vector-component').length,angles:s.find('.component-angle').map((n:any)=>({axis:n.getAttr('axis'),x:n.x(),y:n.y()})),labels:s.find('.angle-label').map((n:any)=>n.getAttr('math'))};});}
async function commit(page:Page){await page.locator('#save-vector').click();await expect(page.locator('#vector-dialog')).not.toBeVisible();}
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number}){if(mobile){const c=await page.context().newCDPSession(page);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=10;i++)await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/10,y:start.y+(end.y-start.y)*i/10}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:10});await page.mouse.up();}}
test('no standalone Angles; coordinate discovery, shared tolerance and 1D availability',async({page})=>{
 const {s,v,symbol}=fixture(-5,false);await page.goto('./');await load(page,s.document);await expect(page.locator('[data-action="angle"],[data-action="angles"],#angle-dialog,#angle-collection')).toHaveCount(0);await vectorAction(page,symbol);await expect(page.locator('#components-hint')).toHaveText('Define a coordinate system to display components and angles.');await expect(page.locator('#component-angle-section')).toBeHidden();await page.locator('#cancel-vector').click();
 await page.getByTitle('Coordinates',{exact:true}).click();await page.getByRole('button',{name:'Save coordinates'}).click();await vectorAction(page,symbol);await expect(page.locator('#component-angle-section')).toBeVisible();for(const id of ['#vector-angles','#component-angle-x','#component-angle-y'])await expect(page.locator(id)).toBeDisabled();await expect(page.locator('#component-angle-hint')).toContainText('two coordinate components');await page.locator('#cancel-vector').click();
 const d=await saved(page);d.presentation.elements.find((g:any)=>g.vectorId===v).points=[0,0,100,-100];await load(page,d);await vectorAction(page,symbol);await expect(page.locator('#component-angle-x')).toBeEnabled();await expect(page.locator('#vector-angles')).toBeChecked();await page.locator('#cancel-vector').click();await page.getByTitle('Coordinates',{exact:true}).click();await page.locator('#coordinate-dimensions').selectOption('1');await page.getByRole('button',{name:'Save coordinates'}).click();await vectorAction(page,symbol);await expect(page.locator('#component-angle-x')).toBeDisabled();await expect(page.locator('#component-angle-hint')).toContainText('2D');
});
test('complementary drafts, cancel, nearest Save constraint, replacement, clearing, reload and undo',async({page},info)=>{
 const {s,v,c,symbol}=fixture();await page.goto('./');await load(page,s.document);const original=await saved(page),g=original.presentation.elements.find((g:any)=>g.vectorId===v);
 await vectorAction(page,symbol);await expect(page.locator('#component-angle-x')).toHaveValue('');await expect(page.locator('#component-angle-y')).toHaveValue('');await page.locator('#component-angle-x').fill('30');await expect(page.locator('#component-angle-y')).toHaveValue('60');
 expect(await page.evaluate(id=>(window as any).Konva.stages[0].findOne('#'+id).points(),g.id)).toEqual(g.points);await page.locator('#component-angle-y').fill('25');await expect(page.locator('#component-angle-x')).toHaveValue('65');await page.locator('#cancel-vector').click();expect(await saved(page)).toEqual(original);
 await vectorAction(page,symbol);await page.locator('#component-angle-x').fill('30');await commit(page);const defined=await saved(page),vg=defined.presentation.elements.find((g:any)=>g.vectorId===v);expect(defined.semantics.vectors[0].componentAngle).toEqual({coordinateSystemId:c,axis:'x',value:30});expect(Math.hypot(vg.points[2],vg.points[3])).toBeCloseTo(100);expect(vg.points[2]).toBeGreaterThan(0);expect(vg.points[3]).toBeLessThan(0);expect([vg.x,vg.y]).toEqual([g.x,g.y]);await expect.poll(async()=>(await overlay(page)).labels).toEqual(['\\theta_{v,x}=30^\\circ','\\theta_{v,y}=60^\\circ']);
 const collisions=await page.evaluate(()=>{const stage=(window as any).Konva.stages[0],angles=stage.find('.angle-label').map((n:any)=>n.getClientRect()),others=[...stage.find('.component-label'),...stage.find('.semantic-label')].map((n:any)=>n.getClientRect());return angles.some((a:any,i:number)=>[...others,...angles.slice(i+1)].some((b:any)=>a.x<b.x+b.width && a.x+a.width>b.x && a.y<b.y+b.height && a.y+a.height>b.y));});expect(collisions).toBe(false);
 await page.screenshot({path:`test-results/defined-component-angles-${info.project.name}.png`});
 await page.getByTitle('Undo',{exact:true}).click();await expect.poll(async()=>(await overlay(page)).labels).toEqual(['\\theta_{v,x}','\\theta_{v,y}']);expect(await saved(page)).toEqual(original);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(defined);
 await vectorAction(page,symbol);await page.locator('#component-angle-y').fill('25');await commit(page);const changed=await saved(page);expect(changed.semantics.vectors[0].componentAngle.axis).toBe('y');await page.reload();await load(page,changed);await vectorAction(page,symbol);await expect(page.locator('#component-angle-x')).toHaveValue('65');await expect(page.locator('#component-angle-y')).toHaveValue('25');await page.locator('#component-angle-x').fill('');await expect(page.locator('#component-angle-y')).toHaveValue('');await commit(page);expect((await saved(page)).semantics.vectors[0]).not.toHaveProperty('componentAngle');await expect.poll(async()=>(await overlay(page)).labels).toEqual(['\\theta_{v,x}','\\theta_{v,y}']);await page.screenshot({path:`test-results/component-angles-${info.project.name}.png`});
});
test('both arcs originate at tail, selection and visibility switches gate the overlay without erasing values',async({page})=>{
 const {s,c,v,symbol}=fixture();s.document.semantics.vectors[0].componentAngle={coordinateSystemId:c!,axis:'x',value:35};await page.goto('./');await load(page,s.document);expect((await overlay(page)).angles).toHaveLength(0);await vectorAction(page,symbol,'Select');await expect.poll(async()=>(await overlay(page)).angles.length).toBe(2);expect((await overlay(page)).angles).toEqual([{axis:'x',x:0,y:0},{axis:'y',x:0,y:0}]);
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();expect((await overlay(page)).angles).toHaveLength(2);await vectorAction(page,symbol);await page.locator('#vector-angles').uncheck();await commit(page);expect((await overlay(page)).components).toBe(2);expect((await overlay(page)).angles).toHaveLength(0);expect((await saved(page)).semantics.vectors[0].componentAngle.value).toBe(35);
 await vectorAction(page,symbol);await page.locator('#vector-angles').check();await page.locator('#vector-components').uncheck();await expect(page.locator('#vector-angles')).toBeDisabled();await commit(page);expect((await overlay(page)).components).toBe(0);expect((await saved(page)).semantics.vectors[0].componentAngle.value).toBe(35);
 await vectorAction(page,symbol);await page.locator('#vector-components').check();await commit(page);await expect.poll(async()=>(await overlay(page)).angles.length).toBe(2);await page.getByTitle('Coordinates',{exact:true}).click();await page.getByRole('button',{name:'Save coordinates'}).click();expect((await overlay(page)).angles).toHaveLength(0);
});
test('coordinate changes and manual direction gestures invalidate definitions without silent replacement',async({page},info)=>{
 const {s,symbol,v}=fixture();await page.goto('./');await load(page,s.document);await vectorAction(page,symbol);await page.locator('#component-angle-x').fill('30');await commit(page);const defined=await saved(page);
 await page.getByTitle('Coordinates',{exact:true}).click();await page.locator('#coordinate-angle').fill('15');await page.getByRole('button',{name:'Save coordinates'}).click();const coordinates=await saved(page);expect(coordinates.presentation.elements).toEqual(defined.presentation.elements);expect(coordinates.semantics.vectors[0]).not.toHaveProperty('componentAngle');await vectorAction(page,symbol,'Select');await expect.poll(async()=>(await overlay(page)).labels).toEqual(['\\theta_{v,x}','\\theta_{v,y}']);
 await load(page,defined);await vectorAction(page,symbol,'Select');const g=defined.presentation.elements.find((g:any)=>g.vectorId===v);await gesture(page,info.project.name==='mobile',await canvasPoint(page,g.points[2],g.points[3]),await canvasPoint(page,60,-60));const dragged=await saved(page);expect(dragged.semantics.vectors[0]).not.toHaveProperty('componentAngle');await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(defined);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(dragged);
});
test('obsolete generic Angle files load and no longer block vector or coordinate deletion',async({page})=>{
 const {s,c,v,symbol}=fixture();const doc:any=s.document;doc.semantics.angles=[{id:'old',from:{type:'vector',vectorId:v},to:{type:'axis',coordinateSystemId:c,axis:'x',sign:1},value:30,visible:true,presentation:{x:30,y:30,labelOffset:[0,0]}}];await page.goto('./');await load(page,doc);expect((await saved(page)).semantics).not.toHaveProperty('angles');await vectorAction(page,symbol);await page.locator('#delete-vector').click();await expect(page.locator('#vector-dialog')).not.toBeVisible();await page.getByTitle('Coordinates',{exact:true}).click();await page.locator('#delete-coordinates').click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();
});
test('coordinate rotation gesture clears authored angles and undo restores the complete constraint',async({page},info)=>{
 const {s,symbol}=fixture();await page.goto('./');await load(page,s.document);await vectorAction(page,symbol);await page.locator('#component-angle-x').fill('30');await commit(page);const defined=await saved(page);
 await page.getByTitle('Coordinates',{exact:true}).click();await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();const p=await page.evaluate(()=>{const n=(window as any).Konva.stages[0].findOne('.coordinate-rotation-handle');return {x:n.x(),y:n.y()};});
 await gesture(page,info.project.name==='mobile',await canvasPoint(page,p.x,p.y),await canvasPoint(page,-120+105/Math.sqrt(2),100-105/Math.sqrt(2)));const changed=await saved(page);expect(Math.abs(changed.semantics.coordinateSystems[0].angle-45)).toBeLessThan(1);expect(changed.presentation.elements).toEqual(defined.presentation.elements);expect(changed.semantics.vectors[0]).not.toHaveProperty('componentAngle');
 await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(defined);
});
