import {canvasPoint as transformedPoint,fixtureView} from './view-helpers';
import {test,expect,type Page} from './test-fixture';
import {readFile} from 'node:fs/promises';
import {DocumentStore,newDocument} from '../../src/model';
import {saveObject,objectDraft} from '../../src/objects';
import {saveVector,vectorGraphic} from '../../src/physics';
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await (await pending).path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'cleanup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');await fixtureView(page,doc);}
async function coordinates(page:Page){await page.getByTitle('Coordinates',{exact:true}).click();await expect(page.locator('#coordinate-dialog')).toBeVisible();}
async function submitCoordinates(page:Page){await page.getByRole('button',{name:'Save coordinates',exact:true}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();}
async function selectVector(page:Page,symbol:string){await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Select ${symbol}`,exact:true}).click();}
async function rendered(page:Page){return page.evaluate(()=>{const s=(window as any).Konva.stages[0];return {components:s.find('.vector-component').map((n:any)=>({axis:n.getAttr('axis'),direction:n.getAttr('coordinateDirection'),points:n.points()})),axes:s.find('.coordinate-axis').map((n:any)=>({axis:n.getAttr('axis'),points:n.points()}))};});}
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number}){if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:8});await page.mouse.up();}}
async function canvasPoint(page:Page,x:number,y:number){return transformedPoint(page,x,y);}
function fixture(){const d=newDocument(800,600);d.presentation.canvas.minX=0;d.presentation.canvas.minY=0;const s=new DocumentStore(d);const object=saveObject(s,{...objectDraft(s),name:'Book'});s.update(s.document.presentation.elements[0].id,{x:200,y:300});const id=saveVector(s,{kind:'velocity',targetId:object,magnitude:{state:'unknown',unit:'m/s'}});vectorGraphic(s.document,id)!.points=[0,0,100*Math.cos(72*Math.PI/180),-100*Math.sin(72*Math.PI/180)];s.document.semantics.coordinateSystems=[{id:'axes',dimensions:2,angle:37,origin:[500,350],visible:true}];return s.document;}
test('reversed axes update signed conventions, retain threshold and persist across dimensions and gestures',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');const original=fixture();await load(page,original);const symbol=original.semantics.variables[0].symbol;await selectVector(page,symbol);await expect.poll(async()=>(await rendered(page)).components.length).toBe(2);const before=await rendered(page);
 for(const [reverseX,reverseY]of [[false,false],[true,false],[false,true],[true,true]]){
  await coordinates(page);await page.locator('#coordinate-reverse-x').setChecked(reverseX);await page.locator('#coordinate-reverse-y').setChecked(reverseY);await submitCoordinates(page);
  await expect.poll(async()=>(await rendered(page)).components.map((p:any)=>p.direction)).toEqual([reverseX?-1:1,reverseY?-1:1]);const view=await rendered(page);
  for(let i=0;i<2;i++){expect(view.components[i].points).toEqual(before.components[i].points);for(const j of [0,1,2,3])expect(view.axes[i].points[j]).toBeCloseTo(before.axes[i].points[j]*([reverseX,reverseY][i]?-1:1));}
  const doc=await saved(page);expect(doc.presentation).toEqual(original.presentation);expect(doc.semantics.vectors).toEqual(original.semantics.vectors);expect(doc.semantics.variables).toEqual(original.semantics.variables);expect(doc.semantics.coordinateSystems[0]).toMatchObject({origin:[500,350],angle:37,reverseX,reverseY});
 }
 // Exact tolerance boundary is unaffected by either or both reversals.
 for(const [angle,count]of [[62,0],[61.9,2],[82,0],[82.1,2]]){await coordinates(page);await page.locator('#coordinate-angle').fill(String(angle));await submitCoordinates(page);await expect.poll(async()=>(await rendered(page)).components.length).toBe(count);}
 await coordinates(page);await page.locator('#coordinate-angle').fill('37');await page.locator('#coordinate-dimensions').selectOption('1');await expect(page.locator('#reverse-y-label')).toBeHidden();await expect(page.locator('#coordinate-reverse-y')).toBeChecked();await submitCoordinates(page);await expect.poll(async()=>(await rendered(page)).components.length).toBe(1);
 await coordinates(page);await page.locator('#coordinate-dimensions').selectOption('2');await expect(page.locator('#coordinate-reverse-y')).toBeVisible();await expect(page.locator('#coordinate-reverse-y')).toBeChecked();await submitCoordinates(page);await expect.poll(async()=>(await rendered(page)).components.length).toBe(2);
 // The handle rotates the reference axes independently of the reversed positive directions.
 const handle=await page.evaluate(()=>{const n=(window as any).Konva.stages[0].findOne('.coordinate-rotation-handle');return {x:n.x(),y:n.y()};});await gesture(page,info.project.name==='mobile',await canvasPoint(page,handle.x,handle.y),await canvasPoint(page,500+105*Math.cos(20*Math.PI/180),350-105*Math.sin(20*Math.PI/180)));const final=await saved(page);expect(Math.abs(final.semantics.coordinateSystems[0].angle-20)).toBeLessThan(1);expect(final.semantics.coordinateSystems[0]).toMatchObject({reverseX:true,reverseY:true,origin:[500,350]});expect(final.presentation).toEqual(original.presentation);
 await page.reload();await load(page,final);expect(await saved(page)).toEqual(final);await selectVector(page,symbol);await expect.poll(async()=>(await rendered(page)).components.map((p:any)=>p.direction)).toEqual([-1,-1]);expect(errors).toEqual([]);await page.screenshot({path:`test-results/cleanup-axes-${info.project.name}.png`});
});
test('toolbar outline icons keep names, touch targets, eligibility and exact vector ordering',async({page},info)=>{
 await page.goto('./');await expect(page.locator('#toolbar-top .toolbar-icon')).toHaveCount(5);for(const icon of await page.locator('#toolbar-top .toolbar-icon').all()){await expect(icon).toHaveAttribute('fill','none');await expect(icon).toHaveAttribute('stroke','currentColor');await expect(icon).toHaveAttribute('stroke-width','1.75');await expect(icon).toHaveAttribute('aria-hidden','true');}
 await expect(page.getByTitle('Vector',{exact:true})).toBeDisabled();for(const control of [page.getByTitle('Object',{exact:true}),page.getByTitle('Vector',{exact:true}),page.getByTitle('Coordinates',{exact:true}),page.locator('#elements-menu summary')]){const box=(await control.boundingBox())!;expect(box.height).toBeGreaterThanOrEqual(44);expect(box.width).toBeGreaterThanOrEqual(44);expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(page.viewportSize()!.width);}
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Book');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();await page.getByTitle('Vector',{exact:true}).click();expect(await page.locator('#vector-kind option').allTextContents()).toEqual(['Force','Field','Separation','Acceleration','Velocity','Displacement']);const eligibility=await page.locator('#vector-kind option').evaluateAll(options=>options.map((o:any)=>({name:o.textContent,disabled:o.disabled})));expect(eligibility).toEqual([{name:'Force',disabled:true},{name:'Field',disabled:true},{name:'Separation',disabled:true},{name:'Acceleration',disabled:false},{name:'Velocity',disabled:false},{name:'Displacement',disabled:false}]);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.locator('#elements-menu summary').focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Objects',exact:true})).toBeVisible();await page.getByRole('button',{name:'Objects',exact:true}).click();await expect(page.locator('#collection-dialog')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await page.screenshot({path:`test-results/cleanup-toolbar-${info.project.name}.png`});
});
test('visible Earth defaults allow independent editing and preserve legacy custom planets',async({page},info)=>{
 await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-type').selectOption('planetSurface');await expect(page.locator('#object-name')).toHaveValue('Earth');await expect(page.locator('#object-representation')).toHaveValue('surface');await expect(page.locator('#gravity-value')).toHaveValue('9.8');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const earth=await saved(page);expect(earth.semantics.objects[0]).toMatchObject({name:'Earth',category:'planetSurface'});expect(earth.presentation.elements[0]).toMatchObject({kind:'surface',visible:true});
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Earth',exact:true}).click();await page.locator('#object-name').fill('Mars');await expect(page.locator('#gravity-value')).toHaveValue('9.8');await page.locator('#gravity-value').fill('3.7');await expect(page.locator('#object-name')).toHaveValue('Mars');await page.locator('#object-representation').selectOption('none');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const mars=await saved(page);expect(mars.semantics.objects[0]).toMatchObject({name:'Mars',category:'planetSurface'});expect(mars.semantics.variables[0].value).toBe(3.7);expect(mars.presentation.elements[0].visible).toBe(false);
 await page.reload();await load(page,mars);expect(await saved(page)).toEqual(mars);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Mars',exact:true}).click();await expect(page.locator('#object-name')).toHaveValue('Mars');await expect(page.locator('#gravity-value')).toHaveValue('3.7');await expect(page.locator('#object-representation')).toHaveValue('none');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();expect((await saved(page)).presentation).toEqual(mars.presentation);await page.screenshot({path:`test-results/cleanup-defaults-${info.project.name}.png`});
});
