import {fixtureOrientation} from './view-helpers';
import {canvasPoint as transformedPoint,fixtureView} from './view-helpers';
import {test,expect,type Page} from './test-fixture';
import {readFile} from 'node:fs/promises';
import {DocumentStore,newDocument} from '../../src/model';
import {saveObject,objectDraft} from '../../src/objects';
import {saveVector,vectorGraphic} from '../../src/physics';
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await (await pending).path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'coordinates.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');await fixtureView(page,doc);}
async function selectVector(page:Page,symbol:string){await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Select ${symbol}`,exact:true}).click();}
async function count(page:Page){return page.evaluate(()=>(window as any).Konva.stages[0].find('.vector-component').length);}
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number},mid?:()=>Promise<void>){if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8}]});if(i===4)await mid?.();}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move((start.x+end.x)/2,(start.y+end.y)/2,{steps:4});await mid?.();await page.mouse.move(end.x,end.y,{steps:4});await page.mouse.up();}}
async function canvasPoint(page:Page,x:number,y:number){return transformedPoint(page,x,y);}
function fixture(){const d=newDocument(800,600);d.presentation.canvas.minX=0;d.presentation.canvas.minY=0;const s=new DocumentStore(d);const o=saveObject(s,{...objectDraft(s),name:'Book'});s.update(s.document.presentation.elements[0].id,{x:200,y:300});const id=saveVector(s,{kind:'velocity',targetId:o,magnitude:{state:'unknown',unit:'m/s'}});vectorGraphic(s.document,id)!.points=[0,0,100,-100];return s.document;}
test('coordinate creation, configuration, hide/show, dimensions and deletion persist',async({page})=>{
 await page.goto('./');await expect(page.getByRole('button',{name:'Edit',exact:true})).toHaveCount(0);
 await page.getByTitle('Coordinates',{exact:true}).click();await page.locator('#coordinate-dimensions').selectOption('1');await expect(page.locator('#coordinate-angle')).toHaveCount(0);await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();
 let doc=await saved(page),c=doc.semantics.coordinateSystems[0];expect(doc.semantics.coordinateSystems).toHaveLength(1);expect(c).toMatchObject({dimensions:1,angle:0,visible:true,origin:[0,0]});
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Coordinate System',exact:true}).click();await page.locator('#coordinate-dimensions').selectOption('2');await page.locator('#coordinate-visible').uncheck();await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();
 doc=await saved(page);expect(doc.semantics.coordinateSystems[0]).toMatchObject({...c,dimensions:2,visible:false});expect(await page.evaluate(()=>(window as any).Konva.stages[0].find('.coordinate-rotation-handle').length)).toBe(0);
 await page.reload();await load(page,doc);expect(await saved(page)).toEqual(doc);
 await page.getByTitle('Coordinates',{exact:true}).click();await page.locator('#coordinate-visible').check();await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();
 await page.getByTitle('Coordinates',{exact:true}).click();await page.getByRole('button',{name:'Delete coordinate system',exact:true}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();expect((await saved(page)).semantics.coordinateSystems).toEqual([]);
});
test('active components follow rotated tolerance and coordinate gestures without mutating vectors',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');const doc=fixture();doc.semantics.coordinateSystems.push({id:'axes',dimensions:2,angle:0,origin:[500,350],visible:true});await load(page,doc);const symbol=doc.semantics.variables[0].symbol;
 await selectVector(page,symbol);await expect.poll(()=>count(page)).toBe(2);
 const components=await page.evaluate(()=>(window as any).Konva.stages[0].find('.vector-component').map((n:any)=>({axis:n.getAttr('axis'),dash:n.dash(),points:n.points()})));expect(components.map((c:any)=>c.axis)).toEqual(['x','y']);expect(components.every((c:any)=>c.dash.length)).toBe(true);
 await page.screenshot({path:`test-results/coordinate-components-${info.project.name}.png`});
 const mobile=info.project.name==='mobile';
 await gesture(page,mobile,await canvasPoint(page,300,200),await canvasPoint(page,320,300));await expect.poll(()=>count(page)).toBe(0);
 await gesture(page,mobile,await canvasPoint(page,320,300),await canvasPoint(page,300,200));await expect.poll(()=>count(page)).toBe(2);
 const before=await saved(page);
 const origin=await canvasPoint(page,500,350);await gesture(page,mobile,origin,await canvasPoint(page,540,390));const moved=await saved(page);expect(Math.abs(moved.semantics.coordinateSystems[0].origin[0]-540)).toBeLessThan(1);expect(Math.abs(moved.semantics.coordinateSystems[0].origin[1]-390)).toBeLessThan(1);expect(moved.presentation.elements).toEqual(before.presentation.elements);await expect.poll(()=>count(page)).toBe(2);
 const handle=await page.evaluate(()=>{const n=(window as any).Konva.stages[0].findOne('.coordinate-rotation-handle');return {x:n.x(),y:n.y()};});await gesture(page,mobile,await canvasPoint(page,handle.x,handle.y),await canvasPoint(page,540+105/Math.sqrt(2),390-105/Math.sqrt(2)),async()=>{await expect.poll(()=>count(page)).toBe(2);await expect.poll(()=>page.evaluate(()=>(window as any).Konva.stages[0].find('.vector-component').map((n:any)=>n.points()))).not.toEqual(components.map(c=>c.points));expect(await page.evaluate(()=>(window as any).Konva.stages[0].find('.angle-label').length)).toBe(2);});await expect.poll(()=>count(page)).toBe(0);expect((await saved(page)).presentation.elements).toEqual(before.presentation.elements);
 // Numerical rotations test the exact inclusive boundary in the actual renderer.
 for(const [angle,expected]of [[35,0],[34.9,2],[55,0],[55.1,2]] as const){await page.getByTitle('Coordinates',{exact:true}).click();await fixtureOrientation(page,Number(String(angle)));await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();await selectVector(page,symbol);await expect.poll(()=>count(page)).toBe(expected);}
 // 1D keeps only x; persisted component switch remains available when editing.
 await page.getByTitle('Coordinates',{exact:true}).click();await fixtureOrientation(page,Number('0'));await page.locator('#coordinate-dimensions').selectOption('1');await page.getByRole('button',{name:'Save coordinates'}).click();await expect(page.locator('#coordinate-dialog')).not.toBeVisible();await selectVector(page,symbol);await expect.poll(()=>count(page)).toBe(1);
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Edit ${symbol}`,exact:true}).click();await page.locator('#vector-components').uncheck();await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();await expect.poll(()=>count(page)).toBe(0);const final=await saved(page);await page.reload();await load(page,final);expect(await saved(page)).toEqual(final);expect(errors).toEqual([]);await page.screenshot({path:`test-results/coordinates-${info.project.name}.png`});
});
test('contextual dialogs expose only applicable fields and preserve valid shared drafts',async({page})=>{
 await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await expect(page.locator('#object-type')).toBeVisible();await expect(page.locator('#object-preset,#object-category')).toHaveCount(0);await expect(page.locator('#mass-enabled')).toBeVisible();await expect(page.locator('#gravity-enabled,#springConstant-enabled,#surfaceChargeDensity-enabled')).toHaveCount(0);
 await page.locator('#object-name').fill('Custom water');await page.locator('#density-enabled').check();await page.locator('#density-state').selectOption('known');await page.locator('#density-value').fill('1200');await page.locator('#object-type').selectOption('fluid');await expect(page.locator('#object-name')).toHaveValue('Custom water');await expect(page.locator('#density-value')).toHaveValue('1200');await expect(page.locator('#mass-enabled')).toHaveCount(0);expect(await page.locator('#object-representation option').evaluateAll(opts=>opts.map((o:any)=>o.value))).toEqual(['surface','none']);await expect(page.locator('#representation-hint')).toBeHidden();await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();
 const doc=await saved(page);expect(doc.semantics.variables).toHaveLength(1);expect(doc.semantics.variables[0].value).toBe(1200);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Custom water',exact:true}).click();await expect(page.locator('#density-enabled')).toBeVisible();await expect(page.locator('#mass-enabled')).toHaveCount(0);await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();expect((await saved(page)).semantics.variables).toEqual(doc.semantics.variables);
});
