import {test,expect,type Page} from './test-fixture';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft} from '../../src/objects';
import {saveVector} from '../../src/physics';
import {readFile} from 'node:fs/promises';
async function saved(page:Page){const p=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await(await p).path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'cleanup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');}
function fixture(){const s=new DocumentStore(),b=saveObject(s,{...presetDraft('ordinary'),name:'Book',properties:{mass:{state:'unknown',unit:'kg'}}}),r=saveObject(s,{...presetDraft('ordinary'),name:'Ramp'});return {s,b,r};}
async function contact(page:Page,b:string,r:string){await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption('contact');await page.locator('#vector-from').selectOption(r);await page.locator('#vector-to').selectOption(b);await page.locator('#vector-friction').selectOption('static');}
async function insert(page:Page,symbol:string){const h=page.locator('#friction-expression');await h.locator('.me-variables summary').click();await h.getByRole('button',{name:`Insert ${symbol}`,exact:true}).click();}
async function editVector(page:Page,symbol:string){await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Edit ${symbol}`,exact:true}).click();}
test('native compact Mathed controls, actual autofocus, selected autocomplete and cursor navigation',async({page},info)=>{
 const {s,b,r}=fixture();saveObject(s,presetDraft('planetSurface'));await page.goto('./');await load(page,s.document);await contact(page,b,r);await page.locator('#friction-state').selectOption('expression');const h=page.locator('#friction-expression');
 await expect(h.locator('.me-structures button')).toHaveText(['a/b','xⁿ','xₙ','( )','√']);await expect(h.locator('.me-menus > *')).toHaveCount(3);await expect(h.locator('.me-actions button')).toHaveText(['←','→','⌫']);await expect(h.locator('.expression-vocabulary')).toHaveCount(0);await expect(h.locator('.me-input')).toBeFocused();
 await page.keyboard.type('m');await expect(h.locator('.me-suggestions [aria-selected=true]')).toHaveAttribute('data-variable-id',s.document.semantics.objects.find(o=>o.id===b)!.properties!.mass);await page.keyboard.press('Space');await expect(h.locator('.me-suggestions button')).toHaveCount(0);
 await page.keyboard.type('g');const suggestions=h.locator('.me-suggestions button');await expect(suggestions).toHaveCount(2);await expect(suggestions.nth(0)).toHaveAttribute('aria-selected','true');await expect(suggestions).not.toContainText(['m/s','N*']);await page.keyboard.press('ArrowRight');await expect(suggestions.nth(1)).toHaveAttribute('aria-selected','true');await page.keyboard.press('ArrowLeft');await expect(suggestions.nth(0)).toHaveAttribute('aria-selected','true');await page.keyboard.press('Space');await page.keyboard.press('ArrowLeft');await expect(h.locator('.me-current')).toHaveAttribute('data-path','[1]');await insert(page,'N_{R,B}');
 await page.screenshot({path:info.outputPath('native-mathed.png')});await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const doc=await saved(page),f=doc.semantics.vectors.find((v:any)=>v.role==='friction'),nodes=doc.semantics.variables.find((v:any)=>v.id===f.variableId).expression.expression;expect(nodes.map((n:any)=>n.id)).toEqual([s.document.semantics.objects.find(o=>o.id===b)!.properties!.mass,doc.semantics.vectors.find((v:any)=>v.role==='normal').variableId,s.document.semantics.variables.find(v=>v.quantity==='gravity')!.id]);
});
test('static and kinetic switch rerenders an open expression without changing IDs, values or cursor',async({page})=>{
 const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);await contact(page,b,r);await expect(page.locator('#coefficient-enabled')).toHaveCount(0);await page.locator('#coefficient-state').selectOption('known');await page.locator('#coefficient-value').fill('.25');await page.locator('#friction-state').selectOption('expression');await insert(page,'\\mu_{s,R,B}');await insert(page,'N_{R,B}');const h=page.locator('#friction-expression');const path=await h.locator('.me-current').getAttribute('data-path');await page.locator('#vector-friction').selectOption('kinetic');await expect(h.locator('.me-unresolved')).toHaveCount(0);await expect(h.locator('.me-field annotation').first()).toContainText('\\mu_{k,R,B}');await expect(h.locator('.me-current')).toHaveAttribute('data-path',path!);await expect(page.locator('#coefficient-value')).toHaveValue('.25');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const kinetic=await saved(page),mu=kinetic.semantics.interactions[0].properties.kineticFriction,f=kinetic.semantics.vectors.find((v:any)=>v.role==='friction');expect(kinetic.semantics.variables.find((v:any)=>v.id===f.variableId).expression.expression[0].id).toBe(mu);await page.reload();await load(page,kinetic);await editVector(page,'N_{R,B}');await page.locator('#vector-friction').selectOption('static');await expect(h.locator('.me-unresolved')).toHaveCount(0);await expect(h.locator('.me-field annotation').first()).toContainText('\\mu_{s,R,B}');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const stat=await saved(page);expect(stat.semantics.interactions[0].properties.staticFriction).toBe(mu);expect(stat.semantics.variables.find((v:any)=>v.id===mu)).toMatchObject({quantity:'staticFriction',value:.25});expect(stat.semantics.variables.find((v:any)=>v.id===f.variableId).expression).toEqual(kinetic.semantics.variables.find((v:any)=>v.id===f.variableId).expression);
});
for(const [category,keys]of [['spring',['springConstant','extension']],['fluid',['density']],['planetSurface',['gravity']],['chargedPlate',['surfaceChargeDensity']]] as const)test(`${category} intrinsic controls and live vocabulary have no existence checkbox`,async({page})=>{
 await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-type').selectOption(category);for(const key of keys){await expect(page.locator(`#${key}-enabled`)).toHaveCount(0);await expect(page.locator(`#${key}-state`)).toBeVisible();}await page.locator(`#${keys[0]}-state`).selectOption('expression');await expect(page.locator(`#${keys[0]}-expression .me-input`)).toBeFocused();await page.locator(`#${keys[0]}-expression .me-variables summary`).click();expect(await page.locator(`#${keys[0]}-expression [data-reference-id]`).count()).toBe(keys.length+2);await page.locator(`#${keys[0]}-state`).selectOption(category==='fluid'||category==='planetSurface'?'known':'unknown');if(category==='fluid')await expect(page.locator('#density-value')).toHaveValue('1000');if(category==='planetSurface')await expect(page.locator('#gravity-value')).toHaveValue('9.8');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const doc=await saved(page);expect(Object.keys(doc.semantics.objects[0].properties)).toEqual([...keys]);await page.reload();await load(page,doc);expect(await saved(page)).toEqual(doc);
});
test('contact discovery always shows all supported options and enables existing Spring/Cable',async({page})=>{const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);await contact(page,b,r);expect(await page.locator('#vector-contact option').evaluateAll(options=>options.map((o:any)=>({value:o.value,disabled:o.disabled,hidden:o.hidden})))).toEqual([{value:'ordinary',disabled:false,hidden:false},{value:'spring',disabled:true,hidden:false},{value:'cable',disabled:true,hidden:false}]);await page.locator('#cancel-vector').click();saveObject(s,presetDraft('spring'));saveObject(s,presetDraft('cable'));await load(page,s.document);await contact(page,b,r);expect(await page.locator('#vector-contact option').evaluateAll(options=>options.map((o:any)=>o.disabled))).toEqual([false,false,false]);});
function groupFixture(){const {s,b,r}=fixture();const n=saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:r,targetId:b,friction:'static',magnitude:{state:'unknown',unit:'N'}}),mu=s.document.semantics.interactions[0].properties!.staticFriction;saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:mu}}});return {s,b,r,n};}
test('object cascade confirmation cancels safely, then deletes dependencies in one undoable action',async({page})=>{const {s}=groupFixture();await page.goto('./');await load(page,s.document);const before=await saved(page);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Delete Ramp',exact:true}).click();await expect(page.locator('#cascade-dialog')).toBeVisible();await page.locator('#cascade-dialog').getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Close',exact:true}).click();expect(await saved(page)).toEqual(before);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Delete Ramp',exact:true}).click();await page.getByRole('button',{name:'Delete all',exact:true}).click();await expect(page.getByRole('button',{name:'Select Ramp',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Close',exact:true}).click();const after=await saved(page);expect(after.semantics.objects).toHaveLength(1);expect(after.semantics.interactions).toEqual([]);expect(after.semantics.vectors).toHaveLength(1);expect(after.semantics.variables.find((v:any)=>v.ownerVectorId)).toMatchObject({state:'unknown'});await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(before);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(after);await page.reload();await load(page,after);expect(await saved(page)).toEqual(after);});
test('contact group cascade deletes all forces and coefficient and clears external expressions',async({page})=>{const {s}=groupFixture();await page.goto('./');await load(page,s.document);const before=await saved(page);await editVector(page,'N_{R,B}');await page.locator('#delete-vector').click();await expect(page.locator('#cascade-dialog')).toBeVisible();await page.getByRole('button',{name:'Delete all',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const after=await saved(page);expect(after.semantics.interactions).toEqual([]);expect(after.semantics.vectors).toHaveLength(1);expect(after.semantics.variables.filter((v:any)=>v.ownerInteractionId)).toEqual([]);expect(after.semantics.variables.find((v:any)=>v.ownerVectorId)).toMatchObject({state:'unknown'});await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(before);});
test('turning friction off confirms dependency removal and clears outside expressions on save',async({page})=>{const {s}=groupFixture();await page.goto('./');await load(page,s.document);const before=await saved(page);await editVector(page,'N_{R,B}');await page.locator('#vector-friction').selectOption('none');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#cascade-dialog')).toBeVisible();await page.locator('#cascade-dialog').getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('#cancel-vector').click();expect(await saved(page)).toEqual(before);await editVector(page,'N_{R,B}');await page.locator('#vector-friction').selectOption('none');await page.getByRole('button',{name:'Save vector',exact:true}).click();await page.getByRole('button',{name:'Delete all',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const after=await saved(page);expect(after.semantics.vectors).toHaveLength(2);expect(after.semantics.variables.find((v:any)=>v.quantity==='velocity')).toMatchObject({state:'unknown'});expect(after.semantics.variables.some((v:any)=>v.quantity==='staticFriction')).toBe(false);await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(before);});
test('removing an optional property in an open modal clears its dependent expression and confirms once',async({page})=>{
 const s=new DocumentStore(),o=saveObject(s,{...presetDraft('ordinary'),name:'Rock',properties:{charge:{state:'unknown',unit:'C'},mass:{state:'unknown',unit:'kg'}}}),charge=s.document.semantics.objects[0].properties!.charge;
 const mass=s.document.semantics.variables.find(v=>v.id===s.document.semantics.objects[0].properties!.mass)!;mass.state='expression';mass.expression={type:'reference',id:charge};await page.goto('./');await load(page,s.document);const before=await saved(page);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Rock',exact:true}).click();await page.locator('#charge-enabled').uncheck();await expect(page.locator('#mass-state')).toHaveValue('unknown');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#cascade-dialog')).toBeVisible();await page.getByRole('button',{name:'Delete all',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const after=await saved(page);expect(after.semantics.variables).toHaveLength(1);expect(after.semantics.variables[0]).toMatchObject({id:mass.id,state:'unknown'});await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(before);
});
