import {test,expect} from './test-fixture';
import {readFile} from 'node:fs/promises';
async function saved(page:any){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();const file=await pending;return JSON.parse(await readFile((await file.path())!,'utf8'));}
test('student authors weight expression and renamed symbols preserve structured references',async({page})=>{
 await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-type').selectOption('planetSurface');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Book');await page.locator('#mass-enabled').check();await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const before=await saved(page),book=before.semantics.objects[1];
 await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption('gravitational');await page.locator('#vector-from').selectOption(before.semantics.objects[0].id);await page.locator('#vector-to').selectOption(book.id);await page.locator('#vector-state').selectOption('expression');const host=page.locator('#vector-expression');await host.getByLabel('Variables',{exact:true}).click();await host.getByRole('button',{name:'Insert m_{B}',exact:true}).click();await host.getByLabel('Variables',{exact:true}).click();await host.getByRole('button',{name:'Insert g',exact:true}).click();await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const doc=await saved(page),vector=doc.semantics.vectors[0],magnitude=doc.semantics.variables.find((v:any)=>v.id===vector.variableId);expect(magnitude.state).toBe('expression');expect(magnitude.expression.expression[0]).toEqual({type:'variable',id:book.properties.mass});
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Book',exact:true}).click();await page.locator('#object-name').fill('Novel');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const changed=await saved(page);expect(changed.semantics.variables.find((v:any)=>v.id===vector.variableId).expression).toEqual(magnitude.expression);
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Edit ${changed.semantics.variables.find((v:any)=>v.id===vector.variableId).symbol}`,exact:true}).click();await expect(page.locator('#vector-expression .me-field')).toContainText('N');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.reload();await page.locator('#file-input').setInputFiles({name:'expression.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(changed))});await expect(page.locator('#status')).toContainText('Opened');expect(await saved(page)).toEqual(changed);
});
