import {test,expect,type Page} from './test-fixture';
import {readFile} from 'node:fs/promises';
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();const file=await pending;return JSON.parse(await readFile((await file.path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');}
for(const key of ['A','B','C','D','E','F'])test(`required scenario ${key} renders, edits and round trips without losing identities`,async({page},info)=>{
 const doc=JSON.parse(await readFile(`examples/scenario-${key}.diagramed.json`,'utf8'));const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('./');await load(page,doc);expect(await saved(page)).toEqual(doc);
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();for(const vector of doc.semantics.vectors){const symbol=doc.semantics.variables.find((v:any)=>v.id===vector.variableId).symbol;await expect(page.getByRole('button',{name:`Edit ${symbol}`,exact:true})).toBeVisible();}await page.getByRole('button',{name:'Close',exact:true}).click();
 const target=doc.semantics.objects.find((o:any)=>o.category==='ordinary')!;await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:`Edit ${target.name}`,exact:true}).click();await page.locator('#object-name').fill(target.name+' renamed');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const changed=await saved(page);expect(changed.semantics.objects.map((o:any)=>o.id)).toEqual(doc.semantics.objects.map((o:any)=>o.id));expect(changed.semantics.vectors.map((v:any)=>v.id)).toEqual(doc.semantics.vectors.map((v:any)=>v.id));expect(changed.semantics.variables.map((v:any)=>v.id).sort()).toEqual(doc.semantics.variables.map((v:any)=>v.id).sort());await page.reload();await load(page,changed);expect(await saved(page)).toEqual(changed);expect(errors).toEqual([]);await page.screenshot({path:`test-results/scenario-${key}-${info.project.name}.png`});
});
test('missing endpoints, orphan quantities and malformed expressions preserve open document',async({page})=>{
 const doc=JSON.parse(await readFile('examples/scenario-B.diagramed.json','utf8'));await page.goto('./');await load(page,doc);
 const candidates=[];const endpoint=structuredClone(doc);endpoint.semantics.vectors.find((v:any)=>v.kind==='separation').toId='missing';candidates.push(endpoint);const orphan=structuredClone(doc);orphan.semantics.variables.push({id:'orphan',symbol:'X',quantity:'force',state:'unknown',unit:'N',ownerVectorId:'missing'});candidates.push(orphan);const expression=structuredClone(doc);expression.semantics.variables.find((v:any)=>v.state==='expression').expression={type:'javascript',code:'alert(1)'};candidates.push(expression);const interaction=structuredClone(doc);interaction.semantics.interactions[0].targetId='missing';candidates.push(interaction);
 for(const candidate of candidates){await page.locator('#file-input').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(candidate))});await expect(page.locator('#status')).toContainText('Cannot open diagram');expect(await saved(page)).toEqual(doc);}
});
test('field, spring, cable and buoyancy workflows expose eligible ingredients without equation templates',async({page})=>{
 for(const [key,kind,interactionType,contactType]of [['C','field','electric','ordinary'],['E','force','contact','spring'],['E','force','contact','cable'],['F','force','buoyant','ordinary']]){
  const doc=JSON.parse(await readFile(`examples/scenario-${key}.diagramed.json`,'utf8'));await page.goto('./');await load(page,doc);await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption(kind);await page.locator('#vector-interaction').selectOption(interactionType);if(interactionType==='contact')await page.locator('#vector-contact').selectOption(contactType);
  const source=doc.semantics.objects.find((o:any)=>key==='C'?o.category==='chargedPlate':key==='F'?o.category==='fluid':o.category===contactType),target=doc.semantics.objects.find((o:any)=>key==='C'?o.category==='spatialPoint':o.category==='ordinary');await page.locator('#vector-from').selectOption(source.id);await page.locator('#vector-to').selectOption(target.id);await page.locator('#vector-state').selectOption('expression');await expect(page.locator('#vector-expression .expression-preview')).toHaveText('');await expect(page.locator('#vector-expression button[data-reference-id]')).toHaveCount(contactType==='cable'?0:interactionType==='buoyant'?3:2);await page.locator('#vector-state').selectOption('unknown');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const result=await saved(page);expect(result.semantics.vectors.length).toBe(doc.semantics.vectors.length+1);await page.reload();await load(page,result);expect(await saved(page)).toEqual(result);
 }
});
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number}){if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/6,y:start.y+(end.y-start.y)*i/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:6});await page.mouse.up();}}
test('specialized surface and endpoint gestures preserve physical quantities',async({page},info)=>{
 for(const key of ['A','F']){const doc=JSON.parse(await readFile(`examples/scenario-${key}.diagramed.json`,'utf8'));await page.goto('./');await load(page,doc);const surface=doc.presentation.elements.find((e:any)=>e.kind==='surface'&&e.visible),box=(await page.locator('.konvajs-content').boundingBox())!,scale=box.width/doc.presentation.canvas.width;await gesture(page,info.project.name==='mobile',{x:box.x+650*scale,y:box.y+surface.y*scale},{x:box.x+650*scale,y:box.y+(surface.y-40)*scale});const moved=await saved(page);expect(moved.presentation.elements.find((e:any)=>e.id===surface.id).y).not.toBe(surface.y);expect(moved.semantics).toEqual(doc.semantics);await page.reload();await load(page,moved);expect(await saved(page)).toEqual(moved);}
 const doc=JSON.parse(await readFile('examples/scenario-E.diagramed.json','utf8'));await page.goto('./');await load(page,doc);const box=(await page.locator('.konvajs-content').boundingBox())!,scale=box.width/doc.presentation.canvas.width;
 for(const kind of ['spring','cable']){const g=doc.presentation.elements.find((e:any)=>e.kind===kind);await page.mouse.click(box.x+g.x*scale,box.y+g.y*scale);const start={x:box.x+(g.x+g.points[0])*scale,y:box.y+(g.y+g.points[1])*scale};await gesture(page,info.project.name==='mobile',start,{x:start.x-40*scale,y:start.y+40*scale});expect((await saved(page)).presentation.elements.find((e:any)=>e.id===g.id).points).not.toEqual(g.points);}
 expect((await saved(page)).semantics).toEqual(doc.semantics);
});
