import {test,expect,type Page} from './test-fixture';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft} from '../../src/objects';
import {saveVector,vectorGraphic} from '../../src/physics';
import {readFile} from 'node:fs/promises';
import {canvasPoint} from './view-helpers';
async function saved(page:Page){const p=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await(await p).path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'mathed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');}
function fixture(){const s=new DocumentStore(),b=saveObject(s,{...presetDraft('ordinary'),name:'Book',properties:{mass:{state:'unknown',unit:'kg'}}}),r=saveObject(s,{...presetDraft('ordinary'),name:'Ramp'});return {s,b,r};}
async function contact(page:Page,b:string,r:string){await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption('contact');await page.locator('#vector-from').selectOption(r);await page.locator('#vector-to').selectOption(b);await page.locator('#vector-friction').selectOption('static');}
async function insert(page:Page,host:string,symbol:string){const h=page.locator(host);await h.locator('.me-variables summary').click();await h.getByRole('button',{name:`Insert ${symbol}`,exact:true}).click();}
test('live static and kinetic coefficients, compact workflow, cancel, full vocabulary and persistent expression labels',async({page},info)=>{
 const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);const before=await saved(page);await contact(page,b,r);
 expect(await page.locator('#vector-interaction option').evaluateAll(opts=>opts.map((o:any)=>({value:o.value,hidden:o.hidden,disabled:o.disabled})))).toEqual([{value:'gravitational',hidden:false,disabled:true},{value:'electric',hidden:false,disabled:true},{value:'contact',hidden:false,disabled:false},{value:'buoyant',hidden:false,disabled:true}]);await expect(page.locator('#friction-variables')).toContainText('μ');await expect(page.locator('#coefficient-enabled')).toHaveCount(0);await expect(page.locator('#coefficient-unit')).toBeHidden();await expect(page.locator('#friction-state')).toHaveAccessibleName('Define friction');await page.locator('#friction-state').selectOption('expression');
 const host=page.locator('#friction-expression');await expect(host.locator('.mathed-editor')).toBeVisible();await expect(page.locator('.expression-palette')).toHaveCount(0);await expect(host.locator('.me-variable-menu')).toBeHidden();
 await host.locator('.me-variables summary').click();const mu=host.getByRole('button',{name:'Insert \\mu_{s,R,B}',exact:true});await expect(mu).toBeVisible();const muId=await mu.getAttribute('data-reference-id');await mu.click();
 await insert(page,'#friction-expression','N_{R,B}');await page.screenshot({path:`test-results/friction-modal-${info.project.name}.png`});await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();
 const doc=await saved(page),i=doc.semantics.interactions[0],f=doc.semantics.vectors.find((v:any)=>v.role==='friction'),fv=doc.semantics.variables.find((v:any)=>v.id===f.variableId);
 expect(i.properties.staticFriction).toBe(muId);expect(doc.semantics.variables.find((v:any)=>v.id===muId)).toMatchObject({state:'unknown',unit:'1'});expect(fv.expression).toEqual({type:'mathed',expression:[{type:'variable',id:muId},{type:'variable',id:doc.semantics.vectors.find((v:any)=>v.role==='normal').variableId}]});
 await expect.poll(()=>page.evaluate(()=>(window as any).Konva.stages[0].find('.semantic-label').map((n:any)=>n.findOne('Image')?.getAttr('math')).join(' '))).toContain('\\mu_{s,R,B}');
 await page.screenshot({path:`test-results/friction-expression-${info.project.name}.png`});
 await page.getByRole('button',{name:'Zoom out',exact:true}).click();await page.getByRole('button',{name:'Zoom out',exact:true}).click();const fg=doc.presentation.elements.find((g:any)=>g.vectorId===f.id),p=await page.evaluate(id=>{const s=(window as any).Konva.stages[0],n=s.find('.semantic-label').find((n:any)=>n.getAttr('graphicId')===id),r=n.getClientRect(),c=s.container().getBoundingClientRect();return {x:c.left+r.x+r.width/2,y:c.top+r.y+r.height/2,scale:s.scaleX()};},fg.id);
 await gesture(page,info.project.name==='mobile',{x:p.x,y:p.y},{x:p.x-40*p.scale,y:p.y+30*p.scale});const moved=await saved(page);expect(moved.semantics).toEqual(doc.semantics);expect(moved.presentation.elements.find((g:any)=>g.id===fg.id).label.offsetX).toBeCloseTo(fg.label.offsetX-40);await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(doc);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(moved);await page.reload();await load(page,moved);expect(await saved(page)).toEqual(moved);
 await load(page,before);await contact(page,b,r);await page.locator('#vector-friction').selectOption('kinetic');await page.locator('#friction-state').selectOption('expression');await insert(page,'#friction-expression','\\mu_{k,R,B}');await page.locator('#cancel-vector').click();expect(await saved(page)).toEqual(before);
 await contact(page,b,r);await page.locator('#coefficient-state').selectOption('known');await page.locator('#coefficient-value').fill('.3');await expect(page.locator('#coefficient-unit')).toBeHidden();await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const known=await saved(page);expect(known.semantics.variables.find((v:any)=>v.quantity==='staticFriction')).toMatchObject({state:'known',value:.3,unit:'1'});
});
test('dropdown inserts at the retained middle/nested cursor and autocomplete uses the same IDs',async({page})=>{
 const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);await contact(page,b,r);await page.locator('#friction-state').selectOption('expression');
 await insert(page,'#friction-expression','N_{R,B}');await insert(page,'#friction-expression','m_{B}');const input=page.locator('#friction-expression .me-input');await input.press('ArrowLeft');await insert(page,'#friction-expression','\\mu_{s,R,B}');
 await input.press('End');await input.pressSequentially('mu');await expect(page.locator('#friction-expression .me-suggestions button')).toHaveCount(1);const suggestion=page.locator('#friction-expression .me-suggestions button'),muId=await suggestion.getAttribute('data-variable-id');await suggestion.click();
 await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const doc=await saved(page),v=doc.semantics.variables.find((v:any)=>v.ownerVectorId===doc.semantics.vectors.find((v:any)=>v.role==='friction').id);expect(v.expression.expression.map((n:any)=>n.id)).toEqual([doc.semantics.vectors.find((v:any)=>v.role==='normal').variableId,muId,doc.semantics.objects.find((o:any)=>o.id===b).properties.mass,muId]);
});
test('object expressions share Mathed and same-modal unknown property IDs',async({page})=>{
 await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Rock');await page.locator('#mass-enabled').check();await page.locator('#charge-enabled').check();await page.locator('#mass-state').selectOption('expression');await insert(page,'#mass-expression','q_{R}');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const doc=await saved(page),o=doc.semantics.objects[0];expect(doc.semantics.variables.find((v:any)=>v.id===o.properties.mass).expression.expression).toEqual([{type:'variable',id:o.properties.charge}]);await page.reload();await load(page,doc);expect(await saved(page)).toEqual(doc);
});
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number}){if(mobile){const c=await page.context().newCDPSession(page);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=10;i++)await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/10,y:start.y+(end.y-start.y)*i/10}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:10});await page.mouse.up();}}
for(const kind of ['velocity','acceleration','displacement'] as const)test(`${kind} position is presentation only with zoom, pan, history and reload`,async({page},info)=>{
 const {s,b,r}=fixture(),v=saveVector(s,{kind,targetId:b,magnitude:{state:'unknown',unit:kind==='velocity'?'m/s':kind==='acceleration'?'m/s^2':'m'},angle:-45,length:100}),g=vectorGraphic(s.document,v)!;await page.goto('./');await load(page,s.document);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Select ${s.document.semantics.variables.find(m=>m.ownerVectorId===v)!.symbol}`,exact:true}).click();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.locator('#main-canvas').evaluate(e=>{e.scrollLeft+=20;e.scrollTop+=20;});
 await gesture(page,info.project.name==='mobile',await canvasPoint(page,g.x+35,g.y-35),await canvasPoint(page,g.x+95,g.y+5));const moved=await saved(page),mg=moved.presentation.elements.find((e:any)=>e.id===g.id);expect(mg.x).toBe(g.x+60);expect(mg.y).toBe(g.y+40);expect(mg.points).toEqual(g.points);expect(moved.semantics).toEqual(s.document.semantics);
 await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(s.document);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(moved);await page.reload();await load(page,moved);expect(await saved(page)).toEqual(moved);
});
test('vocabulary insertion preserves a nested fraction slot on mouse and touch',async({page})=>{
 const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);await contact(page,b,r);await page.locator('#friction-state').selectOption('expression');const h=page.locator('#friction-expression');await h.getByRole('button',{name:'Fraction',exact:true}).click();await insert(page,'#friction-expression','\\mu_{s,R,B}');await h.locator('.me-input').press('Tab');await insert(page,'#friction-expression','N_{R,B}');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const doc=await saved(page),f=doc.semantics.vectors.find((v:any)=>v.role==='friction'),e=doc.semantics.variables.find((v:any)=>v.id===f.variableId).expression.expression[0];expect(e.type).toBe('fraction');expect(e.numerator[0].id).toBe(doc.semantics.interactions[0].properties.staticFriction);expect(e.denominator[0].id).toBe(doc.semantics.vectors.find((v:any)=>v.role==='normal').variableId);
});
test('incomplete or unrecognized expressions retain visible validation and never invent variable IDs',async({page})=>{
 const {s,b,r}=fixture();await page.goto('./');await load(page,s.document);const before=await saved(page);await contact(page,b,r);await page.locator('#friction-state').selectOption('expression');await page.locator('#friction-expression .me-input').pressSequentially('invented ');await expect(page.locator('#friction-expression .me-status')).toContainText('Unrecognized');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-error')).toContainText('Complete the Mathed expression');await expect(page.locator('#vector-dialog')).toBeVisible();await page.locator('#cancel-vector').click();expect(await saved(page)).toEqual(before);
});
test('static/kinetic switch preserves external references and cancellation',async({page})=>{
 const {s,b,r}=fixture();saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:r,targetId:b,friction:'static',magnitude:{state:'unknown',unit:'N'}});const mu=s.document.semantics.interactions[0].properties!.staticFriction;saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:mu}}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await load(page,s.document);await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:'Edit N_{R,B}',exact:true}).click();await page.locator('#vector-friction').selectOption('kinetic');await expect(page.locator('#vector-error')).toBeEmpty();await expect(page.locator('#save-vector')).toBeEnabled();await page.locator('#cancel-vector').click();expect(await saved(page)).toEqual(s.document);expect(errors).toEqual([]);
});
