import {test,expect,type Page} from './test-fixture';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft} from '../../src/objects';
import {saveVector} from '../../src/physics';
import {readFile} from 'node:fs/promises';
async function saved(page:Page){const p=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await(await p).path())!,'utf8'));}
async function load(page:Page,doc:any){await page.locator('#file-input').setInputFiles({name:'values.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');}
async function math(page:Page){return page.evaluate(()=>(window as any).Konva.stages[0].find('.semantic-label').map((n:any)=>n.findOne('Image')?.getAttr('math')).filter(Boolean));}
test('known object mass, defaults and existing physical properties render with values and units',async({page},info)=>{
 const s=new DocumentStore(),rock=saveObject(s,{...presetDraft('ordinary'),name:'Rock',properties:{mass:{state:'known',value:5,unit:'kg'},charge:{state:'known',value:-3,unit:'nC'}}});saveObject(s,presetDraft('planetSurface'));saveObject(s,presetDraft('fluid'));saveObject(s,{...presetDraft('spring'),properties:{springConstant:{state:'known',value:200,unit:'N/m'},extension:{state:'unknown',unit:'m'}}});await page.goto('./');await load(page,s.document);
 expect(await math(page)).toEqual(expect.arrayContaining(['m_{R}=5\\,\\mathrm{kg},\\; q_{R}=-3\\,\\mathrm{nC}','g=9.8\\,\\mathrm{m}/\\mathrm{s}^{2}','\\rho_{W}=1000\\,\\mathrm{kg}/\\mathrm{m}^{3}','k=200\\,\\mathrm{N}/\\mathrm{m},\\; \\Delta x']));
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Rock',exact:true}).click();await page.locator('#mass-value').fill('250');await page.locator('#mass-unit').selectOption('g');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();expect(await math(page)).toContain('m_{R}=250\\,\\mathrm{g},\\; q_{R}=-3\\,\\mathrm{nC}');const changed=await saved(page);expect(changed.semantics.objects.find((o:any)=>o.id===rock).properties.mass).toBe(s.document.semantics.objects[0].properties!.mass);await page.reload();await load(page,changed);expect(await saved(page)).toEqual(changed);expect(await math(page)).toContain('m_{R}=250\\,\\mathrm{g},\\; q_{R}=-3\\,\\mathrm{nC}');
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Objects',exact:true}).click();await page.getByRole('button',{name:'Edit Rock',exact:true}).click();await page.locator('#mass-state').selectOption('unknown');await page.getByRole('button',{name:'Save object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();expect(await math(page)).toContain('m_{R},\\; q_{R}=-3\\,\\mathrm{nC}');await page.screenshot({path:`test-results/numerical-labels-${info.project.name}.png`});
});
test('vector numerical magnitudes show stored definitions without deriving component magnitudes',async({page})=>{
 const s=new DocumentStore(),book=saveObject(s,{...presetDraft('ordinary'),name:'Book'}),v=saveVector(s,{kind:'velocity',targetId:book,magnitude:{state:'known',value:4,unit:'m/s'},angle:-35}),symbol=s.document.semantics.variables[0].symbol;await page.goto('./');await load(page,s.document);expect(await math(page)).toContain('\\vec{v}_{B}=4\\,\\mathrm{m}/\\mathrm{s}');
 await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Edit ${symbol}`,exact:true}).click();await page.locator('#vector-state').selectOption('unknown');await page.locator('#save-vector').click();await expect(page.locator('#vector-dialog')).not.toBeVisible();expect(await math(page)).toContain('\\vec{v}_{B}');expect((await saved(page)).semantics.vectors[0].id).toBe(v);
});
