import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function save(page:Page){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();const file=await pending;return JSON.parse(await readFile((await file.path())!,'utf8'));}
async function gesture(page:Page,mobile:boolean,start:{x:number;y:number},end:{x:number;y:number}){if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:8});await page.mouse.up();}}
async function rendered(page:Page){return page.evaluate(()=>{const stage=(window as any).Konva.stages[0];return {labels:stage.find('.semantic-label').map((g:any)=>({id:g.getAttr('graphicId'),x:g.x(),y:g.y(),bounds:g.getClientRect({skipTransform:true}),absolute:g.getClientRect(),rotation:g.rotation(),children:g.getChildren().map((c:any)=>({type:c.getClassName(),text:c.getAttr('text'),math:c.getAttr('math'),x:c.x(),y:c.y()}))})),origins:stage.find('.shared-origin').map((n:any)=>({x:n.x(),y:n.y(),listening:n.listening(),fill:n.fill()})),nodes:stage.find('Arrow').map((n:any)=>({id:n.id(),x:n.x(),y:n.y(),points:n.points()})),scale:stage.scaleX()};});}
async function dragLabel(page:Page,mobile:boolean,id:string,dx:number,dy:number){const view=await rendered(page),label=view.labels.find((l:any)=>l.id===id)!,box=(await page.locator('.konvajs-content').boundingBox())!;const p={x:box.x+label.absolute.x+label.absolute.width/2,y:box.y+label.absolute.y+label.absolute.height/2};await gesture(page,mobile,p,{x:p.x+dx*view.scale,y:p.y+dy*view.scale});}
async function selectVector(page:Page,symbol:string){await page.getByTitle('Vectors',{exact:true}).click();await page.getByRole('button',{name:`Select ${symbol}`,exact:true}).click();}
async function dragTip(page:Page,mobile:boolean,id:string,dx:number,dy:number){const view=await rendered(page),n=view.nodes.find((n:any)=>n.id===id)!,box=(await page.locator('.konvajs-content').boundingBox())!;const start={x:box.x+(n.x+n.points[2])*view.scale,y:box.y+(n.y+n.points[3])*view.scale};await gesture(page,mobile,start,{x:box.x+(n.x+dx)*view.scale,y:box.y+(n.y+dy)*view.scale});}
async function noDrawingFields(page:Page){await expect(page.locator('#vector-dialog')).toBeVisible();await expect(page.locator('#vector-dialog input[id$="-symbol"],#vector-angle,#vector-length,#friction-length')).toHaveCount(0);await expect(page.locator('#vector-dialog')).not.toContainText(/LaTeX|Graphical direction|Graphical length/i);}
// Run the actual authoring and manipulation scenario on both desktop and touch emulation.
test('Contract 3.1 Book Table Planet notation, labels, inclined geometry and reopen',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const mobile=info.project.name==='mobile';await page.goto('./');
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-preset').selectOption('planetSurface');await page.locator('#object-representation').selectOption('surface');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Table');await page.locator('#object-representation').selectOption('rectangle');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();let doc=await save(page);let table=doc.presentation.elements[1],box=(await page.locator('.konvajs-content').boundingBox())!,scale=box.width/doc.presentation.canvas.width;
 await gesture(page,mobile,{x:box.x+(table.x+5)*scale,y:box.y+(table.y+table.height/2)*scale},{x:box.x+(table.x+5)*scale,y:box.y+(table.y+table.height/2+100)*scale});
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Book');await page.locator('#mass-enabled').check();await expect(page.locator('#mass-preview .katex')).toBeVisible();await expect(page.locator('#object-dialog')).not.toContainText('LaTeX');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();doc=await save(page);const planet=doc.semantics.objects[0],tableObject=doc.semantics.objects[1],book=doc.semantics.objects[2],bookGraphic=doc.presentation.elements[2],mass=book.properties.mass;expect(doc.semantics.variables.find((v:any)=>v.id===mass)).toMatchObject({symbol:'m_{B}',state:'unknown',generatedSymbol:true});
 let view=await rendered(page),label=view.labels.find((l:any)=>l.id===bookGraphic.id)!;expect(label.children.find((c:any)=>c.type==='Text').text).toBe('Book, ');expect(label.children.find((c:any)=>c.type==='Image').math).toBe('m_{B}');expect(label.x+label.bounds.width/2).toBeCloseTo(bookGraphic.x);expect(label.children.every((c:any)=>c.y<10)).toBe(true);await dragLabel(page,mobile,bookGraphic.id,-70,45);const movedLabel=(await save(page)).presentation.elements[2].label;expect(Math.abs(movedLabel.offsetX)).toBeGreaterThan(40);
 for(const kind of ['gravitational','contact']){await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption(kind);await page.locator('#vector-from').selectOption(kind==='gravitational'?planet.id:tableObject.id);await page.locator('#vector-to').selectOption(book.id);await noDrawingFields(page);if(kind==='gravitational'){await page.locator('#vector-state').selectOption('expression');const expression=page.locator('#vector-expression');await expression.getByRole('button',{name:'Insert m_{B}',exact:true}).click();await expression.getByRole('button',{name:'*',exact:true}).click();await expression.getByRole('button',{name:'Insert g',exact:true}).click();}await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();}
 doc=await save(page);const contact=doc.semantics.vectors.find((v:any)=>doc.semantics.interactions.find((i:any)=>i.id===v.interactionId)?.kind==='contact'),weight=doc.semantics.vectors.find((v:any)=>v.id!==contact.id);const weightSymbol=doc.semantics.variables.find((v:any)=>v.id===weight.variableId).symbol;expect(weightSymbol).toBe('W_{P,B}');await selectVector(page,weightSymbol);await dragTip(page,mobile,doc.presentation.elements.find((g:any)=>g.vectorId===weight.id).id,0,120);
 await page.getByTitle('Vectors',{exact:true}).click();await page.getByRole('button',{name:'Edit F_{T,B}',exact:true}).click();await noDrawingFields(page);await page.locator('#vector-friction').selectOption('static');await page.locator('#coefficient-enabled').check();await page.locator('#resultant-visible').check();await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();doc=await save(page);const normal=doc.semantics.vectors.find((v:any)=>v.role==='normal'),friction=doc.semantics.vectors.find((v:any)=>v.role==='friction'),resultant=doc.semantics.vectors.find((v:any)=>v.role==='resultant');for(const [v,sym]of [[normal,'N_{T,B}'],[friction,'f_{T,B}'],[resultant,'F_{T,B}']])expect(doc.semantics.variables.find((m:any)=>m.id===v.variableId).symbol).toBe(sym);
 const ng=doc.presentation.elements.find((g:any)=>g.vectorId===normal.id),fg=doc.presentation.elements.find((g:any)=>g.vectorId===friction.id),rg=doc.presentation.elements.find((g:any)=>g.vectorId===resultant.id);await selectVector(page,'N_{T,B}');await dragTip(page,mobile,ng.id,80,-120);await selectVector(page,'f_{T,B}');await dragTip(page,mobile,fg.id,120,80);view=await rendered(page);const n=view.nodes.find((n:any)=>n.id===ng.id)!,f=view.nodes.find((n:any)=>n.id===fg.id)!,r=view.nodes.find((n:any)=>n.id===rg.id)!;expect(n.points[2]*f.points[2]+n.points[3]*f.points[3]).toBeCloseTo(0);expect(Math.hypot(f.points[2],f.points[3])).toBeGreaterThan(100);expect(r.points[2]).toBeCloseTo(n.points[2]+f.points[2]);expect(r.points[3]).toBeCloseTo(n.points[3]+f.points[3]);expect(view.origins).toContainEqual({x:bookGraphic.x,y:bookGraphic.y,listening:false,fill:'#000'});const tipLabel=view.labels.find((l:any)=>l.id===ng.id)!;expect(Math.hypot(tipLabel.x-(n.x+n.points[2]),tipLabel.y-(n.y+n.points[3]))).toBeLessThan(70);expect(tipLabel.rotation).toBe(0);
 await dragLabel(page,mobile,ng.id,50,-35);const vectorLabel=(await save(page)).presentation.elements.find((g:any)=>g.id===ng.id).label;expect(Math.abs(vectorLabel.offsetX)).toBeGreaterThan(25);await selectVector(page,'N_{T,B}');await dragTip(page,mobile,ng.id,100,-80);expect((await save(page)).presentation.elements.find((g:any)=>g.id===ng.id).label).toEqual(vectorLabel);
 // Rotate the table directly using its existing canvas transform handle.
 await page.getByTitle('Objects',{exact:true}).click();await page.getByRole('button',{name:'Select Table',exact:true}).click();const handle=await page.evaluate(()=>{const s=(window as any).Konva.stages[0],h=s.findOne('.rotater');return h?.getClientRect();});expect(handle).toBeTruthy();box=(await page.locator('.konvajs-content').boundingBox())!;const hp={x:box.x+handle.x+handle.width/2,y:box.y+handle.y+handle.height/2};await gesture(page,mobile,hp,{x:hp.x+35*scale,y:hp.y+15*scale});expect(Math.abs((await save(page)).presentation.elements[1].rotation)).toBeGreaterThan(1);
 await page.getByTitle('Objects',{exact:true}).click();await page.getByRole('button',{name:'Select Book',exact:true}).click();await gesture(page,mobile,{x:box.x+(bookGraphic.x-bookGraphic.radius)*scale,y:box.y+bookGraphic.y*scale},{x:box.x+(bookGraphic.x-bookGraphic.radius-40)*scale,y:box.y+(bookGraphic.y+60)*scale});const inclined=await save(page);expect(inclined.presentation.elements[2].y).not.toBe(bookGraphic.y);expect(inclined.semantics.variables.find((v:any)=>v.id===mass).state).toBe('unknown');const authoredExpression=structuredClone(inclined.semantics.variables.find((v:any)=>v.id===weight.variableId).expression);
 // Introduce a B conflict after physical and mathematical references exist.
 const ids=(await save(page)).semantics.vectors.map((v:any)=>[v.id,v.variableId,v.interactionId]);await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Ball');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();doc=await save(page);expect(doc.semantics.variables.find((v:any)=>v.id===mass).symbol).toBe('m_{Bo}');expect(doc.semantics.variables.find((v:any)=>v.id===weight.variableId).expression).toEqual(authoredExpression);expect(doc.semantics.vectors.map((v:any)=>[v.id,v.variableId,v.interactionId])).toEqual(ids);expect(doc.presentation.elements[2].label).toEqual(movedLabel);expect(doc.presentation.elements.find((g:any)=>g.id===ng.id).label).toEqual(vectorLabel);
 await page.reload();await page.locator('#file-input').setInputFiles({name:'refined.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');expect(await save(page)).toEqual(doc);await page.getByTitle('Vectors',{exact:true}).click();const currentSymbol=doc.semantics.variables.find((v:any)=>v.id===normal.variableId).symbol;await page.getByRole('button',{name:`Edit ${currentSymbol}`,exact:true}).click();await noDrawingFields(page);await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const edited=await save(page);expect(edited.presentation.elements.filter((g:any)=>g.vectorId).map((g:any)=>g.points)).toEqual(doc.presentation.elements.filter((g:any)=>g.vectorId).map((g:any)=>g.points));expect(errors).toEqual([]);await page.screenshot({path:`test-results/contract31-${info.project.name}.png`});
});
test('every vector dialog is free of markup and drawing controls, including imported custom notation',async({page})=>{for(const key of ['C','D','E','F']){const doc=JSON.parse(await readFile(`examples/scenario-${key}.diagramed.json`,'utf8'));await page.goto('./');await page.locator('#file-input').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');for(const v of doc.semantics.vectors){await page.getByTitle('Vectors',{exact:true}).click();await page.getByRole('button',{name:`Edit ${doc.semantics.variables.find((m:any)=>m.id===v.variableId).symbol}`,exact:true}).click();await noDrawingFields(page);await page.getByRole('button',{name:'Cancel',exact:true}).click();}}});
