import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function saved(page:any){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();const file=await pending;return JSON.parse(await readFile((await file.path())!,'utf8'));}
test('weight, motion and linked contact configuration persist through browser save and reopen',async({page})=>{
 await page.goto('./');await expect(page.getByTitle('Vector',{exact:true})).toBeDisabled();
 for(const name of ['Book','Table']){await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill(name);await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();}
 await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-preset').selectOption('planetSurface');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();const objects=(await saved(page)).semantics.objects;
 await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption('gravitational');await page.locator('#vector-from').selectOption(objects[2].id);await page.locator('#vector-to').selectOption(objects[0].id);await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();
 await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('force');await page.locator('#vector-interaction').selectOption('contact');await page.locator('#vector-from').selectOption(objects[1].id);await page.locator('#vector-to').selectOption(objects[0].id);await page.locator('#vector-friction').selectOption('static');await page.locator('#coefficient-enabled').check();await page.locator('#resultant-visible').check();await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();
 await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption('velocity');await page.locator('#vector-to').selectOption(objects[0].id);await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();
 const doc=await saved(page);expect(doc.semantics.vectors).toHaveLength(5);expect(doc.semantics.variables.some((v:any)=>v.symbol.startsWith('W_'))).toBe(true);expect(doc.semantics.vectors.filter((v:any)=>v.role)).toHaveLength(3);await page.reload();await page.locator('#file-input').setInputFiles({name:'vectors.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.locator('#status')).toContainText('Opened');expect(await saved(page)).toEqual(doc);
});
