import {canvasView} from './view-helpers';
import {test,expect,type Page} from './test-fixture';
import {readFile} from 'node:fs/promises';
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByTitle('Download JSON').click();return JSON.parse(await readFile((await (await pending).path())!,'utf8'));}
async function edit(page:Page,symbol:string){await page.locator('#elements-menu summary').click();await page.getByRole('button',{name:'Vectors',exact:true}).click();await page.getByRole('button',{name:`Edit ${symbol}`,exact:true}).click();}
async function view(page:Page,id:string){return page.evaluate(id=>{const stage=(window as any).Konva.stages[0],label=stage.find('.semantic-label').find((n:any)=>n.getAttr('graphicId')===id);return {arrows:stage.find('Arrow').filter((n:any)=>n.id()===id).length,math:label?.findOne('Image')?.getAttr('math'),x:label?.x(),y:label?.y(),components:stage.find('.vector-component').length};},id);}
for(const [kind,unit]of [['acceleration','m/s^2'],['velocity','km/h'],['displacement','cm']] as const)test(`${kind} known zero labels, movement, editing, persistence and history`,async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await page.getByTitle('Object',{exact:true}).click();await page.locator('#object-name').fill('Rock');await page.getByRole('button',{name:'Create object',exact:true}).click();await expect(page.locator('#object-dialog')).not.toBeVisible();await page.getByTitle('Vector',{exact:true}).click();await page.locator('#vector-kind').selectOption(kind);await page.locator('#vector-state').selectOption('known');await page.locator('#vector-value').fill('0');await page.locator('#vector-unit').selectOption(unit);await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const zero=await saved(page),v=zero.semantics.vectors[0],m=zero.semantics.variables[0],g=zero.presentation.elements.find((e:any)=>e.vectorId===v.id);expect(g).toMatchObject({kind:'text',points:[0,0,0,0],visible:true});await expect.poll(async()=>(await view(page,g.id)).math).toBe(`${m.symbol}=0\\,\\mathrm{${unit}}`);expect((await view(page,g.id)).arrows).toBe(0);expect((await view(page,g.id)).components).toBe(0);
 await page.reload();await page.locator('#file-input').setInputFiles({name:'zero.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(zero))});await expect(page.locator('#status')).toContainText('Opened');expect(await saved(page)).toEqual(zero);const first=await view(page,g.id),object=zero.presentation.elements[0],box=(await page.locator('.konvajs-content').boundingBox())!,cam=await canvasView(page),scale=cam.scale,start={x:cam.x+object.x*scale,y:cam.y+(object.y+18)*scale};if(info.project.name==='mobile'){const c=await page.context().newCDPSession(page);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=8;i++)await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+i*5*scale,y:start.y+i*5*scale}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x+40*scale,start.y+40*scale,{steps:8});await page.mouse.up();}await expect.poll(async()=>(await view(page,g.id)).x).not.toBe(first.x);const moved=await saved(page);await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(zero);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(moved);
 await edit(page,m.symbol);await expect(page.locator('#vector-kind')).toHaveValue(kind);await expect(page.locator('#vector-value')).toHaveValue('0');await page.locator('#vector-value').fill('4');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const nonzero=await saved(page);expect(nonzero.semantics.vectors[0]).toEqual(v);expect(nonzero.semantics.variables[0]).toMatchObject({id:m.id,state:'known',value:4,unit});expect((await view(page,g.id)).arrows).toBe(1);expect(nonzero.presentation.elements.find((e:any)=>e.id===g.id).points).toEqual(g.motionArrowPoints);await page.getByTitle('Undo',{exact:true}).click();expect(await saved(page)).toEqual(moved);expect((await view(page,g.id)).arrows).toBe(0);await page.getByTitle('Redo',{exact:true}).click();expect(await saved(page)).toEqual(nonzero);
 await edit(page,m.symbol);await page.locator('#vector-value').fill('0');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();expect((await view(page,g.id)).arrows).toBe(0);await edit(page,m.symbol);await page.locator('#vector-state').selectOption('unknown');await page.getByRole('button',{name:'Save vector',exact:true}).click();await expect(page.locator('#vector-dialog')).not.toBeVisible();const unknown=await saved(page);expect(unknown.semantics.variables[0]).toMatchObject({id:m.id,state:'unknown',unit});expect(unknown.semantics.variables[0].value).toBeUndefined();expect((await view(page,g.id)).arrows).toBe(1);await page.getByTitle('Undo',{exact:true}).click();await page.screenshot({path:`test-results/zero-${kind}-${info.project.name}.png`});expect(errors).toEqual([]);});
