import {parseDocument as parseMath,makeDocument,walk as walkMath} from './vendor/mathed/model';
import {toLatex} from './vendor/mathed/latex';
import type {DiagramDocument} from './model';
import type {Expression,PhysicalVector} from './semantics';
import {physicalConstants} from './constants';
export type Token={type:'reference';id:string}|{type:'number';value:number}|{type:'operation';value:string};
export function references(expression:Expression):string[]{if(expression.type==='mathed'){const ids:string[]=[];walkMath(expression.expression,n=>{if(n.type==='variable')ids.push(n.id);});return ids;}if(expression.type==='reference')return [expression.id];if(expression.type==='binary')return [...references(expression.left),...references(expression.right)];if(expression.type==='unary')return references(expression.operand);return [];}
export function contextualReferences(doc:DiagramDocument,v:PhysicalVector):string[]{
 const ids=new Set<string>();const property=(id:string|undefined,keys:string[])=>{const o=doc.semantics.objects.find(o=>o.id===id);for(const k of keys){const id=o?.properties?.[k];if(id)ids.add(id);}};
 const separation=(id?:string)=>{const s=doc.semantics.vectors.find(v=>v.id===id && v.kind==='separation');if(s)ids.add(s.variableId);};
 if(v.kind==='field'){const source=doc.semantics.objects.find(o=>o.id===v.sourceId);if(v.fieldType==='gravitational'){if(source?.category==='planetSurface')property(source.id,['gravity']);else{property(v.sourceId,['mass']);separation(v.separationId);ids.add('constant:G');}}else{if(source?.category==='chargedPlate')property(source.id,['surfaceChargeDensity']);else{property(v.sourceId,['charge']);separation(v.separationId);}ids.add('constant:ke');}}
 if(v.kind==='force'){const i=doc.semantics.interactions.find(i=>i.id===v.interactionId);if(i?.kind==='gravitational'){if(i.model==='nearSurface'){property(i.sourceId,['gravity']);property(i.targetId,['mass']);}else{property(i.sourceId,['mass']);property(i.targetId,['mass']);separation(i.separationId);ids.add('constant:G');}}else if(i?.kind==='electric'){property(i.sourceId,['charge']);property(i.targetId,['charge']);separation(i.separationId);ids.add('constant:ke');}else if(i?.kind==='buoyant'){property(i.sourceId,['density']);if(i.properties?.volume)ids.add(i.properties.volume);for(const o of doc.semantics.objects)if(o.category==='planetSurface')property(o.id,['gravity']);}else if(i?.model==='spring')property(i.sourceId,['springConstant','extension']);else if(i?.kind==='contact'){property(i.targetId,['mass']);for(const id of Object.values(i.properties||{}))ids.add(id);if(v.role==='friction'){const n=doc.semantics.vectors.find(n=>n.interactionId===i.id && n.role==='normal');if(n)ids.add(n.variableId);}}}
 if(v.kind==='motion')for(const other of doc.semantics.vectors)if(other.kind==='motion' && other.objectId===v.objectId && other.id!==v.id)ids.add(other.variableId);
 ids.delete(v.variableId);return [...ids];
}
export function parseTokens(tokens:Token[]):Expression{
 if(!tokens.length || tokens.length>256)throw new Error('Expression must contain 1–256 tokens.');let index=0;
 const operation=(op:string)=>tokens[index]?.type==='operation' && (tokens[index] as {value:string}).value===op;
 function primary():Expression{const token=tokens[index++];if(!token)throw new Error('Incomplete expression.');if(token.type==='reference')return token;if(token.type==='number'){if(!Number.isFinite(token.value))throw new Error('Invalid numerical literal.');return token;}if(token.value==='pi')return {type:'pi'};if(token.value==='-')return {type:'unary',op:'-',operand:expression(25)};if(token.value==='abs'){if(!operation('('))throw new Error('Absolute value needs parentheses.');index++;const operand=expression(0);if(!operation(')'))throw new Error('Unmatched parentheses.');index++;return {type:'unary',op:'abs',operand};}if(token.value==='('){const e=expression(0);if(!operation(')'))throw new Error('Unmatched parentheses.');index++;return e;}throw new Error('Invalid expression token.');}
 function expression(min:number):Expression{let left=primary();const precedence:Record<string,number>={'+':10,'-':10,'*':20,'/':20,'^':30};while(tokens[index]?.type==='operation'){const op=(tokens[index] as {value:string}).value,p=precedence[op];if(p===undefined || p<min)break;index++;const right=expression(op==='^'?p:p+1);left={type:'binary',op:op as '+'|'-'|'*'|'/'|'^',left,right};}return left;}
 const result=expression(0);if(index!==tokens.length)throw new Error('Unexpected expression token.');return result;
}
export function expressionTokens(e:Expression):Token[]{if(e.type==='mathed')throw new Error('Mathed expressions use structured editing.');if(e.type==='reference'||e.type==='number')return [e];if(e.type==='pi')return [{type:'operation',value:'pi'}];if(e.type==='unary')return [{type:'operation',value:e.op},{type:'operation',value:'('},...expressionTokens(e.operand),{type:'operation',value:')'}];return [{type:'operation',value:'('},...expressionTokens(e.left),{type:'operation',value:e.op},...expressionTokens(e.right),{type:'operation',value:')'}];}
export function expressionLatex(e:Expression,doc:DiagramDocument):string{if(e.type==='mathed')return toLatex(e.expression,expressionVocabulary(doc));if(e.type==='number')return String(e.value);if(e.type==='reference')return doc.semantics.variables.find(v=>v.id===e.id)?.symbol||Object.values(physicalConstants).find(c=>c.id===e.id)?.symbol||'?';if(e.type==='pi')return '\\pi';if(e.type==='unary')return e.op==='abs'?`\\left|${expressionLatex(e.operand,doc)}\\right|`:`-\\left(${expressionLatex(e.operand,doc)}\\right)`;const a=expressionLatex(e.left,doc),b=expressionLatex(e.right,doc);return e.op==='/'?`\\frac{${a}}{${b}}`:e.op==='^'?`\\left(${a}\\right)^{${b}}`:`\\left(${a}${e.op==='*'?'\\cdot':e.op}${b}\\right)`;}
export function validateExpression(value:unknown,allowed:Set<string>):asserts value is Expression{let count=0;function walk(e:any,depth:number){if(!e || typeof e!=='object'||Array.isArray(e)||++count>256||depth>32)throw new Error('Invalid or oversized expression.');switch(e.type){case 'mathed':{const d=parseMath({format:'mathed',version:1,status:'complete',expression:e.expression});if(d.status!=='complete')throw new Error('Complete the expression.');walkMath(d.expression,n=>{if(n.type==='identifier'||n.type==='symbol'||(n.type==='variable'&&!allowed.has(n.id)))throw new Error('Expression references an unavailable variable.');});break;}case 'number':if(typeof e.value!=='number'||!Number.isFinite(e.value))throw new Error('Invalid numerical literal.');break;case 'pi':break;case 'reference':if(typeof e.id!=='string'||!allowed.has(e.id))throw new Error('Expression references an unavailable variable.');break;case 'unary':if(!['-','abs'].includes(e.op))throw new Error('Invalid unary operation.');walk(e.operand,depth+1);break;case 'binary':if(!['+','-','*','/','^'].includes(e.op))throw new Error('Invalid mathematical operation.');walk(e.left,depth+1);walk(e.right,depth+1);break;default:throw new Error('Invalid expression syntax.');}}walk(value,0);}
/** Identity/structure validation only. Expressions are not evaluated or graded. */
export function expressionVocabulary(doc:DiagramDocument){return [...doc.semantics.variables.map(v=>({id:v.id,symbol:v.symbol,quantity:v.quantity,units:v.unit})),...Object.values(physicalConstants).map(c=>({id:c.id,symbol:c.symbol,quantity:c.quantity,units:c.unit}))];}
export function assertExpressions(doc:DiagramDocument){const allowed=new Set(expressionVocabulary(doc).map(v=>v.id));for(const variable of doc.semantics.variables){
 if(variable.state!=='expression'){if(variable.expression!==undefined)throw new Error('Expression contradicts magnitude state.');continue;}
 if(variable.value!==undefined)throw new Error('Expression contradicts numerical value.');
 validateExpression(variable.expression,allowed);
}}
export function ensureNoReferences(doc:DiagramDocument,ids:Set<string>){for(const v of doc.semantics.variables)if(!ids.has(v.id)&&v.expression&&references(v.expression).some(id=>ids.has(id)))throw new Error('This variable is used by an expression. Remove that reference first.');}
