import {clearChangedComponentAngles} from './component-angles';
import {validateRelationships} from './persistence';
import {assertExpressions,ensureNoReferences} from './expressions';
import {eligibility,type Configuration} from './eligibility';
import {DocumentStore,newGraphic,type DiagramDocument,type Graphic} from './model';
import type {PhysicalVector,Quantity,Variable,Interaction} from './semantics';
import {attachmentPoint} from './geometry';
import {synchronizeSymbols} from './naming';
export const quantityUnits:Record<string,string[]>={force:['N','kN'],gravitationalField:['m/s^2','N/kg'],electricField:['N/C','V/m'],length:['m','cm','km'],velocity:['m/s','km/h'],acceleration:['m/s^2'],displacement:['m','cm','km'],staticFriction:['1'],kineticFriction:['1'],volume:['m^3','cm^3','L']};
export interface MagnitudeDraft {symbol?:string;state:'unknown'|'known'|'expression';unit:string;value?:number;expression?:Variable['expression']}
export function validateMagnitude(d:MagnitudeDraft,quantity:Quantity){if(!quantityUnits[quantity]?.includes(d.unit))throw new Error('Unit does not match this quantity.');if(!['unknown','known','expression'].includes(d.state))throw new Error('Invalid magnitude state.');if(d.state==='known' && (d.value===undefined || !Number.isFinite(d.value) || d.value<0 || (quantity==='length' && d.value===0)))throw new Error('Enter an appropriate finite magnitude.');if(d.state==='expression' && !d.expression)throw new Error('Define an expression.');}
export function magnitudeVariable(doc:DiagramDocument,id:string,owner:{ownerVectorId?:string;ownerInteractionId?:string},quantity:Quantity,d:MagnitudeDraft,defaultSymbol:string){validateMagnitude(d,quantity);const old=doc.semantics.variables.find(v=>v.id===id);const symbol=d.symbol?.trim() || old?.symbol || defaultSymbol;if(!symbol || symbol.length>80)throw new Error('Invalid mathematical symbol.');if(d.symbol && doc.semantics.variables.some(v=>v.id!==id && v.symbol.replace(/\s|[{}]/g,'')===symbol.replace(/\s|[{}]/g,'')))throw new Error('The symbol is already used. Choose a distinct subscript.');const v:Variable={id,...owner,quantity,symbol,unit:d.unit,state:d.state,generatedSymbol:d.symbol?(!!old?.generatedSymbol && symbol===old.symbol):(old?.generatedSymbol??true)};if(d.state==='known')v.value=d.value;if(d.state==='expression')v.expression=d.expression;doc.semantics.variables=doc.semantics.variables.filter(v=>v.id!==id);doc.semantics.variables.push(v);return v;}
export function vectorGraphic(doc:DiagramDocument,id:string){return doc.presentation.elements.find(g=>g.vectorId===id);}
export function isZeroMotionVector(doc:DiagramDocument,v:PhysicalVector){
 const magnitude=doc.semantics.variables.find(m=>m.id===v.variableId);
 return v.kind==='motion' && ['acceleration','velocity','displacement'].includes(v.motionType||'') && magnitude?.state==='known' && magnitude.value===0;
}
export function zeroMotionLabelGraphic(g:Graphic):Graphic {
 return {...g,points:[0,0,0,0],label:{...g.label,showName:false,showProperties:true,placement:'objectCenter',offsetX:g.label?.offsetX??0,offsetY:(g.label?.offsetY??0)-40}};
}
/** Reconcile only motion presentation; semantic IDs and magnitude data stay intact. */
export function synchronizeMotionPresentation(doc:DiagramDocument){
 for(const v of doc.semantics.vectors){if(v.kind!=='motion')continue;const g=vectorGraphic(doc,v.id);if(!g)continue;
  if(isZeroMotionVector(doc,v)){
   if(g.kind==='arrow' && g.points[0]===0 && g.points[1]===0) {if(Math.hypot(g.points[2],g.points[3])>0)g.motionArrowPoints=[...g.points];g.kind='text';g.points=[0,0,0,0];}
  }else if(g.kind==='text'){
   g.kind='arrow';g.points=g.motionArrowPoints?[...g.motionArrowPoints]:[0,0,0,-80];delete g.motionArrowPoints;
  }
 }
}
export function objectPosition(doc:DiagramDocument,id?:string){const g=doc.presentation.elements.find(e=>e.semanticId===id);return g && attachmentPoint(g);}
export function displayedVector(doc:DiagramDocument,v:PhysicalVector,g:Graphic):Graphic|undefined{
 const endObject=v.kind==='separation'?v.toId:v.objectId;const endGraphic=doc.presentation.elements.find(e=>e.semanticId===endObject);if(!endGraphic || endGraphic.visible===false)return undefined;
 if(v.kind==='separation'){const startGraphic=doc.presentation.elements.find(e=>e.semanticId===v.fromId);if(!startGraphic || startGraphic.visible===false)return undefined;const start=attachmentPoint(startGraphic),end=attachmentPoint(endGraphic);return {...g,x:start.x,y:start.y,rotation:0,scaleX:1,scaleY:1,points:[0,0,end.x-start.x,end.y-start.y]};}
 const start=attachmentPoint(endGraphic);if(isZeroMotionVector(doc,v))return {...zeroMotionLabelGraphic(g),x:start.x,y:start.y,rotation:0,scaleX:1,scaleY:1};let points=g.points;
 if(v.role==='friction' || v.role==='resultant'){const normal=doc.semantics.vectors.find(n=>n.interactionId===v.interactionId && n.role==='normal');const ng=normal && vectorGraphic(doc,normal.id);const friction=doc.semantics.vectors.find(n=>n.interactionId===v.interactionId && n.role==='friction');const fg=friction && vectorGraphic(doc,friction.id);if(ng){const len=Math.hypot(g.points[2],g.points[3]),a=Math.atan2(ng.points[3],ng.points[2])+Math.PI/2;points=[0,0,len*Math.cos(a),len*Math.sin(a)];if(v.role==='resultant' && fg){const fl=Math.hypot(fg.points[2],fg.points[3]);points=[0,0,ng.points[2]+fl*Math.cos(a),ng.points[3]+fl*Math.sin(a)];}}}
 return {...g,x:start.x,y:start.y,rotation:0,scaleX:1,scaleY:1,points};
}
export function saveSeparation(store:DocumentStore,d:{id?:string;fromId:string;toId:string;magnitude:MagnitudeDraft;visible?:boolean}){
 const doc=structuredClone(store.document);if(d.fromId===d.toId || ![d.fromId,d.toId].every(id=>doc.semantics.objects.some(o=>o.id===id)))throw new Error('Choose two distinct endpoints.');let existing=d.id?doc.semantics.vectors.find(v=>v.id===d.id):undefined;if(d.id && (!existing || existing.kind!=='separation'))throw new Error('Invalid separation.');if(existing && (existing.fromId!==d.fromId || existing.toId!==d.toId) && (doc.semantics.interactions.some(i=>i.separationId===existing!.id)||doc.semantics.vectors.some(v=>v.separationId===existing!.id)))throw new Error('This separation is referenced by an interaction.');
 const id=existing?.id||crypto.randomUUID(),variableId=existing?.variableId||crypto.randomUUID();const vector:PhysicalVector={id,kind:'separation',fromId:d.fromId,toId:d.toId,variableId,showAngles:existing?.showAngles,componentAngle:existing?.componentAngle};doc.semantics.vectors=doc.semantics.vectors.filter(v=>v.id!==id);doc.semantics.vectors.push(vector);
 magnitudeVariable(doc,variableId,{ownerVectorId:id},'length',d.magnitude,`r_{${doc.semantics.vectors.length}}`);synchronizeSymbols(doc);
 let g=vectorGraphic(doc,id);if(!g){g=newGraphic('dashedArrow',doc);g.vectorId=id;g.stroke='#77828a';g.label={placement:'vectorTip',showName:false,showProperties:true,offsetX:0,offsetY:0};doc.presentation.elements.push(g);}g.visible=d.visible??g.visible??true;clearChangedComponentAngles(doc,store.document);doc.metadata.updatedAt=new Date().toISOString();store.replace(doc);return id;
}
export function compatibleSeparations(doc:DiagramDocument,a:string,b:string,ordered=false){return doc.semantics.vectors.filter(v=>v.kind==='separation' && ((v.fromId===a && v.toId===b)||(!ordered && v.fromId===b && v.toId===a)));}
export function saveInteraction(store:DocumentStore,d:Omit<Interaction,'id'|'objectIds'> & {id?:string}){const doc=structuredClone(store.document);if(!d.sourceId||!d.targetId||d.sourceId===d.targetId||![d.sourceId,d.targetId].every(id=>doc.semantics.objects.some(o=>o.id===id)))throw new Error('Invalid interaction participants.');if(d.separationId && !compatibleSeparations(doc,d.sourceId,d.targetId).some(v=>v.id===d.separationId))throw new Error('Invalid interaction separation.');const id=d.id||crypto.randomUUID();if(d.id && !doc.semantics.interactions.some(i=>i.id===id))throw new Error('Missing interaction.');doc.semantics.interactions=doc.semantics.interactions.filter(i=>i.id!==id);doc.semantics.interactions.push({...d,id,objectIds:[d.sourceId,d.targetId]});synchronizeSymbols(doc);doc.metadata.updatedAt=new Date().toISOString();store.replace(doc);return id;}
export function deleteVector(store:DocumentStore,id:string){const doc=structuredClone(store.document),v=doc.semantics.vectors.find(v=>v.id===id);if(!v)return;if(doc.semantics.interactions.some(i=>i.separationId===id) || doc.semantics.vectors.some(v=>v.separationId===id) || doc.semantics.components.some(c=>c.vectorId===id || c.variableId===v.variableId))throw new Error('Remove dependent relationships before deleting this vector.');ensureNoReferences(doc,new Set([v.variableId]));if(v.role && v.interactionId && doc.semantics.vectors.some(n=>n.id!==id && n.interactionId===v.interactionId))throw new Error('Delete the linked interaction group together.');doc.semantics.vectors=doc.semantics.vectors.filter(v=>v.id!==id);doc.semantics.variables=doc.semantics.variables.filter(variable=>variable.ownerVectorId!==id);doc.presentation.elements=doc.presentation.elements.filter(g=>g.vectorId!==id);if(v.interactionId && !doc.semantics.vectors.some(n=>n.interactionId===v.interactionId)){const owned=doc.semantics.variables.filter(variable=>variable.ownerInteractionId===v.interactionId).map(variable=>variable.id);ensureNoReferences(doc,new Set(owned));doc.semantics.interactions=doc.semantics.interactions.filter(i=>i.id!==v.interactionId);doc.semantics.variables=doc.semantics.variables.filter(variable=>variable.ownerInteractionId!==v.interactionId);}doc.metadata.updatedAt=new Date().toISOString();store.replace(doc);}

export interface VectorDraft extends Configuration {id?:string;magnitude:MagnitudeDraft;friction?:'static'|'kinetic';frictionMagnitude?:MagnitudeDraft;coefficient?:MagnitudeDraft;volume?:MagnitudeDraft;resultantVisible?:boolean;visible?:boolean;angle?:number;length?:number;frictionLength?:number}
export function saveVector(store:DocumentStore,d:VectorDraft):string{
 if(d.kind==='separation')return saveSeparation(store,{id:d.id,fromId:d.sourceId!,toId:d.targetId!,magnitude:d.magnitude,visible:d.visible});
 const doc=structuredClone(store.document);if(!eligibility(doc,d))throw new Error('Unavailable vector configuration.');

 let existing=d.id?doc.semantics.vectors.find(v=>v.id===d.id):undefined;if(d.id && !existing)throw new Error('Vector no longer exists.');if(existing && (existing.kind!==(d.kind==='force'?'force':d.kind==='field'?'field':'motion') || (existing.kind==='motion' && existing.motionType!==d.kind)))throw new Error('Saved vector kind cannot be changed.');
 let id=existing?.id||crypto.randomUUID();let interaction:Interaction|undefined;
 if(d.kind==='force'){
  const source=doc.semantics.objects.find(o=>o.id===d.sourceId)!;const model=d.interactionType==='gravitational'?(source.category==='planetSurface'?'nearSurface':'universal'):d.interactionType==='electric'?'pointSource':d.contactType||'ordinary';
  interaction=existing?.interactionId?doc.semantics.interactions.find(i=>i.id===existing!.interactionId):doc.semantics.interactions.find(i=>i.kind===d.interactionType && i.sourceId===d.sourceId && i.targetId===d.targetId && i.model===model && i.separationId===d.separationId && i.friction===d.friction);
  if(!interaction){interaction={id:crypto.randomUUID(),kind:d.interactionType!,model,sourceId:d.sourceId,targetId:d.targetId,objectIds:[d.sourceId!,d.targetId!],properties:{}};doc.semantics.interactions.push(interaction);}
  if(existing && (interaction.sourceId!==d.sourceId || interaction.targetId!==d.targetId || interaction.kind!==d.interactionType || interaction.model!==model))throw new Error('A saved vector retains its interaction. Create a different vector for another relationship.');
  interaction.separationId=d.separationId;interaction.friction=d.friction;interaction.resultantVisible=!!d.resultantVisible;
  const properties:Record<string,string>={};
  if(d.interactionType==='buoyant'){const variableId=interaction.properties?.volume||crypto.randomUUID();magnitudeVariable(doc,variableId,{ownerInteractionId:interaction.id},'volume',d.volume||{state:'unknown',unit:'m^3'},`V_{disp${doc.semantics.interactions.length===1?'':doc.semantics.interactions.length}}`);properties.volume=variableId;}
  if(d.friction && d.coefficient){const key=d.friction==='static'?'staticFriction':'kineticFriction',variableId=interaction.properties?.[key]||crypto.randomUUID();magnitudeVariable(doc,variableId,{ownerInteractionId:interaction.id},key,d.coefficient,`${d.friction==='static'?'\\mu_s':'\\mu_k'}_{${doc.semantics.interactions.length}}`);properties[key]=variableId;}
  for(const old of Object.values(interaction.properties||{}))if(!Object.values(properties).includes(old)){ensureNoReferences(doc,new Set([old]));doc.semantics.variables=doc.semantics.variables.filter(v=>v.id!==old);}
  interaction.properties=properties;
 }
 const kind=d.kind==='force'?'force':d.kind==='field'?'field':'motion',quantity:Quantity=d.kind==='field'?(d.interactionType==='gravitational'?'gravitationalField':'electricField'):d.kind==='force'?'force':d.kind;
 if(interaction && d.friction && !existing){existing=doc.semantics.vectors.find(v=>v.interactionId===interaction!.id && v.role==='normal');if(existing)id=existing.id;}
 const variableId=existing?.variableId||crypto.randomUUID();
 const vector:PhysicalVector={id,kind,variableId,objectId:d.targetId,showAngles:existing?.showAngles,componentAngle:existing?.componentAngle};if(kind==='force'){vector.interactionId=interaction!.id;if(d.friction)vector.role=existing?.role==='friction'?'friction':'normal';}if(kind==='field'){vector.sourceId=d.sourceId;vector.fieldType=d.interactionType as 'gravitational'|'electric';vector.separationId=d.separationId;}if(kind==='motion')vector.motionType=d.kind as 'velocity'|'acceleration'|'displacement';
 doc.semantics.vectors=doc.semantics.vectors.filter(v=>v.id!==id);doc.semantics.vectors.push(vector);magnitudeVariable(doc,variableId,{ownerVectorId:id},quantity,d.magnitude,`u_{${doc.semantics.vectors.length}}`);
 const addGraphic=(v:PhysicalVector,visible:boolean,length=80,angle=-90)=>{let g=vectorGraphic(doc,v.id);if(!g){g=newGraphic('arrow',doc);g.vectorId=v.id;g.points=[0,0,length*Math.cos(angle*Math.PI/180),length*Math.sin(angle*Math.PI/180)];g.stroke=v.kind==='field'?'#9954a7':v.kind==='motion'?'#277d86':'#c54840';g.label={placement:'vectorTip',showName:false,showProperties:true,offsetX:0,offsetY:0};doc.presentation.elements.push(g);}g.visible=visible;if(d.angle!==undefined || d.length!==undefined){const a=(d.angle??Math.atan2(g.points[3],g.points[2])*180/Math.PI)*Math.PI/180,l=d.length??Math.hypot(g.points[2],g.points[3]);if(!Number.isFinite(a)||!Number.isFinite(l)||l<=0||l>10000)throw new Error('Invalid graphical direction or length.');g.points=[0,0,l*Math.cos(a),l*Math.sin(a)];}return g;};
 addGraphic(vector,d.visible??vectorGraphic(doc,id)?.visible??true);
 if(interaction && d.friction){for(const role of ['normal','friction','resultant'] as const){if(role===vector.role)continue;let other=doc.semantics.vectors.find(v=>v.interactionId===interaction!.id && v.role===role);if(!other){other={id:crypto.randomUUID(),kind:'force',objectId:d.targetId,interactionId:interaction.id,role,variableId:crypto.randomUUID()};doc.semantics.vectors.push(other);magnitudeVariable(doc,other.variableId,{ownerVectorId:other.id},'force',role==='friction'?(d.frictionMagnitude||{state:'unknown',unit:'N'}):{state:'unknown',unit:'N'},`u_{${doc.semantics.vectors.length}}`);}else if(role==='friction' && d.frictionMagnitude)magnitudeVariable(doc,other.variableId,{ownerVectorId:other.id},'force',d.frictionMagnitude,doc.semantics.variables.find(v=>v.id===other!.variableId)!.symbol);const g=addGraphic(other,role==='resultant'?!!d.resultantVisible:true);if(role==='friction' && d.frictionLength!==undefined){if(d.frictionLength<=0||!Number.isFinite(d.frictionLength))throw new Error('Invalid friction length.');g.points=[0,0,d.frictionLength,0];}}}
 if(interaction && !d.friction){const remove=doc.semantics.vectors.filter(v=>v.interactionId===interaction!.id && v.id!==id && v.role).map(v=>v.id);ensureNoReferences(doc,new Set(doc.semantics.variables.filter(v=>remove.includes(v.ownerVectorId||'')).map(v=>v.id)));doc.semantics.vectors=doc.semantics.vectors.filter(v=>!remove.includes(v.id));doc.semantics.variables=doc.semantics.variables.filter(v=>!remove.includes(v.ownerVectorId||''));doc.presentation.elements=doc.presentation.elements.filter(g=>!remove.includes(g.vectorId||''));}
 synchronizeSymbols(doc);synchronizeMotionPresentation(doc);clearChangedComponentAngles(doc,store.document);assertExpressions(doc);validateRelationships(doc);doc.metadata.updatedAt=new Date().toISOString();store.replace(doc);return id;
}
export function deleteInteraction(store:DocumentStore,id:string){const doc=structuredClone(store.document);const vectors=doc.semantics.vectors.filter(v=>v.interactionId===id).map(v=>v.id);const variables=doc.semantics.variables.filter(v=>v.ownerInteractionId===id || vectors.includes(v.ownerVectorId||'')).map(v=>v.id);ensureNoReferences(doc,new Set(variables));if(doc.semantics.components.some(c=>vectors.includes(c.vectorId)||variables.includes(c.variableId)))throw new Error('Remove dependent components first.');doc.semantics.vectors=doc.semantics.vectors.filter(v=>!vectors.includes(v.id));doc.semantics.variables=doc.semantics.variables.filter(v=>!variables.includes(v.id));doc.presentation.elements=doc.presentation.elements.filter(g=>!vectors.includes(g.vectorId||''));doc.semantics.interactions=doc.semantics.interactions.filter(i=>i.id!==id);doc.metadata.updatedAt=new Date().toISOString();store.replace(doc);}
