import {DocumentStore,newGraphic,type DiagramDocument,type Graphic} from './model';
import type {PhysicalVector,Quantity,Variable,Interaction} from './semantics';
import {attachmentPoint} from './geometry';
import {synchronizeSymbols} from './naming';
export const quantityUnits:Record<string,string[]>={force:['N','kN'],gravitationalField:['m/s^2','N/kg'],electricField:['N/C','V/m'],length:['m','cm','km'],velocity:['m/s','km/h'],acceleration:['m/s^2'],displacement:['m','cm','km'],staticFriction:['1'],kineticFriction:['1'],volume:['m^3','cm^3','L']};
export interface MagnitudeDraft {symbol?:string;state:'unknown'|'known'|'expression';unit:string;value?:number;expression?:Variable['expression']}
export function validateMagnitude(d:MagnitudeDraft,quantity:Quantity){if(!quantityUnits[quantity]?.includes(d.unit))throw new Error('Unit does not match this quantity.');if(!['unknown','known','expression'].includes(d.state))throw new Error('Invalid magnitude state.');if(d.state==='known' && (d.value===undefined || !Number.isFinite(d.value) || d.value<0 || (quantity==='length' && d.value===0)))throw new Error('Enter an appropriate finite magnitude.');if(d.state==='expression' && !d.expression)throw new Error('Define an expression.');}
export function magnitudeVariable(doc:DiagramDocument,id:string,owner:{ownerVectorId?:string;ownerInteractionId?:string},quantity:Quantity,d:MagnitudeDraft,defaultSymbol:string){validateMagnitude(d,quantity);const old=doc.semantics.variables.find(v=>v.id===id);const symbol=d.symbol?.trim() || old?.symbol || defaultSymbol;if(!symbol || symbol.length>80)throw new Error('Invalid mathematical symbol.');if(doc.semantics.variables.some(v=>v.id!==id && v.symbol.replace(/\s|[{}]/g,'')===symbol.replace(/\s|[{}]/g,'')))throw new Error('The symbol is already used. Choose a distinct subscript.');const v:Variable={id,...owner,quantity,symbol,unit:d.unit,state:d.state,generatedSymbol:!d.symbol};if(d.state==='known')v.value=d.value;if(d.state==='expression')v.expression=d.expression;doc.semantics.variables=doc.semantics.variables.filter(v=>v.id!==id);doc.semantics.variables.push(v);return v;}
export function vectorGraphic(doc:DiagramDocument,id:string){return doc.presentation.elements.find(g=>g.vectorId===id);}
export function objectPosition(doc:DiagramDocument,id?:string){const g=doc.presentation.elements.find(e=>e.semanticId===id);return g && attachmentPoint(g);}
export function displayedVector(doc:DiagramDocument,v:PhysicalVector,g:Graphic):Graphic|undefined{
 const endObject=v.kind==='separation'?v.toId:v.objectId;const endGraphic=doc.presentation.elements.find(e=>e.semanticId===endObject);if(!endGraphic || endGraphic.visible===false)return undefined;
 if(v.kind==='separation'){const startGraphic=doc.presentation.elements.find(e=>e.semanticId===v.fromId);if(!startGraphic || startGraphic.visible===false)return undefined;const start=attachmentPoint(startGraphic),end=attachmentPoint(endGraphic);return {...g,x:start.x,y:start.y,rotation:0,scaleX:1,scaleY:1,points:[0,0,end.x-start.x,end.y-start.y]};}
 const start=attachmentPoint(endGraphic);let points=g.points;
 if(v.role==='friction' || v.role==='resultant'){const normal=doc.semantics.vectors.find(n=>n.interactionId===v.interactionId && n.role==='normal');const ng=normal && vectorGraphic(doc,normal.id);const friction=doc.semantics.vectors.find(n=>n.interactionId===v.interactionId && n.role==='friction');const fg=friction && vectorGraphic(doc,friction.id);if(ng){const len=Math.hypot(g.points[2],g.points[3]),a=Math.atan2(ng.points[3],ng.points[2])+Math.PI/2;points=[0,0,len*Math.cos(a),len*Math.sin(a)];if(v.role==='resultant' && fg){const fl=Math.hypot(fg.points[2],fg.points[3]);points=[0,0,ng.points[2]+fl*Math.cos(a),ng.points[3]+fl*Math.sin(a)];}}}
 return {...g,x:start.x,y:start.y,rotation:0,scaleX:1,scaleY:1,points};
}
export function saveSeparation(store:DocumentStore,d:{id?:string;fromId:string;toId:string;magnitude:MagnitudeDraft;visible?:boolean}){
 const doc=structuredClone(store.document);if(d.fromId===d.toId || ![d.fromId,d.toId].every(id=>doc.semantics.objects.some(o=>o.id===id)))throw new Error('Choose two distinct endpoints.');const existing=d.id?doc.semantics.vectors.find(v=>v.id===d.id):undefined;if(d.id && (!existing || existing.kind!=='separation'))throw new Error('Invalid separation.');if(existing && (existing.fromId!==d.fromId || existing.toId!==d.toId) && doc.semantics.interactions.some(i=>i.separationId===existing.id))throw new Error('This separation is referenced by an interaction.');
 const id=existing?.id||crypto.randomUUID(),variableId=existing?.variableId||crypto.randomUUID();const vector:PhysicalVector={id,kind:'separation',fromId:d.fromId,toId:d.toId,variableId};doc.semantics.vectors=doc.semantics.vectors.filter(v=>v.id!==id);doc.semantics.vectors.push(vector);
 magnitudeVariable(doc,variableId,{ownerVectorId:id},'length',d.magnitude,`r_{${doc.semantics.vectors.length}}`);synchronizeSymbols(doc);
 let g=vectorGraphic(doc,id);if(!g){g=newGraphic('dashedArrow',doc);g.vectorId=id;g.stroke='#77828a';g.label={showName:false,showProperties:true,offsetX:12,offsetY:12};doc.presentation.elements.push(g);}g.visible=d.visible??g.visible??true;store.replace(doc);return id;
}
export function compatibleSeparations(doc:DiagramDocument,a:string,b:string,ordered=false){return doc.semantics.vectors.filter(v=>v.kind==='separation' && ((v.fromId===a && v.toId===b)||(!ordered && v.fromId===b && v.toId===a)));}
export function saveInteraction(store:DocumentStore,d:Omit<Interaction,'id'|'objectIds'> & {id?:string}){const doc=structuredClone(store.document);if(!d.sourceId||!d.targetId||d.sourceId===d.targetId||![d.sourceId,d.targetId].every(id=>doc.semantics.objects.some(o=>o.id===id)))throw new Error('Invalid interaction participants.');if(d.separationId && !compatibleSeparations(doc,d.sourceId,d.targetId).some(v=>v.id===d.separationId))throw new Error('Invalid interaction separation.');const id=d.id||crypto.randomUUID();if(d.id && !doc.semantics.interactions.some(i=>i.id===id))throw new Error('Missing interaction.');doc.semantics.interactions=doc.semantics.interactions.filter(i=>i.id!==id);doc.semantics.interactions.push({...d,id,objectIds:[d.sourceId,d.targetId]});store.replace(doc);return id;}
export function deleteVector(store:DocumentStore,id:string){const doc=structuredClone(store.document),v=doc.semantics.vectors.find(v=>v.id===id);if(!v)return;if(doc.semantics.interactions.some(i=>i.separationId===id) || doc.semantics.vectors.some(v=>v.separationId===id) || doc.semantics.components.some(c=>c.vectorId===id || c.variableId===v.variableId))throw new Error('Remove dependent relationships before deleting this vector.');if(v.interactionId && doc.semantics.vectors.some(n=>n.id!==id && n.interactionId===v.interactionId))throw new Error('Delete the linked interaction group together.');doc.semantics.vectors=doc.semantics.vectors.filter(v=>v.id!==id);doc.semantics.variables=doc.semantics.variables.filter(variable=>variable.ownerVectorId!==id);doc.presentation.elements=doc.presentation.elements.filter(g=>g.vectorId!==id);if(v.interactionId){doc.semantics.interactions=doc.semantics.interactions.filter(i=>i.id!==v.interactionId);doc.semantics.variables=doc.semantics.variables.filter(variable=>variable.ownerInteractionId!==v.interactionId);}store.replace(doc);}
