import {mountExpression,readExpression} from './expression-ui';
import type {DiagramDocument} from './model';
import {generatedMagnitudeSymbol,vectorSymbol,interactionSymbol,synchronizeSymbols} from './naming';
import katex from 'katex';
import {DocumentStore,newDocument} from './model';
import {DiagramRenderer} from './renderer';
import {saveVector,deleteVector,deleteInteraction,vectorGraphic,quantityUnits,type MagnitudeDraft,type VectorDraft} from './physics';
import {eligibility,choiceAvailable,anyEligible,matchingSeparations,type Configuration,type VectorChoice} from './eligibility';
import type {Variable,PhysicalVector} from './semantics';
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
export function showMagnitude(host:HTMLElement,prefix:string,quantity:string,variable?:Variable, context?:{doc:DiagramDocument;vector:PhysicalVector}){
 host.replaceChildren();const add=(name:string,control:HTMLElement)=>{const label=document.createElement('label');label.textContent=name;label.append(control);host.append(label);};
 const symbol=document.createElement('div');symbol.id=`${prefix}-preview`;symbol.className='symbol-preview';symbol.innerHTML=katex.renderToString(variable?.symbol||generatedMagnitudeSymbol(context?.doc||newDocument(),context?.vector,quantity),{throwOnError:false,trust:false,maxExpand:1000});symbol.dataset.custom=String(variable ? !variable.generatedSymbol : false);host.append(symbol);
 const state=document.createElement('select');state.id=`${prefix}-state`;for(const key of context?['unknown','known','expression']:['unknown','known']){const option=document.createElement('option');option.value=key;option.textContent=key==='known'?'Known':key==='expression'?'Expression':'Unknown';state.append(option);}state.value=variable?.state||'unknown';add('Magnitude state',state);
 const value=document.createElement('input');value.id=`${prefix}-value`;value.inputMode='decimal';value.value=variable?.value===undefined?'':String(variable.value);add('Numerical magnitude',value);
 const unit=document.createElement('select');unit.id=`${prefix}-unit`;for(const name of quantityUnits[quantity]||[]){const option=document.createElement('option');option.textContent=name;unit.append(option);}unit.value=variable?.unit||quantityUnits[quantity]?.[0];add('Units',unit);
 const expression=document.createElement('div');expression.id=`${prefix}-expression`;host.append(expression);if(context)mountExpression(expression,context.doc,context.vector,variable?.expression);
 const refresh=()=>{expression.hidden=state.value!=='expression';value.disabled=state.value!=='known';value.required=state.value==='known';value.parentElement!.hidden=state.value!=='known';};state.addEventListener('change',refresh);refresh();
}
export function readMagnitude(prefix:string):MagnitudeDraft{const state=$<HTMLSelectElement>(`#${prefix}-state`).value as MagnitudeDraft['state'];const d:MagnitudeDraft={state,unit:$<HTMLSelectElement>(`#${prefix}-unit`).value};if(state==='expression')d.expression=readExpression($(`#${prefix}-expression`));if(state==='known'){const text=$<HTMLInputElement>(`#${prefix}-value`).value.trim();if(!text)throw new Error('Enter a numerical magnitude.');d.value=Number(text);}return d;}
export function initializeVectors(store:DocumentStore,renderer:DiagramRenderer){
 const dialog=$<HTMLDialogElement>('#vector-dialog'),error=$('#vector-error');let editingId:string|undefined;let saving=false;
 const value=(id:string)=>$<HTMLSelectElement>(id).value;const variable=(id?:string)=>store.document.semantics.variables.find(v=>v.id===id);
 function config():Configuration{return {kind:value('#vector-kind') as VectorChoice,interactionType:value('#vector-interaction') as Configuration['interactionType'],contactType:value('#vector-contact') as Configuration['contactType'],sourceId:value('#vector-from'),targetId:value('#vector-to'),separationId:value('#vector-separation')||undefined};}
 function options(id:string,entries:{id:string;name:string;disabled?:boolean}[],chosen?:string){const host=$<HTMLSelectElement>(id),old=chosen??host.value;host.replaceChildren();for(const entry of entries){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.name;if(entry.disabled)continue;option.disabled=false;host.append(option);}host.value=entries.some(e=>e.id===old && !e.disabled)?old:entries.find(e=>!e.disabled)?.id||'';}
 function context(c:Configuration,id?:string){const doc=structuredClone(store.document),existing=doc.semantics.vectors.find(v=>v.id===id);if(existing)return {doc,vector:existing};const vector:PhysicalVector={id:'draft',variableId:'draft-magnitude',kind:c.kind==='separation'?'separation':c.kind==='force'?'force':c.kind==='field'?'field':'motion',fromId:c.sourceId,toId:c.targetId,objectId:c.targetId,sourceId:c.sourceId,fieldType:c.interactionType as 'gravitational'|'electric',separationId:c.separationId,motionType:c.kind as 'velocity'|'acceleration'|'displacement'};if(c.kind==='force'){const source=doc.semantics.objects.find(o=>o.id===c.sourceId),i={id:'draft-interaction',kind:c.interactionType!,sourceId:c.sourceId,targetId:c.targetId,objectIds:[c.sourceId!,c.targetId!],separationId:c.separationId,model:(c.interactionType==='gravitational'?(source?.category==='planetSurface'?'nearSurface':'universal'):c.contactType||'ordinary') as 'nearSurface'|'universal'|'ordinary'|'spring'|'cable'};const existing=doc.semantics.interactions.find(n=>n.kind===i.kind && n.sourceId===i.sourceId && n.targetId===i.targetId && n.model===i.model && n.separationId===i.separationId);if(!existing)doc.semantics.interactions.push(i);vector.interactionId=existing?.id||i.id;}return {doc,vector};}
 function refresh(resetMagnitude=false){const doc=store.document;
 const hasCoordinates=!!doc.semantics.coordinateSystems.length;$<HTMLInputElement>('#vector-components').disabled=!hasCoordinates;$('#components-label').hidden=!hasCoordinates;$('#components-hint').hidden=hasCoordinates;
let c=config();const pair=c.kind==='force'||c.kind==='field';$('#interaction-label').hidden=!pair;$('#contact-label').hidden=!(c.kind==='force' && c.interactionType==='contact');$('#from-label').hidden=['velocity','acceleration','displacement'].includes(c.kind);$('#from-label span').textContent=c.kind==='separation'?'FROM':'BY';$('#to-label span').textContent=c.kind==='field'?'AT':c.kind==='separation'?'TO':'ON';
 for(const option of $<HTMLSelectElement>('#vector-kind').options)option.disabled=!choiceAvailable(doc,option.value as VectorChoice);
 for(const option of $<HTMLSelectElement>('#vector-interaction').options)option.disabled=c.kind==='field'?!['gravitational','electric'].includes(option.value)||!anyEligible(doc,{kind:'field',interactionType:option.value as Configuration['interactionType']}):option.value==='contact'?!['ordinary','spring','cable'].some(type=>anyEligible(doc,{kind:'force',interactionType:'contact',contactType:type as Configuration['contactType']})):!anyEligible(doc,{kind:'force',interactionType:option.value as Configuration['interactionType']});
 for(const option of $<HTMLSelectElement>('#vector-interaction').options)option.hidden=option.disabled;
 if(pair && $<HTMLSelectElement>('#vector-interaction').selectedOptions[0]?.disabled){$<HTMLSelectElement>('#vector-interaction').value=Array.from($<HTMLSelectElement>('#vector-interaction').options).find(o=>!o.disabled)?.value||'';c=config();}
 for(const option of $<HTMLSelectElement>('#vector-contact').options)option.disabled=!anyEligible(doc,{kind:'force',interactionType:'contact',contactType:option.value as Configuration['contactType']});
 for(const option of $<HTMLSelectElement>('#vector-contact').options)option.hidden=option.disabled;
 if(c.interactionType==='contact' && $<HTMLSelectElement>('#vector-contact').selectedOptions[0]?.disabled){$<HTMLSelectElement>('#vector-contact').value=Array.from($<HTMLSelectElement>('#vector-contact').options).find(o=>!o.disabled)?.value||'';c=config();}
 options('#vector-from',doc.semantics.objects.map(o=>({id:o.id,name:o.name,disabled:!doc.semantics.objects.some(t=>eligibility(doc,{...c,sourceId:o.id,targetId:t.id},false))})));c=config();
 options('#vector-to',doc.semantics.objects.map(o=>({id:o.id,name:o.name,disabled:!eligibility(doc,{...c,targetId:o.id},false)})));c=config();
 $('#contact-label').hidden=!(c.kind==='force' && c.interactionType==='contact');
 const source=doc.semantics.objects.find(o=>o.id===c.sourceId);const needsSeparation=(c.kind==='force' && ['gravitational','electric'].includes(c.interactionType||'') && source?.category!=='planetSurface')||(c.kind==='field' && !['planetSurface','chargedPlate'].includes(source?.category||''));$('#separation-label').hidden=!needsSeparation;options('#vector-separation',needsSeparation?matchingSeparations(doc,c).map(v=>({id:v.id,name:variable(v.variableId)?.symbol||'Separation'})):[]);c=config();
 $('#friction-options').hidden=!(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary');const friction=value('#vector-friction')!=='none';for(const id of ['#friction-magnitude','#coefficient-enabled','#resultant-visible']){const el=$(id);(el.parentElement?.tagName==='LABEL'?el.parentElement:el).hidden=!friction;}$('#coefficient-fields').hidden=!friction || !$<HTMLInputElement>('#coefficient-enabled').checked;$('#volume-fields').hidden=!(c.kind==='force' && c.interactionType==='buoyant');
 const q=c.kind==='force'?'force':c.kind==='field'?(c.interactionType==='gravitational'?'gravitationalField':'electricField'):c.kind==='separation'?'length':c.kind;
 if(resetMagnitude){showMagnitude($('#magnitude-fields'),'vector',q,undefined,c.kind==='separation'?undefined:context(c,editingId));showMagnitude($('#friction-magnitude'),'friction','force');showMagnitude($('#coefficient-fields'),'coefficient',value('#vector-friction')==='kinetic'?'kineticFriction':'staticFriction');showMagnitude($('#volume-fields'),'volume','volume');}
 for(const input of document.querySelectorAll<HTMLInputElement>('#vector-form input[required]'))input.disabled=!!input.closest('[hidden]');
 const ctx=context(c,editingId),previewVector={...ctx.vector};if(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary')previewVector.role=friction?'normal':undefined;
 const preview=$('#vector-preview');if(preview.dataset.custom!=='true' || (friction && preview.textContent?.replace(/\s/g,'').includes('F')))preview.innerHTML=katex.renderToString(vectorSymbol(ctx.doc,previewVector),{throwOnError:false,trust:false,maxExpand:1000});
 for(const [prefix,role]of [['friction','friction']] as const){const el=$(`#${prefix}-preview`);if(el.dataset.custom!=='true')el.innerHTML=katex.renderToString(vectorSymbol(ctx.doc,{...previewVector,role}),{throwOnError:false,trust:false,maxExpand:1000});}
 for(const prefix of ['coefficient','volume']){const el=$(`#${prefix}-preview`);if(el.dataset.custom!=='true' && previewVector.interactionId)el.innerHTML=katex.renderToString(interactionSymbol(ctx.doc,previewVector.interactionId,prefix==='volume'?'volume':value('#vector-friction')==='kinetic'?'kineticFriction':'staticFriction'),{throwOnError:false,trust:false,maxExpand:1000});}
 $<HTMLButtonElement>('#save-vector').disabled=!eligibility(doc,c);}
 function open(id?:string){let v=store.document.semantics.vectors.find(v=>v.id===id);if(v?.role && v.role!=='normal'){v=store.document.semantics.vectors.find(n=>n.interactionId===v!.interactionId && n.role==='normal')||v;id=v.id;}editingId=id;error.textContent='';const i=store.document.semantics.interactions.find(i=>i.id===v?.interactionId),doc=store.document;
 $<HTMLSelectElement>('#vector-kind').value=v?.kind==='motion'?v.motionType!:v?.kind||(['separation','velocity','force','field'].find(kind=>choiceAvailable(doc,kind as VectorChoice))||'separation');$<HTMLSelectElement>('#vector-kind').disabled=!!id;
 $<HTMLSelectElement>('#vector-interaction').value=i?.kind||v?.fieldType||'gravitational';$<HTMLSelectElement>('#vector-contact').value=i?.model==='spring'?'spring':i?.model==='cable'?'cable':'ordinary';
 options('#vector-from',doc.semantics.objects.map(o=>({id:o.id,name:o.name})),v?.fromId||v?.sourceId||i?.sourceId);options('#vector-to',doc.semantics.objects.map(o=>({id:o.id,name:o.name})),v?.toId||v?.objectId||doc.semantics.objects[1]?.id);options('#vector-separation',doc.semantics.vectors.filter(v=>v.kind==='separation').map(v=>({id:v.id,name:variable(v.variableId)?.symbol||'Separation'})),v?.separationId||i?.separationId);
 $<HTMLSelectElement>('#vector-friction').value=i?.friction||'none';$<HTMLInputElement>('#coefficient-enabled').checked=!!(i?.properties?.staticFriction||i?.properties?.kineticFriction);$<HTMLInputElement>('#resultant-visible').checked=!!i?.resultantVisible;refresh(true);
 const g=v && vectorGraphic(doc,v.id),m=variable(v?.variableId);const q=m?.quantity|| (config().kind==='separation'?'length':config().kind==='force'?'force':config().kind==='field'?(config().interactionType==='gravitational'?'gravitationalField':'electricField'):config().kind);showMagnitude($('#magnitude-fields'),'vector',q,m,config().kind==='separation'?undefined:context(config(),editingId));
 const fv=doc.semantics.vectors.find(n=>n.interactionId===i?.id && n.role==='friction'),fg=fv && vectorGraphic(doc,fv.id);showMagnitude($('#friction-magnitude'),'friction','force',variable(fv?.variableId),fv?{doc,vector:fv}:undefined);showMagnitude($('#coefficient-fields'),'coefficient',i?.friction==='kinetic'?'kineticFriction':'staticFriction',variable(i?.properties?.staticFriction||i?.properties?.kineticFriction));showMagnitude($('#volume-fields'),'volume','volume',variable(i?.properties?.volume));$<HTMLInputElement>('#vector-components').checked=g?.showComponents!==false;$<HTMLInputElement>('#vector-visible').checked=g?.visible!==false;refresh();dialog.showModal();}
 function collection(){const modal=$<HTMLDialogElement>('#vector-collection'),host=$('#vector-list');host.replaceChildren();$('#vector-collection-error').textContent='';for(const vector of store.document.semantics.vectors){const m=variable(vector.variableId),g=vectorGraphic(store.document,vector.id),row=document.createElement('div');row.className='object-row';for(const label of ['Select','Edit',g?.visible===false?'Show':'Hide',vector.role?'Delete group':'Delete']){const button=document.createElement('button');button.setAttribute('aria-label',`${label} ${m?.symbol||vector.kind}`);button.append(document.createTextNode(label+' '));const math=document.createElement('span');math.innerHTML=katex.renderToString(m?.symbol||vector.kind,{throwOnError:false,trust:false,maxExpand:1000});button.append(math);button.addEventListener('click',async()=>{try{if(label==='Edit'){modal.close();open(vector.id);}else if(label==='Select'){modal.close();renderer.select(g?.id||null);}else{if(label==='Delete group')deleteInteraction(store,vector.interactionId!);else if(label==='Delete')deleteVector(store,vector.id);else if(g){store.update(g.id,{visible:g.visible===false});if(vector.role==='resultant'){store.document.semantics.interactions.find(i=>i.id===vector.interactionId)!.resultantVisible=g.visible;}}await renderer.render();collection();}}catch(e){$('#vector-collection-error').textContent=(e as Error).message;}});row.append(button);}host.append(row);}if(!modal.open)modal.showModal();}
 for(const id of ['#vector-kind','#vector-interaction','#vector-contact'])$(id).addEventListener('change',()=>refresh(true));for(const id of ['#vector-from','#vector-to','#vector-separation'])$(id).addEventListener('change',()=>refresh(true));for(const id of ['#vector-friction','#coefficient-enabled'])$(id).addEventListener('change',()=>refresh());
 $('[data-action="vector"]').addEventListener('click',()=>open());document.querySelectorAll('[data-action="vectors"]').forEach(button=>button.addEventListener('click',collection));$('#cancel-vector').addEventListener('click',()=>dialog.close());$('#close-vectors').addEventListener('click',()=> $<HTMLDialogElement>('#vector-collection').close());
 $('#vector-form').addEventListener('submit',async event=>{event.preventDefault();if(saving)return;saving=true;$<HTMLButtonElement>('#save-vector').disabled=true;try{const c=config(),d:VectorDraft={...c,id:editingId,magnitude:readMagnitude('vector'),visible:$<HTMLInputElement>('#vector-visible').checked};if(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary' && value('#vector-friction')!=='none'){d.friction=value('#vector-friction') as 'static'|'kinetic';d.frictionMagnitude=readMagnitude('friction');d.resultantVisible=$<HTMLInputElement>('#resultant-visible').checked;if($<HTMLInputElement>('#coefficient-enabled').checked)d.coefficient=readMagnitude('coefficient');}if(c.kind==='force' && c.interactionType==='buoyant')d.volume=readMagnitude('volume');const id=saveVector(store,d);const graphic=vectorGraphic(store.document,id)!;if(store.document.semantics.coordinateSystems.length)store.update(graphic.id,{showComponents:$<HTMLInputElement>('#vector-components').checked});await renderer.render();renderer.select(vectorGraphic(store.document,id)!.id);dialog.close();}catch(e){error.textContent=(e as Error).message;}finally{saving=false;if(dialog.open)refresh();}});
 function availability(){$<HTMLButtonElement>('[data-action="vector"]').disabled=!(['force','field','separation','velocity','acceleration','displacement'] as VectorChoice[]).some(kind=>choiceAvailable(store.document,kind));}store.subscribe(availability);availability();return {open,collection};
}
