import {componentAngleSymbol,componentAngleValues,componentAngleGeometry,angleGraphic,applyComponentAngle} from './component-angles';
import {mountExpression,readExpression,updateExpressionVocabulary} from './expression-ui';
import type {DiagramDocument} from './model';
import {generatedMagnitudeSymbol,vectorSymbol,interactionSymbol,synchronizeSymbols} from './naming';
import katex from 'katex';
import {DocumentStore,newDocument} from './model';
import {DiagramRenderer} from './renderer';
import {saveVector,deleteVector,deleteInteraction,vectorGraphic,quantityUnits,type MagnitudeDraft,type VectorDraft} from './physics';
import {eligibility,choiceAvailable,anyEligible,matchingSeparations,type Configuration,type VectorChoice} from './eligibility';
import type {Variable,PhysicalVector,ComponentAngleDefinition} from './semantics';
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
export function showMagnitude(host:HTMLElement,prefix:string,quantity:string,variable?:Variable, context?:{doc:DiagramDocument;vector:PhysicalVector}){
 host.replaceChildren();const add=(name:string,control:HTMLElement)=>{const label=document.createElement('label');label.textContent=name;label.append(control);host.append(label);};
 const symbol=document.createElement('div');symbol.id=`${prefix}-preview`;symbol.className='symbol-preview';symbol.innerHTML=katex.renderToString(variable?.symbol||generatedMagnitudeSymbol(context?.doc||newDocument(),context?.vector,quantity),{throwOnError:false,trust:false,maxExpand:1000});symbol.dataset.custom=String(variable ? !variable.generatedSymbol : false);host.append(symbol);
 const state=document.createElement('select');state.id=`${prefix}-state`;for(const key of context?['unknown','known','expression']:['unknown','known']){const option=document.createElement('option');option.value=key;option.textContent=key==='known'?'Known':key==='expression'?'Expression':'Unknown';state.append(option);}state.value=variable?.state||'unknown';add(prefix==='friction'?'Define friction':'Magnitude state',state);
 const value=document.createElement('input');value.id=`${prefix}-value`;value.inputMode='decimal';value.value=variable?.value===undefined?'':String(variable.value);add('Numerical magnitude',value);
 const unit=document.createElement('select');unit.id=`${prefix}-unit`;for(const name of quantityUnits[quantity]||[]){const option=document.createElement('option');option.textContent=name;unit.append(option);}unit.value=variable?.unit||quantityUnits[quantity]?.[0];add('Units',unit);
 if(quantity==='staticFriction'||quantity==='kineticFriction')unit.parentElement!.hidden=true;
 const expression=document.createElement('div');expression.id=`${prefix}-expression`;host.append(expression);if(context)mountExpression(expression,context.doc,context.vector,variable?.expression);
 const refresh=()=>{expression.hidden=state.value!=='expression';value.disabled=state.value!=='known';value.required=state.value==='known';value.parentElement!.hidden=state.value!=='known';};state.addEventListener('change',refresh);refresh();
}
export function readMagnitude(prefix:string):MagnitudeDraft{const state=$<HTMLSelectElement>(`#${prefix}-state`).value as MagnitudeDraft['state'];const d:MagnitudeDraft={state,unit:$<HTMLSelectElement>(`#${prefix}-unit`).value};if(state==='expression')d.expression=readExpression($(`#${prefix}-expression`));if(state==='known'){const text=$<HTMLInputElement>(`#${prefix}-value`).value.trim();if(!text)throw new Error('Enter a numerical magnitude.');d.value=Number(text);}return d;}
export function initializeVectors(store:DocumentStore,renderer:DiagramRenderer){
 const dialog=$<HTMLDialogElement>('#vector-dialog'),error=$('#vector-error');let draftStore=new DocumentStore(store.document),draftVectorId:string|undefined;let editingId:string|undefined;let saving=false;let angleTargetId:string|undefined;let angleDraft:ComponentAngleDefinition|undefined;let angleEdited=false;
 const value=(id:string)=>$<HTMLSelectElement>(id).value;const variable=(id?:string)=>store.document.semantics.variables.find(v=>v.id===id);
 function config():Configuration{return {kind:value('#vector-kind') as VectorChoice,interactionType:value('#vector-interaction') as Configuration['interactionType'],contactType:value('#vector-contact') as Configuration['contactType'],sourceId:value('#vector-from'),targetId:value('#vector-to'),separationId:value('#vector-separation')||undefined};}
 function options(id:string,entries:{id:string;name:string;disabled?:boolean}[],chosen?:string){const host=$<HTMLSelectElement>(id),old=chosen??host.value;host.replaceChildren();for(const entry of entries){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.name;if(entry.disabled)continue;option.disabled=false;host.append(option);}host.value=entries.some(e=>e.id===old && !e.disabled)?old:entries.find(e=>!e.disabled)?.id||'';}
 function context(c:Configuration,id?:string){const doc=draftStore.document,vector=doc.semantics.vectors.find(v=>v.id===(draftVectorId||id));return {doc,vector:vector||{id:'draft',variableId:'draft-magnitude',kind:c.kind==='force'?'force':c.kind==='field'?'field':c.kind==='separation'?'separation':'motion',objectId:c.targetId,motionType:c.kind} as PhysicalVector};}
 function synchronizeDraft(c:Configuration,reset:boolean){
  if(reset&&!editingId){draftStore=new DocumentStore(store.document);draftVectorId=undefined;}
  if(!eligibility(store.document,c))return;
  const quantity=c.kind==='force'?'force':c.kind==='field'?(c.interactionType==='gravitational'?'gravitationalField':'electricField'):c.kind==='separation'?'length':c.kind;
  const friction=c.kind==='force'&&c.interactionType==='contact'&&c.contactType==='ordinary'&&value('#vector-friction')!=='none'?value('#vector-friction') as 'static'|'kinetic':undefined;
  draftVectorId=saveVector(draftStore,{...c,id:draftVectorId||editingId,magnitude:{state:'unknown',unit:quantityUnits[quantity][0]},friction,frictionMagnitude:{state:'unknown',unit:'N'},coefficient:{state:'unknown',unit:'1'}});
 }
 function angleVector(){return draftStore.document.semantics.vectors.find(v=>v.id===(angleTargetId||draftVectorId));}
 function angleControls(){
  const doc=structuredClone(draftStore.document),c=doc.semantics.coordinateSystems[0],v=angleVector()||context(config(),editingId).vector;
  const m=doc.semantics.variables.find(m=>m.id===v.variableId);
  if(v.kind==='motion'&&m&&document.querySelector('#vector-state')){m.state=value('#vector-state') as Variable['state'];if(m.state==='known')m.value=Number($<HTMLInputElement>('#vector-value').value);}
  $('#component-angle-section').hidden=true;
  if(!c)return;
  const graphic=angleGraphic(doc,v),available=!!graphic && componentAngleGeometry(graphic,doc).length===2;
  const components=$<HTMLInputElement>('#vector-components').checked;
  $('#component-angle-section').hidden=!available||!components;
  $<HTMLFieldSetElement>('#component-angle-fields').disabled=!available||!components;
  for(const axis of ['x','y'] as const)$(`#component-angle-${axis}-symbol`).innerHTML=katex.renderToString(componentAngleSymbol(doc,v,axis),{throwOnError:false,trust:false});
  $('#component-angle-hint').textContent=c.dimensions!==2?'Component angles require a 2D coordinate system.':!available?'Component angles become available when the vector is resolved into two coordinate components (more than 10° from either axis).':!components?'Show coordinate components to display angles.':v.kind==='separation'?'Saving an angle keeps FROM fixed and moves TO to preserve the separation length.':v.role?'Saving an angle rotates the linked contact group together.':'Leave both fields blank for undefined angles. Changing one updates the complementary angle; Save vector applies the direction.';
 }
 function fillAngles(){const values=angleDraft?componentAngleValues({componentAngle:angleDraft} as PhysicalVector):undefined;for(const axis of ['x','y'] as const)$<HTMLInputElement>(`#component-angle-${axis}`).value=values?String(values[axis]):'';}
 for(const axis of ['x','y'] as const)$(`#component-angle-${axis}`).addEventListener('input',()=>{
  angleEdited=true;const input=$<HTMLInputElement>(`#component-angle-${axis}`),text=input.value.trim(),c=store.document.semantics.coordinateSystems[0];
  if(!text){angleDraft=undefined;fillAngles();return;}
  const number=Number(text);if(!Number.isFinite(number)||number<0||number>90)return;
  angleDraft={coordinateSystemId:c.id,axis,value:number};
  $<HTMLInputElement>(`#component-angle-${axis==='x'?'y':'x'}`).value=String(Number((90-number).toPrecision(12)));
 });
 $('#vector-components').addEventListener('change',angleControls);
 $('#vector-form').addEventListener('change',angleControls);
 $('#vector-form').addEventListener('input',event=>{if((event.target as HTMLElement).id==='vector-value')angleControls();});
 function refresh(resetMagnitude=false){const doc=store.document;
 const hasCoordinates=!!doc.semantics.coordinateSystems.length;$<HTMLInputElement>('#vector-components').disabled=!hasCoordinates;$('#components-label').hidden=!hasCoordinates;$('#components-hint').hidden=hasCoordinates;
let c=config();const pair=c.kind==='force'||c.kind==='field';$('#interaction-label').hidden=!pair;$('#contact-label').hidden=!(c.kind==='force' && c.interactionType==='contact');$('#from-label').hidden=['velocity','acceleration','displacement'].includes(c.kind);$('#from-label span').textContent=c.kind==='separation'?'FROM':'BY';$('#to-label span').textContent=c.kind==='field'?'AT':c.kind==='separation'?'TO':'ON';
 for(const option of $<HTMLSelectElement>('#vector-kind').options)option.disabled=!choiceAvailable(doc,option.value as VectorChoice);
 for(const option of $<HTMLSelectElement>('#vector-interaction').options)option.disabled=c.kind==='field'?!['gravitational','electric'].includes(option.value)||!anyEligible(doc,{kind:'field',interactionType:option.value as Configuration['interactionType']}):option.value==='contact'?!['ordinary','spring','cable'].some(type=>anyEligible(doc,{kind:'force',interactionType:'contact',contactType:type as Configuration['contactType']})):!anyEligible(doc,{kind:'force',interactionType:option.value as Configuration['interactionType']});
 for(const option of $<HTMLSelectElement>('#vector-interaction').options)option.hidden=c.kind==='field'&&option.disabled;
 if(pair && $<HTMLSelectElement>('#vector-interaction').selectedOptions[0]?.disabled){$<HTMLSelectElement>('#vector-interaction').value=Array.from($<HTMLSelectElement>('#vector-interaction').options).find(o=>!o.disabled)?.value||'';c=config();}
 for(const option of $<HTMLSelectElement>('#vector-contact').options)option.disabled=!anyEligible(doc,{kind:'force',interactionType:'contact',contactType:option.value as Configuration['contactType']});
 for(const option of $<HTMLSelectElement>('#vector-contact').options)option.hidden=option.disabled;
 if(c.interactionType==='contact' && $<HTMLSelectElement>('#vector-contact').selectedOptions[0]?.disabled){$<HTMLSelectElement>('#vector-contact').value=Array.from($<HTMLSelectElement>('#vector-contact').options).find(o=>!o.disabled)?.value||'';c=config();}
 options('#vector-from',doc.semantics.objects.map(o=>({id:o.id,name:o.name,disabled:!doc.semantics.objects.some(t=>eligibility(doc,{...c,sourceId:o.id,targetId:t.id},false))})));c=config();
 options('#vector-to',doc.semantics.objects.map(o=>({id:o.id,name:o.name,disabled:!eligibility(doc,{...c,targetId:o.id},false)})));c=config();
 $('#contact-label').hidden=!(c.kind==='force' && c.interactionType==='contact');
 const source=doc.semantics.objects.find(o=>o.id===c.sourceId);const needsSeparation=(c.kind==='force' && ['gravitational','electric'].includes(c.interactionType||'') && source?.category!=='planetSurface')||(c.kind==='field' && !['planetSurface','chargedPlate'].includes(source?.category||''));$('#separation-label').hidden=!needsSeparation;options('#vector-separation',needsSeparation?matchingSeparations(doc,c).map(v=>({id:v.id,name:variable(v.variableId)?.symbol||'Separation'})):[]);c=config();
 $('#friction-options').hidden=!(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary');const friction=value('#vector-friction')!=='none';for(const id of ['#friction-magnitude','#coefficient-enabled','#resultant-visible']){const el=$(id);(el.parentElement?.tagName==='LABEL'?el.parentElement:el).hidden=!friction;}$('#coefficient-fields').hidden=!friction || !$<HTMLInputElement>('#coefficient-enabled').checked;$('#volume-fields').hidden=!(c.kind==='force' && c.interactionType==='buoyant');
 const q=c.kind==='force'?'force':c.kind==='field'?(c.interactionType==='gravitational'?'gravitationalField':'electricField'):c.kind==='separation'?'length':c.kind;
 synchronizeDraft(c,resetMagnitude);
 if(resetMagnitude){showMagnitude($('#magnitude-fields'),'vector',q,undefined,context(c,editingId));showMagnitude($('#friction-magnitude'),'friction','force',undefined,context(c,editingId));showMagnitude($('#coefficient-fields'),'coefficient',value('#vector-friction')==='kinetic'?'kineticFriction':'staticFriction');showMagnitude($('#volume-fields'),'volume','volume',undefined,context(c,editingId));}
 for(const input of document.querySelectorAll<HTMLInputElement>('#vector-form input[required]'))input.disabled=!!input.closest('[hidden]');
 const ctx=context(c,editingId),previewVector={...ctx.vector};
 for(const prefix of ['vector','friction','volume'])updateExpressionVocabulary($(`#${prefix}-expression`),ctx.doc);
 const interaction=ctx.doc.semantics.interactions.find(i=>i.id===ctx.vector.interactionId),fv=ctx.doc.semantics.vectors.find(v=>v.interactionId===interaction?.id&&v.role==='friction'),mu=ctx.doc.semantics.variables.find(v=>v.id===interaction?.properties?.[value('#vector-friction')==='kinetic'?'kineticFriction':'staticFriction']);
 $('#friction-variables').hidden=!friction;$('#friction-variables').innerHTML=friction&&fv&&mu?katex.renderToString(`${vectorSymbol(ctx.doc,fv)},\\;${mu.symbol}`,{throwOnError:false,trust:false}):'';if(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary')previewVector.role=friction?'normal':undefined;
 const preview=$('#vector-preview');if(preview.dataset.custom!=='true' || (friction && preview.textContent?.replace(/\s/g,'').includes('F')))preview.innerHTML=katex.renderToString(vectorSymbol(ctx.doc,previewVector),{throwOnError:false,trust:false,maxExpand:1000});
 for(const [prefix,role]of [['friction','friction']] as const){const el=$(`#${prefix}-preview`);if(el.dataset.custom!=='true')el.innerHTML=katex.renderToString(vectorSymbol(ctx.doc,{...previewVector,role}),{throwOnError:false,trust:false,maxExpand:1000});}
 for(const prefix of ['coefficient','volume']){const el=$(`#${prefix}-preview`);if(el.dataset.custom!=='true' && previewVector.interactionId)el.innerHTML=katex.renderToString(interactionSymbol(ctx.doc,previewVector.interactionId,prefix==='volume'?'volume':value('#vector-friction')==='kinetic'?'kineticFriction':'staticFriction'),{throwOnError:false,trust:false,maxExpand:1000});}
 angleControls();$<HTMLButtonElement>('#save-vector').disabled=!eligibility(doc,c);}
 function refreshSafely(reset=false,clearError=true){try{refresh(reset);if(clearError)error.textContent='';}catch(e){error.textContent=(e as Error).message;$<HTMLButtonElement>('#save-vector').disabled=true;}}
 function open(id?:string){draftStore=new DocumentStore(store.document);draftVectorId=undefined;angleTargetId=id;angleEdited=false;const angleSource=store.document.semantics.vectors.find(v=>v.id===id);angleDraft=angleSource?.componentAngle?{...angleSource.componentAngle}:undefined;$<HTMLInputElement>('#vector-angles').checked=angleSource?.showAngles!==false;fillAngles();let v=store.document.semantics.vectors.find(v=>v.id===id);if(v?.role && v.role!=='normal'){v=store.document.semantics.vectors.find(n=>n.interactionId===v!.interactionId && n.role==='normal')||v;id=v.id;}editingId=id;$('#delete-vector').hidden=!id;error.textContent='';const i=store.document.semantics.interactions.find(i=>i.id===v?.interactionId),doc=store.document;
 $<HTMLSelectElement>('#vector-kind').value=v?.kind==='motion'?v.motionType!:v?.kind||(['force','field','separation','acceleration','velocity','displacement'].find(kind=>choiceAvailable(doc,kind as VectorChoice))||'separation');$<HTMLSelectElement>('#vector-kind').disabled=!!id;
 $<HTMLSelectElement>('#vector-interaction').value=i?.kind||v?.fieldType||'gravitational';$<HTMLSelectElement>('#vector-contact').value=i?.model==='spring'?'spring':i?.model==='cable'?'cable':'ordinary';
 options('#vector-from',doc.semantics.objects.map(o=>({id:o.id,name:o.name})),v?.fromId||v?.sourceId||i?.sourceId);options('#vector-to',doc.semantics.objects.map(o=>({id:o.id,name:o.name})),v?.toId||v?.objectId||doc.semantics.objects[1]?.id);options('#vector-separation',doc.semantics.vectors.filter(v=>v.kind==='separation').map(v=>({id:v.id,name:variable(v.variableId)?.symbol||'Separation'})),v?.separationId||i?.separationId);
 $<HTMLSelectElement>('#vector-friction').value=i?.friction||'none';$<HTMLInputElement>('#coefficient-enabled').checked=variable(i?.properties?.staticFriction||i?.properties?.kineticFriction)?.state==='known';$<HTMLInputElement>('#resultant-visible').checked=!!i?.resultantVisible;refresh(true);
 const g=v && vectorGraphic(doc,v.id),m=variable(v?.variableId);const q=m?.quantity|| (config().kind==='separation'?'length':config().kind==='force'?'force':config().kind==='field'?(config().interactionType==='gravitational'?'gravitationalField':'electricField'):config().kind);showMagnitude($('#magnitude-fields'),'vector',q,m,context(config(),editingId));
 const fv=doc.semantics.vectors.find(n=>n.interactionId===i?.id && n.role==='friction'),fg=fv && vectorGraphic(doc,fv.id);showMagnitude($('#friction-magnitude'),'friction','force',variable(fv?.variableId),{doc:draftStore.document,vector:fv||context(config(),editingId).vector});showMagnitude($('#coefficient-fields'),'coefficient',i?.friction==='kinetic'?'kineticFriction':'staticFriction',variable(i?.properties?.staticFriction||i?.properties?.kineticFriction));showMagnitude($('#volume-fields'),'volume','volume',variable(i?.properties?.volume),context(config(),editingId));$<HTMLInputElement>('#vector-components').checked=(angleSource && vectorGraphic(doc,angleSource.id)||g)?.showComponents!==false;$<HTMLInputElement>('#vector-visible').checked=g?.visible!==false;refresh();dialog.showModal();}
 function collection(){const modal=$<HTMLDialogElement>('#vector-collection'),host=$('#vector-list');host.replaceChildren();$('#vector-collection-error').textContent='';for(const vector of store.document.semantics.vectors){const m=variable(vector.variableId),g=vectorGraphic(store.document,vector.id),row=document.createElement('div');row.className='object-row';for(const label of ['Select','Edit',g?.visible===false?'Show':'Hide',vector.role?'Delete group':'Delete']){const button=document.createElement('button');button.setAttribute('aria-label',`${label} ${m?.symbol||vector.kind}`);button.append(document.createTextNode(label+' '));const math=document.createElement('span');math.innerHTML=katex.renderToString(m?.symbol||vector.kind,{throwOnError:false,trust:false,maxExpand:1000});button.append(math);button.addEventListener('click',async()=>{try{if(label==='Edit'){modal.close();open(vector.id);}else if(label==='Select'){modal.close();renderer.select(g?.id||null);}else{if(label==='Delete group')deleteInteraction(store,vector.interactionId!);else if(label==='Delete')deleteVector(store,vector.id);else if(g){store.transaction(()=>{g.visible=g.visible===false;if(vector.role==='resultant')store.document.semantics.interactions.find(i=>i.id===vector.interactionId)!.resultantVisible=g.visible;store.changed();});}await renderer.render();collection();}}catch(e){$('#vector-collection-error').textContent=(e as Error).message;}});row.append(button);}host.append(row);}if(!modal.open)modal.showModal();}
 for(const id of ['#vector-kind','#vector-interaction','#vector-contact'])$(id).addEventListener('change',()=>refreshSafely(true));for(const id of ['#vector-from','#vector-to','#vector-separation'])$(id).addEventListener('change',()=>refreshSafely(true));for(const id of ['#vector-friction','#coefficient-enabled'])$(id).addEventListener('change',()=>refreshSafely());
 $('[data-action="vector"]').addEventListener('click',()=>open());document.querySelectorAll('[data-action="vectors"]').forEach(button=>button.addEventListener('click',collection));$('#cancel-vector').addEventListener('click',()=>dialog.close());$('#close-vectors').addEventListener('click',()=> $<HTMLDialogElement>('#vector-collection').close());
 $('#vector-form').addEventListener('submit',async event=>{event.preventDefault();if(saving)return;saving=true;$<HTMLButtonElement>('#save-vector').disabled=true;try{const c=config(),d:VectorDraft={...c,id:editingId,magnitude:readMagnitude('vector'),visible:$<HTMLInputElement>('#vector-visible').checked};if(c.kind==='force' && c.interactionType==='contact' && c.contactType==='ordinary' && value('#vector-friction')!=='none'){d.friction=value('#vector-friction') as 'static'|'kinetic';d.frictionMagnitude=readMagnitude('friction');d.resultantVisible=$<HTMLInputElement>('#resultant-visible').checked;if($<HTMLInputElement>('#coefficient-enabled').checked)d.coefficient=readMagnitude('coefficient');}if(c.kind==='force' && c.interactionType==='buoyant')d.volume=readMagnitude('volume');const id=store.transaction(()=>{d.id=draftVectorId||editingId;const id=saveVector(draftStore,d);store.replace(draftStore.document);const targetId=angleTargetId && store.document.semantics.vectors.some(v=>v.id===angleTargetId)?angleTargetId:id;
 const target=store.document.semantics.vectors.find(v=>v.id===targetId)!,graphic=vectorGraphic(store.document,targetId)!;
 if(store.document.semantics.coordinateSystems.length){store.update(graphic.id,{showComponents:$<HTMLInputElement>('#vector-components').checked});target.showAngles=$<HTMLInputElement>('#vector-angles').checked;
 if(angleEdited)applyComponentAngle(store.document,targetId,angleDraft);store.changed();}return targetId;});await renderer.render();renderer.select(vectorGraphic(store.document,id)!.id);dialog.close();}catch(e){error.textContent=(e as Error).message;}finally{saving=false;if(dialog.open)refreshSafely(false,false);}});
 $('#delete-vector').addEventListener('click',async()=>{if(!editingId||saving)return;saving=true;try{const v=store.document.semantics.vectors.find(v=>v.id===editingId)!;if(v.role)deleteInteraction(store,v.interactionId!);else deleteVector(store,editingId);await renderer.render();dialog.close();}catch(e){error.textContent=(e as Error).message;}finally{saving=false;}});
 function availability(){$<HTMLButtonElement>('[data-action="vector"]').disabled=!(['force','field','separation','velocity','acceleration','displacement'] as VectorChoice[]).some(kind=>choiceAvailable(store.document,kind));}store.subscribe(availability);availability();return {open,collection};
}
