import {DocumentStore} from './model';
import {DiagramRenderer} from './renderer';
import {saveSeparation,deleteVector,vectorGraphic,type MagnitudeDraft} from './physics';
export function initializeVectors(store:DocumentStore,renderer:DiagramRenderer){
 const dialog=document.querySelector<HTMLDialogElement>('#vector-dialog')!,form=document.querySelector<HTMLFormElement>('#vector-form')!,error=document.querySelector('#vector-error')!;
 const select=(id:string)=>document.querySelector<HTMLSelectElement>(id)!;
 let editingId:string|undefined;
 function open(id?:string){editingId=id;error.textContent='';const v=store.document.semantics.vectors.find(v=>v.id===id),variable=store.document.semantics.variables.find(variable=>variable.id===v?.variableId);for(const selector of ['#vector-from','#vector-to']){const host=select(selector);host.replaceChildren();for(const object of store.document.semantics.objects){const option=document.createElement('option');option.value=object.id;option.textContent=object.name;host.append(option);}}select('#vector-from').value=v?.fromId||store.document.semantics.objects[0]?.id||'';select('#vector-to').value=v?.toId||store.document.semantics.objects[1]?.id||'';select('#vector-state').value=variable?.state||'unknown';document.querySelector<HTMLInputElement>('#vector-value')!.value=variable?.value===undefined?'':String(variable.value);document.querySelector<HTMLInputElement>('#vector-symbol')!.value=variable?.symbol||'';select('#vector-unit').value=variable?.unit||'m';dialog.showModal();}
 function collection(){const modal=document.querySelector<HTMLDialogElement>('#vector-collection')!,host=document.querySelector('#vector-list')!;host.replaceChildren();for(const vector of store.document.semantics.vectors){const variable=store.document.semantics.variables.find(v=>v.id===vector.variableId),g=vectorGraphic(store.document,vector.id);const row=document.createElement('div');row.className='object-row';for(const label of ['Select','Edit',g?.visible===false?'Show':'Hide','Delete']){const button=document.createElement('button');button.textContent=`${label} ${variable?.symbol||vector.kind}`;button.addEventListener('click',async()=>{try{if(label==='Edit'){modal.close();open(vector.id);}else if(label==='Select'){modal.close();renderer.select(g?.id||null);}else{if(label==='Delete')deleteVector(store,vector.id);else if(g)store.update(g.id,{visible:g.visible===false});await renderer.render();collection();}}catch(e){document.querySelector('#vector-collection-error')!.textContent=(e as Error).message;}});row.append(button);}host.append(row);}if(!modal.open)modal.showModal();}
 document.querySelector('[data-action="vector"]')!.addEventListener('click',()=>open());document.querySelector('[data-action="vectors"]')!.addEventListener('click',collection);document.querySelector('#cancel-vector')!.addEventListener('click',()=>dialog.close());document.querySelector('#close-vectors')!.addEventListener('click',()=>document.querySelector<HTMLDialogElement>('#vector-collection')!.close());
 form.addEventListener('submit',async event=>{event.preventDefault();try{const magnitude:MagnitudeDraft={symbol:document.querySelector<HTMLInputElement>('#vector-symbol')!.value||undefined,state:select('#vector-state').value as MagnitudeDraft['state'],unit:select('#vector-unit').value};if(magnitude.state==='known')magnitude.value=Number(document.querySelector<HTMLInputElement>('#vector-value')!.value);const id=saveSeparation(store,{id:editingId,fromId:select('#vector-from').value,toId:select('#vector-to').value,magnitude});await renderer.render();renderer.select(vectorGraphic(store.document,id)!.id);dialog.close();}catch(e){error.textContent=(e as Error).message;}});
 function availability(){document.querySelector<HTMLButtonElement>('[data-action="vector"]')!.disabled=store.document.semantics.objects.length<2;}store.subscribe(availability);availability();
 return {open,collection};
}
