import {describe,it,expect} from 'vitest';
import {newDocument,newGraphic,DocumentStore} from '../../src/model';
import {saveCoordinates,deleteCoordinates,graphicalComponents,coordinateBasis,COMPONENT_ANGLE_TOLERANCE_DEGREES} from '../../src/coordinates';
import {serializeDocument,parseDocument} from '../../src/persistence';
import {saveObject,objectDraft} from '../../src/objects';
import {saveVector} from '../../src/physics';
const frame={id:'frame',dimensions:2 as 1|2,origin:[100,200] as [number,number],angle:0,visible:true};
function graphic(angle:number){const g=newGraphic('arrow',newDocument());g.points=[0,0,100*Math.cos(angle*Math.PI/180),-100*Math.sin(angle*Math.PI/180)];return g;}
describe('angular presentation tolerance',()=>{
 it('uses a single ten-degree default',()=>expect(COMPONENT_ANGLE_TOLERANCE_DEGREES).toBe(10));
 for(const rotation of [0,37,-48,360,721])for(const axis of [0,90,180,270])for(const offset of [-10,-9.999,0,9.999,10])it(`suppresses ${rotation}/${axis}/${offset}`,()=>expect(graphicalComponents(graphic(rotation+axis+offset),{...frame,angle:rotation})).toEqual([]));
 for(const rotation of [0,37,-48])for(const axis of [0,90,180,270])for(const offset of [-10.001,10.001])it(`shows just outside ${rotation}/${axis}/${offset}`,()=>expect(graphicalComponents(graphic(rotation+axis+offset),{...frame,angle:rotation})).toHaveLength(2));
 it('signed projections sum to actual geometry and ignore origin',()=>{const g=graphic(220),before=structuredClone(g),parts=graphicalComponents(g,{...frame,angle:15});expect(parts.reduce((n,p)=>n+p.dx,0)).toBeCloseTo(g.points[2]);expect(parts.reduce((n,p)=>n+p.dy,0)).toBeCloseTo(g.points[3]);expect(graphicalComponents(g,{...frame,angle:15,origin:[-400,300]})).toEqual(parts);expect(g).toEqual(before);});
 it('reevaluates both vector and axis rotations without snapping',()=>{const g=graphic(35);expect(graphicalComponents(g,frame)).toHaveLength(2);expect(graphicalComponents(g,{...frame,angle:30})).toHaveLength(0);g.points=graphic(60).points;expect(graphicalComponents(g,{...frame,angle:30})).toHaveLength(2);});
 it('accounts for graphical transforms and zero vectors',()=>{const g=graphic(45);g.rotation=45;expect(graphicalComponents(g,frame)).toEqual([]);g.points=[0,0,0,0];expect(graphicalComponents(g,frame)).toEqual([]);});
 it('1D omits parallel and negligible perpendicular projections',()=>{for(const angle of [0,10,80,90,100,170,180,190,260,270,280,350])expect(graphicalComponents(graphic(angle),{...frame,dimensions:1})).toEqual([]);const [x]=graphicalComponents(graphic(135),{...frame,dimensions:1});expect(x.axis).toBe('x');expect(x.dx).toBeCloseTo(-Math.sqrt(5000));expect(x.dy).toBeCloseTo(0);});
 it('uses mathematical counterclockwise angles in screen space',()=>{const basis=coordinateBasis(90);expect(basis.x[0]).toBeCloseTo(0);expect(basis.x[1]).toBeCloseTo(-1);expect(basis.y[0]).toBeCloseTo(-1);expect(basis.x[0]*basis.y[0]+basis.x[1]*basis.y[1]).toBeCloseTo(0);});
});
describe('coordinate identity and persistence',()=>{
 it('prevents duplicates and round-trips all settings',()=>{const s=new DocumentStore();const id=saveCoordinates(s,{...frame,id:undefined,angle:37,visible:false});expect(()=>saveCoordinates(s,{...frame,id:undefined})).toThrow('Only one');const before=structuredClone(s.document);expect(parseDocument(serializeDocument(before))).toEqual(before);saveCoordinates(s,{...s.document.semantics.coordinateSystems[0],dimensions:1});expect(s.document.semantics.coordinateSystems[0]).toMatchObject({id,angle:37,origin:[100,200],visible:false});const bad=structuredClone(s.document);bad.semantics.coordinateSystems.push({...frame,id:'second'});expect(()=>parseDocument(serializeDocument(bad))).toThrow('only one');});
 it('legacy files acquire no implicit coordinate definition',()=>{const d=newDocument();expect(parseDocument(serializeDocument(d)).semantics.coordinateSystems).toEqual([]);});
 it('deletion preserves physical vectors, properties, and component variables',()=>{const s=new DocumentStore(),o=saveObject(s,{...objectDraft(s),name:'Book'});const v=saveVector(s,{kind:'velocity',targetId:o,magnitude:{state:'unknown',unit:'m/s'}});saveCoordinates(s,{...frame,id:undefined});const g=s.document.presentation.elements.find(g=>g.vectorId===v)!;g.showComponents=true;const semantics=structuredClone(s.document.semantics);deleteCoordinates(s);expect(s.document.semantics.vectors).toEqual(semantics.vectors);expect(s.document.semantics.objects).toEqual(semantics.objects);expect(s.document.semantics.variables).toEqual(semantics.variables);expect(s.document.semantics.components).toEqual([]);expect(s.document.presentation.elements.find(n=>n.id===g.id)!.showComponents).toBeUndefined();});
 it('rejects nonfinite angles and malformed visibility in saved files',()=>{const s=new DocumentStore();expect(()=>saveCoordinates(s,{...frame,id:undefined,angle:NaN})).toThrow();saveCoordinates(s,{...frame,id:undefined});const d=JSON.parse(serializeDocument(s.document));d.semantics.coordinateSystems[0].visible='no';expect(()=>parseDocument(JSON.stringify(d))).toThrow('visibility');});
});
