import {it,expect} from 'vitest';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft,objectDraft,deleteObject,intrinsicProperties} from '../../src/objects';
import {saveVector,deleteVector,deleteInteraction,saveSeparation} from '../../src/physics';
import {saveCoordinates,deleteCoordinates} from '../../src/coordinates';
import {serializeDocument,parseDocument} from '../../src/persistence';
import {assertExpressions} from '../../src/expressions';
const unknown={state:'unknown' as const,unit:'N'};
function fixture(){const s=new DocumentStore(),a=saveObject(s,{...presetDraft('ordinary'),name:'Ramp'}),b=saveObject(s,{...presetDraft('ordinary'),name:'Book'}),n=saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:a,targetId:b,friction:'static',magnitude:unknown,coefficient:{state:'known',unit:'1',value:.3}});return {s,a,b,n};}
it('static/kinetic characterization retains coefficient ID, value, and expression references',()=>{
 const {s,a,b,n}=fixture(),mu=s.document.semantics.interactions[0].properties!.staticFriction,f=s.document.semantics.vectors.find(v=>v.role==='friction')!;
 const expression={type:'mathed' as const,expression:[{type:'variable' as const,id:mu},{type:'variable' as const,id:s.document.semantics.vectors.find(v=>v.id===n)!.variableId}]};
 for(const friction of ['kinetic','static'] as const){saveVector(s,{id:n,kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:a,targetId:b,friction,magnitude:unknown,coefficient:{state:'known',unit:'1',value:.3},frictionMagnitude:{state:'expression',unit:'N',expression}});const key=friction==='static'?'staticFriction':'kineticFriction';expect(s.document.semantics.interactions[0].properties).toEqual({[key]:mu});expect(s.document.semantics.variables.find(v=>v.id===mu)).toMatchObject({quantity:key,value:.3,symbol:friction==='static'?'\\mu_{s,R,B}':'\\mu_{k,R,B}'});expect(s.document.semantics.variables.find(v=>v.id===f.variableId)!.expression).toEqual(expression);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);}
});
for(const category of ['spring','fluid','planetSurface','chargedPlate'] as const)it(`${category} intrinsic variables exist immediately and retain IDs on save/load`,()=>{
 const s=new DocumentStore(),o=saveObject(s,{...presetDraft(category),properties:{}}),keys=intrinsicProperties[category]!;expect(Object.keys(s.document.semantics.objects[0].properties!)).toEqual(keys);
 const ids={...s.document.semantics.objects[0].properties};saveObject(s,objectDraft(s,o));expect(s.document.semantics.objects[0].properties).toEqual(ids);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);
 const legacy=structuredClone(s.document);legacy.semantics.variables=[];legacy.semantics.objects[0].properties={};const loaded=parseDocument(JSON.stringify(legacy));expect(Object.keys(loaded.semantics.objects[0].properties!)).toEqual(keys);expect(parseDocument(JSON.stringify(loaded))).toEqual(loaded);
});
it('ordinary and point properties remain optional',()=>{const s=new DocumentStore();saveObject(s,presetDraft('ordinary'));saveObject(s,presetDraft('spatialPoint'));expect(s.document.semantics.variables).toEqual([]);});
it('object cascade removes owned groups, fields, separation dependencies, components and presentation atomically',()=>{
 const {s,a,b,n}=fixture(),mu=s.document.semantics.interactions[0].properties!.staticFriction;
 const spring=saveObject(s,presetDraft('spring'));saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:mu}}});
 saveCoordinates(s,{dimensions:2,origin:[0,0],angle:0});const componentId=crypto.randomUUID();s.document.semantics.variables.push({id:componentId,symbol:'n_x',state:'unknown',unit:'N'});s.document.semantics.components.push({id:'component',vectorId:n,variableId:componentId,coordinateSystemId:s.document.semantics.coordinateSystems[0].id,axis:'x'});s.load(s.document);
 const before=structuredClone(s.document);deleteObject(s,a);expect(s.document.semantics.objects.map(o=>o.id)).toEqual([b,spring]);expect(s.document.semantics.interactions).toEqual([]);expect(s.document.semantics.components).toEqual([]);expect(s.document.semantics.vectors).toHaveLength(1);expect(s.document.semantics.variables.find(v=>v.ownerVectorId)).toMatchObject({state:'unknown'});assertExpressions(s.document);const after=structuredClone(s.document);s.undo();expect(s.document).toEqual(before);s.redo();expect(s.document).toEqual(after);expect(parseDocument(serializeDocument(s.document))).toEqual(after);
});
it('deleting a single grouped arrow deletes the whole contact group and clears external definitions',()=>{const {s,b,n}=fixture(),mu=s.document.semantics.interactions[0].properties!.staticFriction;const motion=saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:mu}}});s.load(s.document);const before=structuredClone(s.document);deleteVector(s,n);expect(s.document.semantics.interactions).toEqual([]);expect(s.document.semantics.vectors.map(v=>v.id)).toEqual([motion]);expect(s.document.semantics.variables.find(v=>v.ownerVectorId===motion)!.expression).toBeUndefined();s.undo();expect(s.document).toEqual(before);deleteInteraction(s,s.document.semantics.interactions[0].id);expect(s.document.semantics.vectors.map(v=>v.id)).toEqual([motion]);});
it('separation cascade deletes dependent inverse-square force and leaves unrelated contact intact',()=>{const {s,a,b}=fixture(),sep=saveSeparation(s,{fromId:a,toId:b,magnitude:{state:'unknown',unit:'m'}});saveVector(s,{kind:'force',interactionType:'gravitational',sourceId:a,targetId:b,separationId:sep,magnitude:unknown});deleteVector(s,sep);expect(s.document.semantics.interactions.map(i=>i.kind)).toEqual(['contact']);expect(s.document.semantics.vectors).toHaveLength(3);assertExpressions(s.document);});
it('removing a property clears dependent definitions without destroying their semantic identity',()=>{const s=new DocumentStore(),o=saveObject(s,{...presetDraft('ordinary'),name:'Rock',properties:{mass:{state:'unknown',unit:'kg'}}}),mass=s.document.semantics.objects[0].properties!.mass,v=saveVector(s,{kind:'velocity',targetId:o,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:mass}}});saveObject(s,{...objectDraft(s,o),properties:{}});expect(s.document.semantics.variables.find(n=>n.ownerVectorId===v)).toMatchObject({state:'unknown'});assertExpressions(s.document);});
it('coordinate removal deletes component variables and clears references while preserving vectors',()=>{const {s,b,n}=fixture();saveCoordinates(s,{dimensions:2,origin:[0,0],angle:0});s.document.semantics.variables.push({id:'component-var',symbol:'N_x'});s.document.semantics.components.push({id:'component',vectorId:n,variableId:'component-var',coordinateSystemId:s.document.semantics.coordinateSystems[0].id,axis:'x'});const v=saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'expression',unit:'m/s',expression:{type:'reference',id:'component-var'}}});deleteCoordinates(s);expect(s.document.semantics.variables.some(v=>v.id==='component-var')).toBe(false);expect(s.document.semantics.variables.find(n=>n.ownerVectorId===v)!.state).toBe('unknown');expect(s.document.semantics.vectors).toHaveLength(4);});
it('property removal invalidates a surviving sibling definition while retaining its identity',()=>{const s=new DocumentStore(),o=saveObject(s,{...presetDraft('ordinary'),name:'Rock',properties:{charge:{state:'unknown',unit:'C'},mass:{state:'unknown',unit:'kg'}}});const d=objectDraft(s,o),mass=d.properties!.mass!.id!,charge=d.properties!.charge!.id!;d.properties!.mass!.state='expression';d.properties!.mass!.expression={type:'reference',id:charge};saveObject(s,d);const edited=objectDraft(s,o);delete edited.properties!.charge;saveObject(s,edited);expect(s.document.semantics.variables).toHaveLength(1);expect(s.document.semantics.variables[0]).toMatchObject({id:mass,state:'unknown'});expect(s.document.semantics.variables[0].expression).toBeUndefined();});
