import {it,expect} from 'vitest';
import {DocumentStore} from '../../src/model';
import {saveObject,presetDraft,objectDraft} from '../../src/objects';
import {saveVector,deleteVector,saveSeparation,deleteInteraction} from '../../src/physics';
import {contextualReferences,expressionLatex,parseTokens,validateExpression} from '../../src/expressions';
import {parseDocument,serializeDocument} from '../../src/persistence';
import type {Expression} from '../../src/semantics';
it('student expression references synchronize actual symbols and clear dependent definitions on removal',()=>{
 const s=new DocumentStore(),planet=saveObject(s,presetDraft('planetSurface')),book=saveObject(s,{name:'Book',representation:'circle',showName:true,showProperties:true,properties:{mass:{symbol:'m_7',state:'unknown',unit:'kg'}}});const mass=s.document.semantics.objects.find(o=>o.id===book)!.properties!.mass,g=s.document.semantics.objects.find(o=>o.id===planet)!.properties!.gravity;
 const e:Expression={type:'binary',op:'*',left:{type:'reference',id:mass},right:{type:'reference',id:g}};const id=saveVector(s,{kind:'force',interactionType:'gravitational',sourceId:planet,targetId:book,magnitude:{state:'expression',unit:'N',expression:e}});expect(contextualReferences(s.document,s.document.semantics.vectors[0]).sort()).toEqual([mass,g].sort());
 saveObject(s,{...objectDraft(s,book),name:'Novel',properties:{mass:{symbol:'M',state:'known',unit:'kg',value:2}}});expect(expressionLatex(e,s.document)).toContain('M');expect(s.document.semantics.variables.find(v=>v.ownerVectorId===id)!.expression).toEqual(e);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);
 saveObject(s,{...objectDraft(s,book),properties:{}});expect(s.document.semantics.variables.find(v=>v.ownerVectorId===id)).toMatchObject({state:'unknown'});expect(s.document.semantics.variables.find(v=>v.ownerVectorId===id)!.expression).toBeUndefined();deleteVector(s,id);
});
it('point field accepts document-wide references while preserving identities',()=>{
 const s=new DocumentStore(),source=saveObject(s,{name:'Source',representation:'point',showName:true,showProperties:true,properties:{charge:{symbol:'Q',state:'unknown',unit:'C'}}}),point=saveObject(s,{...presetDraft('spatialPoint'),properties:{charge:{symbol:'q',state:'unknown',unit:'C'}}});const sep=saveSeparation(s,{fromId:source,toId:point,magnitude:{state:'known',unit:'m',value:3}});const id=saveVector(s,{kind:'field',interactionType:'electric',sourceId:source,targetId:point,separationId:sep,magnitude:{state:'unknown',unit:'N/C'}}),v=s.document.semantics.vectors.find(v=>v.id===id)!;const pointCharge=s.document.semantics.objects.find(o=>o.id===point)!.properties!.charge;expect(contextualReferences(s.document,v)).not.toContain(pointCharge);expect(contextualReferences(s.document,v)).toContain('constant:ke');saveVector(s,{id,kind:'field',interactionType:'electric',sourceId:source,targetId:point,separationId:sep,magnitude:{state:'expression',unit:'N/C',expression:{type:'reference',id:pointCharge}}});expect(s.document.semantics.variables.find(m=>m.id===v.variableId)!.expression).toEqual({type:'reference',id:pointCharge});
});
it('bounded grammar accepts arithmetic, negation, powers, pi and absolute value without evaluating',()=>{
 const e=parseTokens([{type:'operation',value:'abs'},{type:'operation',value:'('},{type:'operation',value:'-'},{type:'reference',id:'x'},{type:'operation',value:')'},{type:'operation',value:'/'},{type:'operation',value:'pi'},{type:'operation',value:'^'},{type:'number',value:2}]);validateExpression(e,new Set(['x']));expect(e.type).toBe('binary');expect(()=>parseTokens([{type:'operation',value:'+'}])).toThrow();expect(()=>validateExpression({type:'reference',id:'unknown'},new Set())).toThrow(/unavailable/);
});
it('referenced contact magnitudes cannot be deleted through their interaction group',()=>{
 const s=new DocumentStore(),a=saveObject(s,{name:'A',representation:'circle',showName:true,showProperties:true}),b=saveObject(s,{name:'B',representation:'circle',showName:true,showProperties:true});const id=saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:a,targetId:b,friction:'static',magnitude:{state:'unknown',unit:'N'},frictionMagnitude:{state:'unknown',unit:'N'}});const normal=s.document.semantics.vectors.find(v=>v.id===id)!,friction=s.document.semantics.vectors.find(v=>v.role==='friction')!;const i=s.document.semantics.interactions[0];expect(i).toBeDefined();expect(normal.variableId).not.toBe(friction.variableId);deleteInteraction(s,i.id);expect(s.document.semantics.vectors).toHaveLength(0);
});
