import {it,expect} from 'vitest';
import {DocumentStore,newDocument,documentContent} from '../../src/model';
import {saveObject,deleteObject,objectDraft,presetDraft,objectGraphic} from '../../src/objects';
import {saveVector,deleteVector,deleteInteraction,vectorGraphic} from '../../src/physics';
import {saveCoordinates,deleteCoordinates} from '../../src/coordinates';
import {parseDocument,serializeDocument} from '../../src/persistence';
function fixture(){const s=new DocumentStore(),earth=saveObject(s,presetDraft('planetSurface')),rock=saveObject(s,{...objectDraft(s),name:'Rock'}),table=saveObject(s,{...objectDraft(s),name:'Table'});const d={kind:'force' as const,interactionType:'gravitational' as const,sourceId:earth,targetId:rock,magnitude:{state:'unknown' as const,unit:'N'}};const weight=saveVector(s,d);saveVector(s,d);saveCoordinates(s,{dimensions:2,angle:37,origin:[300,200],reverseX:true,reverseY:false,visible:true});s.load(s.document);return {s,earth,rock,table,weight,d};}
function roundtrip(s:DocumentStore,edit:()=>unknown){const before=structuredClone(s.document);edit();const after=structuredClone(s.document);expect(s.canUndo).toBe(true);expect(s.undo()).toBe(true);expect(s.document).toEqual(before);expect(s.redo()).toBe(true);expect(s.document).toEqual(after);expect(parseDocument(serializeDocument(s.document))).toEqual(after);}
it('creation and deletion restore complete IDs, relationships and disambiguated symbols',()=>{const {s,rock,weight,d}=fixture();roundtrip(s,()=>saveVector(s,d));roundtrip(s,()=>deleteVector(s,weight));const before=structuredClone(s.document);deleteObject(s,rock);expect(s.document.semantics.objects.some(o=>o.id===rock)).toBe(false);s.undo();expect(s.document).toEqual(before);expect(new Set(s.document.semantics.variables.filter(v=>v.ownerVectorId).map(v=>v.symbol)).size).toBe(2);s.redo();expect(s.document.semantics.vectors).toEqual([]);});
it('all persisted object edits and label geometry round trip in a single modal change',()=>{const {s,rock}=fixture();roundtrip(s,()=>{const draft=objectDraft(s,rock);draft.name='Pebble';draft.representation='rectangle';draft.showName=false;draft.properties!.mass={state:'known',value:2.5,unit:'kg'};saveObject(s,draft);});const g=objectGraphic(s,rock)!;roundtrip(s,()=>s.update(g.id,{x:180,y:240,rotation:45,scaleX:2,label:{...g.label!,offsetX:80,offsetY:-20}}));});
it('vector participants, physical magnitudes and component/label settings restore together',()=>{const {s,weight,table,d}=fixture();roundtrip(s,()=>s.transaction(()=>{saveVector(s,{...d,id:weight,magnitude:{state:'known',unit:'N',value:5}});const g=vectorGraphic(s.document,weight)!;s.update(g.id,{points:[0,0,60,-140],showComponents:false,label:{...g.label!,offsetX:35,offsetY:20}});}));});
it('linked contact deletion restores its complete interaction, components and variables',()=>{const {s,table,rock}=fixture();const id=saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:table,targetId:rock,friction:'static',resultantVisible:true,magnitude:{state:'unknown',unit:'N'},frictionMagnitude:{state:'unknown',unit:'N'}});s.load(s.document);const group=s.document.semantics.vectors.find(v=>v.id===id)!.interactionId!;roundtrip(s,()=>deleteInteraction(s,group));});
it('every coordinate property and dependent graphical setting survives deletion/undo',()=>{const {s,weight}=fixture();roundtrip(s,()=>saveCoordinates(s,{...s.document.semantics.coordinateSystems[0],dimensions:1,angle:123,origin:[450,280],reverseX:false,reverseY:true,visible:false}));s.update(vectorGraphic(s.document,weight)!.id,{showComponents:false});s.load(s.document);roundtrip(s,()=>deleteCoordinates(s));});
it('50 gesture updates form one bounded edit and cancellation restores the original state',()=>{const {s,rock}=fixture(),g=objectGraphic(s,rock)!,before=structuredClone(s.document);s.beginTransaction();for(let i=1;i<=50;i++)s.update(g.id,{x:i});expect(s.canUndo).toBe(false);s.endTransaction();const after=structuredClone(s.document);s.undo();expect(s.document).toEqual(before);expect(s.canUndo).toBe(false);s.redo();expect(s.document).toEqual(after);s.beginTransaction();s.update(g.id,{x:999});s.cancelTransaction();expect(s.document).toEqual(after);expect(s.inTransaction).toBe(false);});
it('nested modal changes, exceptions and no-op saves do not create spurious edits',()=>{const {s,rock}=fixture();saveObject(s,objectDraft(s,rock));saveCoordinates(s,{...s.document.semantics.coordinateSystems[0]});s.changed();expect(s.canUndo).toBe(false);const before=structuredClone(s.document);expect(()=>s.transaction(()=>{s.update(objectGraphic(s,rock)!.id,{x:999});throw new Error('failed');})).toThrow('failed');expect(documentContent(s.document)).toBe(documentContent(before));expect(s.canUndo).toBe(false);s.transaction(()=>s.transaction(()=>s.update(objectGraphic(s,rock)!.id,{x:80})));s.undo();expect(s.canUndo).toBe(false);});
it('saved-state comparison survives undo, redo, save and abandoned branches',()=>{const s=new DocumentStore();expect(s.dirty).toBe(false);saveObject(s,{...objectDraft(s),name:'Rock'});expect(s.dirty).toBe(true);s.markSaved();expect(s.dirty).toBe(false);expect(s.canUndo).toBe(true);s.undo();expect(s.dirty).toBe(true);s.redo();expect(s.dirty).toBe(false);const id=s.document.semantics.objects[0].id;saveObject(s,{...objectDraft(s,id),name:'Pebble'});expect(s.dirty).toBe(true);s.undo();expect(s.dirty).toBe(false);saveObject(s,{...objectDraft(s,id),name:'Stone'});expect(s.canRedo).toBe(false);expect(s.dirty).toBe(true);});
it('opening a file resets history/baseline; snapshots cannot be mutated through current document',()=>{const {s,rock}=fixture();s.update(objectGraphic(s,rock)!.id,{x:80});s.load(newDocument());expect(s.canUndo).toBe(false);expect(s.canRedo).toBe(false);expect(s.dirty).toBe(false);const start=structuredClone(s.document);saveObject(s,{...objectDraft(s),name:'Rock'});s.undo();s.document.metadata.title='mutated';s.redo();s.undo();expect(s.document).toEqual(start);});
it('history retains 100 completed edits without caches and ignores timestamp/semantic record order',()=>{const {s,rock}=fixture(),id=objectGraphic(s,rock)!.id;for(let i=1;i<=110;i++)s.update(id,{x:i});let count=0;while(s.undo())count++;expect(count).toBe(100);expect(objectGraphic(s,rock)!.x).toBe(10);while(s.redo()){}expect(objectGraphic(s,rock)!.x).toBe(110);const before=documentContent(s.document);s.document.semantics.variables.reverse();s.document.metadata.updatedAt='different';expect(documentContent(s.document)).toBe(before);});

it('supported motion and separation participant edits retain their identities across history',()=>{const {s,rock,table,earth}=fixture();const motion=saveVector(s,{kind:'velocity',targetId:rock,magnitude:{state:'unknown',unit:'m/s'}}),separation=saveVector(s,{kind:'separation',sourceId:rock,targetId:table,magnitude:{state:'unknown',unit:'m'}});s.load(s.document);roundtrip(s,()=>saveVector(s,{id:motion,kind:'velocity',targetId:table,magnitude:{state:'known',unit:'m/s',value:3}}));roundtrip(s,()=>saveVector(s,{id:separation,kind:'separation',sourceId:earth,targetId:table,magnitude:{state:'unknown',unit:'m'}}));});
it('missing backwards-compatible coordinate flags remain a no-op when saving their defaults',()=>{const s=new DocumentStore();saveCoordinates(s,{dimensions:2,angle:0,origin:[200,200]});s.load(s.document);saveCoordinates(s,{...s.document.semantics.coordinateSystems[0],reverseX:false,reverseY:false});expect(s.canUndo).toBe(false);expect(s.dirty).toBe(false);});
