import {it,expect} from 'vitest';
import {DocumentStore,newGraphic} from '../../src/model';
import {labelPosition} from '../../src/geometry';
import {saveObject,objectDraft,objectGraphic} from '../../src/objects';
import {saveVector,vectorGraphic,displayedVector} from '../../src/physics';
import {parseDocument,serializeDocument} from '../../src/persistence';
const make=(s:DocumentStore,name:string)=>saveObject(s,{name,representation:'circle',showName:true,showProperties:true});
it('new object labels center at attachment and persist adjustments through rename and reopen',()=>{const s=new DocumentStore(),id=make(s,'Book'),g=objectGraphic(s,id)!;expect(labelPosition(g,100,20).x).toBe(g.x-50);s.update(g.id,{label:{...g.label!,offsetX:51,offsetY:70}});saveObject(s,{...objectDraft(s,id),name:'Novel'});expect(objectGraphic(s,id)!.label).toEqual({...g.label!,offsetX:51,offsetY:70});expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});
it('vector label default follows tip across rotation and manual offsets survive geometry changes',()=>{const s=new DocumentStore(),g=newGraphic('arrow',s.document);g.label={placement:'vectorTip',showName:false,showProperties:true,offsetX:0,offsetY:0};g.points=[0,0,100,0];const before=labelPosition(g,30,20);expect(before.x).toBeGreaterThan(g.x+100);g.points=[0,0,0,-200];const after=labelPosition(g,30,20);expect(after.y).toBeLessThan(g.y-200);g.label.offsetX=17;g.label.offsetY=-9;expect(labelPosition(g,30,20)).toEqual({x:after.x+17,y:after.y-9});g.rotation=30;expect(Number.isFinite(labelPosition(g,50,25).x)).toBe(true);});
it('historic label offsets stay in their original frame',()=>{const s=new DocumentStore(),g=newGraphic('arrow',s.document);g.label={showName:false,showProperties:true,offsetX:23,offsetY:44};expect(labelPosition(g,100,20)).toEqual({x:g.x+23,y:g.y+44});});
it('physical editing leaves component geometry and independent magnitudes untouched',()=>{const s=new DocumentStore(),book=make(s,'Book'),table=make(s,'Table');const d={kind:'force' as const,interactionType:'contact' as const,contactType:'ordinary' as const,sourceId:table,targetId:book,friction:'static' as const,resultantVisible:true,magnitude:{state:'known' as const,unit:'N',value:10},frictionMagnitude:{state:'known' as const,unit:'N',value:4}};const id=saveVector(s,{...d,angle:-60,length:150,frictionLength:60});const before=s.document.presentation.elements.filter(g=>g.vectorId).map(g=>g.points);saveVector(s,{...d,id});expect(s.document.presentation.elements.filter(g=>g.vectorId).map(g=>g.points)).toEqual(before);const vectors=s.document.semantics.vectors,n=vectors.find(v=>v.role==='normal')!,f=vectors.find(v=>v.role==='friction')!,r=vectors.find(v=>v.role==='resultant')!;const ng=vectorGraphic(s.document,n.id)!,fg=vectorGraphic(s.document,f.id)!,rg=vectorGraphic(s.document,r.id)!;s.update(ng.id,{points:[0,0,80,-60]});s.update(fg.id,{points:[0,0,40,0]});const fp=displayedVector(s.document,f,fg)!.points,rp=displayedVector(s.document,r,rg)!.points;expect(fp[2]*80+fp[3]*-60).toBeCloseTo(0);expect(rp[2]).toBeCloseTo(80+fp[2]);expect(rp[3]).toBeCloseTo(-60+fp[3]);expect(s.document.semantics.variables.find(v=>v.id===n.variableId)!.value).toBe(10);expect(s.document.semantics.variables.find(v=>v.id===f.variableId)!.value).toBe(4);});
it('historic generic normal notation corrects without changing IDs or unrelated custom symbols',()=>{const s=new DocumentStore(),book=make(s,'Book'),table=make(s,'Table');saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:table,targetId:book,friction:'static',magnitude:{symbol:'F_{T,B}',state:'unknown',unit:'N'}});const normal=s.document.semantics.vectors.find(v=>v.role==='normal')!,variable=s.document.semantics.variables.find(v=>v.id===normal.variableId)!;expect(variable.symbol).toBe('N_{T,B}');variable.generatedSymbol=false;variable.symbol='F_{T,B}';const resultant=s.document.semantics.vectors.find(v=>v.role==='resultant')!;s.document.semantics.variables.find(v=>v.id===resultant.variableId)!.symbol='F_{T,B,2}';const reopened=parseDocument(serializeDocument(s.document));expect(reopened.semantics.variables.find(v=>v.id===normal.variableId)!.symbol).toBe('N_{T,B}');expect(reopened.semantics.variables.find(v=>v.id===resultant.variableId)!.symbol).toBe('F_{T,B}');expect(reopened.semantics.vectors).toEqual(s.document.semantics.vectors);variable.symbol='R_{authored}';expect(parseDocument(serializeDocument(s.document)).semantics.variables.find(v=>v.id===normal.variableId)!.symbol).toBe('R_{authored}');});

it('historical automatic defaults adopt tip placement without rewriting saved offsets',()=>{const s=new DocumentStore(),g=newGraphic('arrow',s.document);g.vectorId='legacy-vector';g.label={showName:false,showProperties:true,offsetX:12,offsetY:12};g.points=[0,0,100,0];const old=structuredClone(g.label);expect(labelPosition(g,20,20).x).toBeGreaterThan(g.x+100);expect(g.label).toEqual(old);});
