import {it,expect} from 'vitest';
import {DocumentStore} from '../../src/model';
import {saveObject,deleteObject,objectDraft,presetDraft} from '../../src/objects';
import {saveVector,saveSeparation} from '../../src/physics';
import {synchronizeSymbols,vectorLatex} from '../../src/naming';
import {parseDocument,serializeDocument} from '../../src/persistence';
import {expressionLatex} from '../../src/expressions';
import {physicalConstants} from '../../src/constants';
const unknown={state:'unknown' as const,unit:'N'};
const make=(s:DocumentStore,name:string)=>saveObject(s,{name,representation:'circle',showName:true,showProperties:true,properties:{mass:{state:'unknown',unit:'kg'}}});
const symbol=(s:DocumentStore,id:string)=>s.document.semantics.variables.find(v=>v.id===id)!.symbol;
it('properties use assigned abbreviations and collision changes keep every semantic reference',()=>{
 const s=new DocumentStore(),earth=make(s,'Earth'),mass=s.document.semantics.objects[0].properties!.mass;expect(symbol(s,mass)).toBe('m_{E}');const emu=make(s,'Emu');expect(symbol(s,mass)).toBe('m_{Ea}');expect(symbol(s,s.document.semantics.objects[1].properties!.mass)).toBe('m_{Em}');
 const sep=saveSeparation(s,{fromId:earth,toId:emu,magnitude:{state:'unknown',unit:'m'}}),vector=s.document.semantics.vectors[0],ids=[vector.id,vector.variableId];
 saveObject(s,{...objectDraft(s,emu),name:'Book'});expect(symbol(s,vector.variableId)).toBe('r_{Ea,B}');expect([s.document.semantics.vectors[0].id,s.document.semantics.vectors[0].variableId]).toEqual(ids);expect(s.document.semantics.vectors[0].id).toBe(sep);
 const before=structuredClone(s.document);s.document.semantics.objects.reverse();synchronizeSymbols(s.document);expect(s.document.semantics.variables).toEqual(before.semantics.variables);
});
it('identical names are deterministic across array ordering and preserve suffixes after deletion',()=>{const s=new DocumentStore();make(s,'Ball');make(s,'Ball');const before=structuredClone(s.document);s.document.semantics.objects.reverse();synchronizeSymbols(s.document);expect(s.document.semantics.objects.map(o=>o.abbreviation).sort()).toEqual(before.semantics.objects.map(o=>o.abbreviation).sort());expect(new Set(s.document.semantics.objects.map(o=>o.abbreviation)).size).toBe(2);});
it('single/multiple springs and gravitational environments get conventional distinct notation',()=>{
 const s=new DocumentStore(),a=saveObject(s,{...presetDraft('spring'),name:'Spring',properties:{springConstant:{state:'unknown',unit:'N/m'},extension:{state:'unknown',unit:'m'}}});expect(s.document.semantics.variables.map(v=>v.symbol)).toEqual(['k','\\Delta x']);saveObject(s,{...presetDraft('spring'),name:'Elastic',properties:{springConstant:{state:'unknown',unit:'N/m'}}});expect(symbol(s,s.document.semantics.objects.find(o=>o.id===a)!.properties!.springConstant)).toBe('k_{S}');
 saveObject(s,presetDraft('planetSurface'));expect(s.document.semantics.variables.some(v=>v.symbol==='g')).toBe(true);saveObject(s,{...presetDraft('planetSurface'),name:'Mars'});expect(s.document.semantics.variables.filter(v=>v.quantity==='gravity').map(v=>v.symbol).sort()).toEqual(['g_{M}','g_{P}']);expect(physicalConstants['constant:ke'].symbol).toBe('k_e');expect(physicalConstants['constant:G'].symbol).toBe('G');
});
it('all supported object properties default automatically without creating absent quantities',()=>{const s=new DocumentStore();saveObject(s,{...presetDraft('spatialPoint'),name:'Particle',properties:{charge:{state:'unknown',unit:'C'}}});saveObject(s,{...presetDraft('chargedPlate'),name:'Plate',properties:{surfaceChargeDensity:{state:'unknown',unit:'C/m^2'}}});saveObject(s,presetDraft('fluid'));expect(s.document.semantics.variables.map(v=>v.symbol)).toEqual(['q_{Pa}','\\sigma_{Pl}','\\rho_{W}']);expect(s.document.semantics.variables).toHaveLength(3);});
it('interaction quantities and component vectors use participants and update together',()=>{const s=new DocumentStore(),b=make(s,'Book'),t=make(s,'Table');const id=saveVector(s,{kind:'force',interactionType:'contact',contactType:'ordinary',sourceId:t,targetId:b,friction:'static',coefficient:{state:'unknown',unit:'1'},magnitude:unknown,resultantVisible:true});const v=s.document.semantics.vectors.find(v=>v.id===id)!;expect(symbol(s,v.variableId)).toBe('N_{T,B}');expect(s.document.semantics.variables.some(v=>v.symbol==='f_{T,B}')).toBe(true);expect(s.document.semantics.variables.some(v=>v.symbol==='F_{T,B}')).toBe(true);expect(s.document.semantics.variables.some(v=>v.symbol==='\\mu_{s,T,B}')).toBe(true);const ids=s.document.semantics.variables.map(v=>v.id);saveObject(s,{...objectDraft(s,b),name:'Novel'});expect(s.document.semantics.variables.map(v=>v.id).sort()).toEqual(ids.sort());expect(symbol(s,v.variableId)).toBe('N_{T,N}');});
it('expression IDs stay stable while rendered ingredients follow automatic renames',()=>{const s=new DocumentStore(),p=saveObject(s,presetDraft('planetSurface')),b=make(s,'Book'),mass=s.document.semantics.objects.find(o=>o.id===b)!.properties!.mass;const ast={type:'reference' as const,id:mass};const id=saveVector(s,{kind:'force',interactionType:'gravitational',sourceId:p,targetId:b,magnitude:{state:'expression',unit:'N',expression:ast}});saveObject(s,{...objectDraft(s,b),name:'Novel'});expect(expressionLatex(ast,s.document)).toBe('m_{N}');expect(s.document.semantics.variables.find(v=>v.ownerVectorId===id)!.expression).toEqual(ast);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});
it('historical custom property/vector symbols survive ordinary physical edits',()=>{const s=new DocumentStore(),b=saveObject(s,{name:'Book',representation:'circle',showName:true,showProperties:true,properties:{mass:{symbol:'M_{custom}',state:'unknown',unit:'kg'}}});const id=saveVector(s,{kind:'velocity',targetId:b,magnitude:{symbol:'u_{custom}',state:'unknown',unit:'m/s'}});saveObject(s,{...objectDraft(s,b),name:'Novel'});saveVector(s,{id,kind:'velocity',targetId:b,magnitude:{state:'known',unit:'m/s',value:3}});expect(s.document.semantics.variables.map(v=>v.symbol)).toEqual(['M_{custom}','u_{custom}']);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});
it('multiple relationships with the same notation get distinct symbols without redefining constants',()=>{const s=new DocumentStore(),b=make(s,'Book');saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'unknown',unit:'m/s'}});saveVector(s,{kind:'velocity',targetId:b,magnitude:{state:'unknown',unit:'m/s'}});expect(new Set(s.document.semantics.variables.map(v=>v.symbol)).size).toBe(3);expect(vectorLatex('r_{A,B}')).toBe('\\vec{r}_{A,B}');});

it('long and prefix-identical names remain readable within notation limits',()=>{const s=new DocumentStore();make(s,'A'.repeat(119)+'B');make(s,'A'.repeat(119)+'C');expect(new Set(s.document.semantics.objects.map(o=>o.abbreviation)).size).toBe(2);expect(s.document.semantics.variables.every(v=>v.symbol.length<=80)).toBe(true);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});

it('vector presentation keeps complex historical markup intact',()=>{expect(vectorLatex('\\frac{F_1}{2}')).toBe('\\vec{\\frac{F_1}{2}}');expect(vectorLatex('\\vec{u}_{custom}')).toBe('\\vec{u}_{custom}');});

it('removing a second spring or environment restores singleton notation and keeps remaining IDs',()=>{const s=new DocumentStore();const spring=saveObject(s,{...presetDraft('spring'),name:'Spring',properties:{springConstant:{state:'unknown',unit:'N/m'},extension:{state:'unknown',unit:'m'}}});const second=saveObject(s,{...presetDraft('spring'),name:'Elastic'});const ids=Object.values(s.document.semantics.objects.find(o=>o.id===spring)!.properties!);deleteObject(s,second);expect(ids.map(id=>symbol(s,id))).toEqual(['k','\\Delta x']);const p=saveObject(s,presetDraft('planetSurface')),other=saveObject(s,{...presetDraft('planetSurface'),name:'Mars'}),gravity=s.document.semantics.objects.find(o=>o.id===p)!.properties!.gravity;deleteObject(s,other);expect(symbol(s,gravity)).toBe('g');expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});
