import {it,expect} from 'vitest';
import {DocumentStore,newDocument} from '../../src/model';
import {saveObject,objectDraft,presetDraft} from '../../src/objects';
import {saveVector,vectorGraphic,isZeroMotionVector,displayedVector} from '../../src/physics';
import {parseDocument,serializeDocument,validateRelationships} from '../../src/persistence';
for(const [kind,unit]of [['acceleration','m/s^2'],['velocity','km/h'],['displacement','cm']] as const){
 it(`${kind}: known zero has label-only geometry and stable semantic identities, units and offsets`,()=>{const s=new DocumentStore(),object=saveObject(s,{...objectDraft(s),name:'Rock'});const id=saveVector(s,{kind,targetId:object,magnitude:{state:'known',value:0,unit}}),v=s.document.semantics.vectors[0],m=s.document.semantics.variables[0],g=vectorGraphic(s.document,id)!;expect(isZeroMotionVector(s.document,v)).toBe(true);expect(m).toMatchObject({id:v.variableId,state:'known',value:0,unit});expect(g).toMatchObject({kind:'text',points:[0,0,0,0],visible:true});expect(g.motionArrowPoints).toEqual([0,0,expect.any(Number),expect.any(Number)]);expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);const shown=displayedVector(s.document,v,g)!;expect(shown.points).toEqual([0,0,0,0]);expect(shown.label?.placement).toBe('objectCenter');});
 it(`${kind}: nonzero → zero → nonzero/unknown restores graphical configuration and undo`,()=>{const s=new DocumentStore(),object=saveObject(s,{...objectDraft(s),name:'Rock'});const draft={kind,targetId:object,magnitude:{state:'known' as const,value:4,unit}};const id=saveVector(s,draft),g=vectorGraphic(s.document,id)!;s.update(g.id,{points:[0,0,120,-60],showComponents:false,label:{...g.label!,offsetX:35,offsetY:22}});s.load(s.document);const before=structuredClone(s.document),v=before.semantics.vectors[0];saveVector(s,{...draft,id,magnitude:{state:'known',value:0,unit}});const zero=structuredClone(s.document);expect(zero.semantics.vectors).toEqual(before.semantics.vectors);expect(vectorGraphic(zero,id)).toMatchObject({id:g.id,kind:'text',points:[0,0,0,0],motionArrowPoints:[0,0,120,-60],showComponents:false,label:g.label});s.undo();expect(s.document).toEqual(before);s.redo();expect(s.document).toEqual(zero);s.load(parseDocument(serializeDocument(s.document)));saveVector(s,{...draft,id});expect(vectorGraphic(s.document,id)).toEqual(vectorGraphic(before,id));expect(s.document.semantics.vectors[0]).toEqual(v);saveVector(s,{...draft,id,magnitude:{state:'known',value:0,unit}});saveVector(s,{...draft,id,magnitude:{state:'unknown',unit}});expect(isZeroMotionVector(s.document,s.document.semantics.vectors[0])).toBe(false);expect(vectorGraphic(s.document,id)?.points).toEqual([0,0,120,-60]);expect(s.document.semantics.variables[0].value).toBeUndefined();});
 it(`${kind}: pre-fix zero-arrow documents load without an inconsistent visible arrow`,()=>{const s=new DocumentStore(),object=saveObject(s,{...objectDraft(s),name:'Rock'});const id=saveVector(s,{kind,targetId:object,magnitude:{state:'unknown',unit}});s.document.semantics.variables[0].state='known';s.document.semantics.variables[0].value=0;const source=structuredClone(s.document),loaded=parseDocument(serializeDocument(source));expect(loaded.semantics).toEqual(source.semantics);expect(vectorGraphic(loaded,id)).toMatchObject({kind:'text',points:[0,0,0,0]});expect(source.presentation.elements[1].kind).toBe('arrow');});
}
it('force and field zero magnitudes keep their previous arrow behavior',()=>{const s=new DocumentStore(),earth=saveObject(s,presetDraft('planetSurface')),rock=saveObject(s,{...objectDraft(s),name:'Rock'}),point=saveObject(s,presetDraft('spatialPoint'));for(const kind of ['force','field'] as const){const id=saveVector(s,{kind,sourceId:earth,targetId:kind==='force'?rock:point,interactionType:'gravitational',magnitude:{state:'known',value:0,unit:kind==='force'?'N':'m/s^2'}});const v=s.document.semantics.vectors.find(v=>v.id===id)!;expect(isZeroMotionVector(s.document,v)).toBe(false);expect(vectorGraphic(s.document,id)?.kind).toBe('arrow');expect(Math.hypot(...vectorGraphic(s.document,id)!.points)).toBeGreaterThan(0);}expect(parseDocument(serializeDocument(s.document))).toEqual(s.document);});
it('invalid label geometry/cache is rejected and hidden zero vectors remain hidden',()=>{const s=new DocumentStore(newDocument()),object=saveObject(s,{...objectDraft(s),name:'Rock'}),id=saveVector(s,{kind:'velocity',targetId:object,visible:false,magnitude:{state:'known',value:0,unit:'m/s'}});expect(vectorGraphic(s.document,id)?.visible).toBe(false);const d=structuredClone(s.document);vectorGraphic(d,id)!.points[2]=30;expect(()=>validateRelationships(d)).toThrow(/label-only/);vectorGraphic(d,id)!.points=[0,0,0,0];vectorGraphic(d,id)!.motionArrowPoints=[0,0,0,0];expect(()=>parseDocument(serializeDocument(d))).toThrow(/dormant/);});
